Repository OCA/server-tools, pull requests merged in 2018-12, with the labels that each got.

#1441 [FIX] base_exception: Migration scripts
  base_exception/__init__.py
  base_exception/__manifest__.py
  base_exception/hooks.py
  base_exception/migrations/10.0.1.0.0/pre-migration.py
Labels: approved, needs review

#1308 [auto_backup] show chatter; custom tempdir
  auto_backup/models/db_backup.py
  auto_backup/view/db_backup_view.xml
Labels: approved, needs review, ready to merge

#1455 [FIX][auth_dynamic_groups] don't break when there are no dynamic groups
  auth_dynamic_groups/__openerp__.py
  auth_dynamic_groups/model/res_groups.py
  auth_dynamic_groups/model/res_users.py
Labels: needs review

#1379 [ADD] 10.0 base_jsonify
  base_jsonify/README.rst
  base_jsonify/__init__.py
  base_jsonify/__manifest__.py
  base_jsonify/demo/export_demo.xml
  base_jsonify/demo/ir.exports.line.csv
  base_jsonify/models/__init__.py
  base_jsonify/models/ir_export.py
  base_jsonify/models/ir_exports_line.py
  base_jsonify/models/models.py
  base_jsonify/readme/CONTRIBUTORS.rst
  base_jsonify/readme/DESCRIPTION.rst
  base_jsonify/static/description/index.html
  base_jsonify/tests/__init__.py
  base_jsonify/tests/test_get_parser.py
  base_jsonify/tests/test_ir_exports_line.py
  base_jsonify/views/ir_exports_view.xml
Labels: approved, ready to merge

#1222 [10.0] Avoid crash in base_optional_quick_create during migration
  base_optional_quick_create/models/ir_model.py
Labels: approved

#1410 [10.0][IMP] base_exception add rules by domain and improve perfs
  base_exception/README.rst
  base_exception/__manifest__.py
  base_exception/migrations/10.0.2.0.0/pre-migration.py
  base_exception/models/base_exception.py
  base_exception/views/base_exception_view.xml
Labels: approved

#1466 [FIX] base_remote: Do not raise Error on login failure
  base_remote/__manifest__.py
  base_remote/models/base.py
  base_remote/models/res_users.py
  base_remote/tests/test_remote.py
Labels: approved
