Repository OCA/server-tools, pull requests merged in 2018-05, with the labels that each got.

#1065 [10.0][FIX] auth_totp: Various issues
  auth_totp/README.rst
  auth_totp/__manifest__.py
  auth_totp/controllers/main.py
  auth_totp/exceptions.py
  auth_totp/migrations/10.0.2.0.0/post-migrate.py
  auth_totp/models/__init__.py
  auth_totp/models/res_users.py
  auth_totp/models/res_users_device.py
  auth_totp/security/ir.model.access.csv
  auth_totp/tests/__init__.py
  auth_totp/tests/test_main.py
  auth_totp/tests/test_post_migrate.py
  auth_totp/tests/test_res_users.py
  auth_totp/views/auth_totp.xml
Labels: bug, needs review

#1219 [REF] auth_brute_force: Cover all auth entrypoints
  .travis.yml
  auth_brute_force/README.rst
  auth_brute_force/__init__.py
  auth_brute_force/__manifest__.py
  auth_brute_force/controllers/__init__.py
  auth_brute_force/controllers/main.py
  auth_brute_force/data/ir_config_parameter.xml
  auth_brute_force/migrations/10.0.2.0.0/pre-migrate.py
  auth_brute_force/models/__init__.py
  auth_brute_force/models/res_authentication_attempt.py
  auth_brute_force/models/res_banned_remote.py
  auth_brute_force/models/res_users.py
  auth_brute_force/security/ir_model_access.yml
  auth_brute_force/static/description/screenshot_custom_ban.png
  auth_brute_force/tests/__init__.py
  auth_brute_force/tests/test_brute_force.py
  auth_brute_force/views/action.xml
  auth_brute_force/views/menu.xml
  auth_brute_force/views/view.xml
Labels: bug, enhancement, needs review

#1250 [FIX] auth_brute_force: Small typos
  auth_brute_force/__manifest__.py
  auth_brute_force/views/view.xml
Labels: bug, needs review

#1251 [FIX] auth_brute_force: Fix addon requirement computation
  auth_brute_force/__manifest__.py
  auth_brute_force/tests/test_brute_force.py
Labels: bug, needs review

#1252 [FIX] module_auto_update: Ignore `__pycache__` in hash test
  module_auto_update/__manifest__.py
  module_auto_update/tests/test_addon_hash.py
Labels: needs review

#1254 [FIX] password_security: Create user as admin in tests
  password_security/__manifest__.py
  password_security/tests/test_res_users.py
Labels: needs review

#1256 [FIX] password_security: Default last write date
  password_security/__openerp__.py
  password_security/models/res_users.py
Labels: bug, needs review

#1148 [FIX] html_image_url_extractor: Do not test the specific exception
  html_image_url_extractor/tests/test_extractor.py
Labels: needs review

#1258 [FIX] auth_brute_force: Avoid storing false login attempts
  auth_brute_force/__openerp__.py
  auth_brute_force/models/res_authentication_attempt.py
  auth_brute_force/models/res_users.py
  auth_brute_force/views/action.xml
Labels: needs review
