Repository OCA/server-tools, pull requests merged in 2018-03, with the labels that each got.

#1183 8.0 auth brute force log request environment
  auth_brute_force/README.rst
  auth_brute_force/controllers/controllers.py
  auth_brute_force/models/res_authentication_attempt.py
  auth_brute_force/views/view.xml
Labels: needs review

#1184 [FIX] auth_signup_verify_email: Better integration tests
  auth_signup_verify_email/tests/test_verify_email.py
Labels: bug, needs review

#1147 [11.0] [MIG] base_technical_user
  base_technical_user/README.rst
  base_technical_user/__init__.py
  base_technical_user/__manifest__.py
  base_technical_user/i18n/de.po
  base_technical_user/i18n/es.po
  base_technical_user/i18n/fr.po
  base_technical_user/i18n/hr.po
  base_technical_user/i18n/it.po
  base_technical_user/i18n/nl_NL.po
  base_technical_user/i18n/pt.po
  base_technical_user/models/__init__.py
  base_technical_user/models/res_company.py
  base_technical_user/views/res_company_view.xml
Labels: needs review

#1190 [REF] module_auto_update: Deprecate buggy features, add new API
  module_auto_update/README.rst
  module_auto_update/__init__.py
  module_auto_update/__openerp__.py
  module_auto_update/addon_hash.py
  module_auto_update/data/cron_data_deprecated.xml
  module_auto_update/hooks.py
  module_auto_update/migrations/9.0.2.0.0/pre-migrate.py
  module_auto_update/models/__init__.py
  module_auto_update/models/module.py
  module_auto_update/models/module_deprecated.py
  module_auto_update/tests/__init__.py
  module_auto_update/tests/sample_module/README.rst
  module_auto_update/tests/sample_module/data/f1.xml
  module_auto_update/tests/sample_module/data/f2.xml
  module_auto_update/tests/sample_module/i18n/en.po
  module_auto_update/tests/sample_module/i18n/en_US.po
  module_auto_update/tests/sample_module/i18n/fr.po
  module_auto_update/tests/sample_module/i18n/fr_BE.po
  module_auto_update/tests/sample_module/i18n/test.pot
  module_auto_update/tests/sample_module/i18n_extra/en.po
  module_auto_update/tests/sample_module/i18n_extra/fr.po
  module_auto_update/tests/sample_module/i18n_extra/nl_NL.po
  module_auto_update/tests/sample_module/models/stuff.py
  module_auto_update/tests/sample_module/models/stuff.pyc
  module_auto_update/tests/sample_module/static/src/some.js
  module_auto_update/tests/test_addon_hash.py
  module_auto_update/tests/test_module.py
  module_auto_update/tests/test_module_deprecated.py
  module_auto_update/tests/test_module_upgrade_deprecated.py
  module_auto_update/views/module_views.xml
  module_auto_update/wizards/__init__.py
  module_auto_update/wizards/module_upgrade.py
  module_auto_update/wizards/module_upgrade_deprecated.py
  requirements.txt
Labels: enhancement, needs review

#1205 [FIX] module_auto_update: Add .pyo sample file
  module_auto_update/__openerp__.py
  module_auto_update/tests/sample_module/models/stuff.pyo
  module_auto_update/tests/test_addon_hash.py
Labels: bug, needs review

#1206 [FIX] module_auto_update: Rollback cursor if param exists
  module_auto_update/migrations/9.0.2.0.0/pre-migrate.py
Labels: bug, needs review

#1198 [MIG][8.0] module_auto_update backport from 9
  module_auto_update/README.rst
  module_auto_update/__init__.py
  module_auto_update/__openerp__.py
  module_auto_update/addon_hash.py
  module_auto_update/hooks.py
  module_auto_update/i18n/ca.po
  module_auto_update/i18n/de.po
  module_auto_update/i18n/es.po
  module_auto_update/i18n/es_MX.po
  module_auto_update/i18n/fr.po
  module_auto_update/i18n/hr.po
  module_auto_update/i18n/it.po
  module_auto_update/i18n/nl_NL.po
  module_auto_update/i18n/pt_BR.po
  module_auto_update/i18n/sl.po
  module_auto_update/i18n/tr.po
  module_auto_update/models/__init__.py
  module_auto_update/models/module.py
  module_auto_update/models/module_deprecated.py
  module_auto_update/tests/__init__.py
  module_auto_update/tests/sample_module/README.rst
  module_auto_update/tests/sample_module/data/f1.xml
  module_auto_update/tests/sample_module/data/f2.xml
  module_auto_update/tests/sample_module/i18n/en.po
  module_auto_update/tests/sample_module/i18n/en_US.po
  module_auto_update/tests/sample_module/i18n/fr.po
  module_auto_update/tests/sample_module/i18n/fr_BE.po
  module_auto_update/tests/sample_module/i18n/test.pot
  module_auto_update/tests/sample_module/i18n_extra/en.po
  module_auto_update/tests/sample_module/i18n_extra/fr.po
  module_auto_update/tests/sample_module/i18n_extra/nl_NL.po
  module_auto_update/tests/sample_module/models/stuff.py
  module_auto_update/tests/sample_module/models/stuff.pyc
  module_auto_update/tests/sample_module/models/stuff.pyo
  module_auto_update/tests/sample_module/static/src/some.js
  module_auto_update/tests/test_addon_hash.py
  module_auto_update/tests/test_module.py
Labels: needs review

#1207 [10.0] module_auto_update forward port 9.0
  module_auto_update/README.rst
  module_auto_update/__init__.py
  module_auto_update/__manifest__.py
  module_auto_update/addon_hash.py
  module_auto_update/data/cron_data_deprecated.xml
  module_auto_update/hooks.py
  module_auto_update/migrations/10.0.2.0.0/pre-migrate.py
  module_auto_update/models/__init__.py
  module_auto_update/models/module.py
  module_auto_update/models/module_deprecated.py
  module_auto_update/tests/__init__.py
  module_auto_update/tests/sample_module/README.rst
  module_auto_update/tests/sample_module/data/f1.xml
  module_auto_update/tests/sample_module/data/f2.xml
  module_auto_update/tests/sample_module/i18n/en.po
  module_auto_update/tests/sample_module/i18n/en_US.po
  module_auto_update/tests/sample_module/i18n/fr.po
  module_auto_update/tests/sample_module/i18n/fr_BE.po
  module_auto_update/tests/sample_module/i18n/test.pot
  module_auto_update/tests/sample_module/i18n_extra/en.po
  module_auto_update/tests/sample_module/i18n_extra/fr.po
  module_auto_update/tests/sample_module/i18n_extra/nl_NL.po
  module_auto_update/tests/sample_module/models/stuff.py
  module_auto_update/tests/sample_module/models/stuff.pyc
  module_auto_update/tests/sample_module/models/stuff.pyo
  module_auto_update/tests/sample_module/static/src/some.js
  module_auto_update/tests/test_addon_hash.py
  module_auto_update/tests/test_module.py
  module_auto_update/tests/test_module_deprecated.py
  module_auto_update/tests/test_module_upgrade_deprecated.py
  module_auto_update/views/module_views.xml
  module_auto_update/wizards/__init__.py
  module_auto_update/wizards/module_upgrade.py
  module_auto_update/wizards/module_upgrade_deprecated.py
Labels: needs review

#1059 [ADD] create an xmlid for mapped records too
  base_import_odoo/models/import_odoo_database.py
Labels: needs review
