Repository OCA/server-tools, pull requests merged in 2019-02, with the labels that each got.

#1509 [FIX] add perm_read in ir.model.access for base.group_user to avoid b…
  base_user_role/security/ir.model.access.csv
Labels: approved, ready to merge

#1080 [8.0][sql_export] Allow to use many2one and many2many fields for query variables
  sql_export/wizard/wizard_file.py
Labels: approved, needs review

#1518 [9.0] [FIX] auth_ldap_populate
  users_ldap_populate/__openerp__.py
  users_ldap_populate/models/users_ldap.py
Labels: approved

#1520 [10.0][FIX] auth_ldap_populate
  users_ldap_populate/__manifest__.py
  users_ldap_populate/models/users_ldap.py
Labels: approved
