Repository OCA/server-tools, pull requests merged in 2019-03, with the labels that each got.

#1519 [8.0][FIX] auth ldap populate
  users_ldap_populate/__init__.py
  users_ldap_populate/models/__init__.py
  users_ldap_populate/models/populate_wizard.py
  users_ldap_populate/models/users_ldap.py
  users_ldap_populate/view/users_ldap.xml
Labels: approved

#1496 12.0 mig datetime_formatter
  datetime_formatter/README.rst
  datetime_formatter/__init__.py
  datetime_formatter/__manifest__.py
  datetime_formatter/i18n/ar.po
  datetime_formatter/i18n/ca.po
  datetime_formatter/i18n/datetime_formatter.pot
  datetime_formatter/i18n/de.po
  datetime_formatter/i18n/es.po
  datetime_formatter/i18n/fr.po
  datetime_formatter/i18n/hr.po
  datetime_formatter/i18n/it.po
  datetime_formatter/i18n/nl_NL.po
  datetime_formatter/i18n/sl.po
  datetime_formatter/i18n/tr.po
  datetime_formatter/models/__init__.py
  datetime_formatter/models/res_lang.py
  datetime_formatter/readme/CONTRIBUTORS.rst
  datetime_formatter/readme/DESCRIPTION.rst
  datetime_formatter/readme/USAGE.rst
  datetime_formatter/static/description/icon.png
  datetime_formatter/static/description/index.html
  datetime_formatter/tests/__init__.py
  datetime_formatter/tests/test_best_matcher.py
  datetime_formatter/tests/test_formatter.py
Labels: approved, needs review

#1524 [12.0][MIG] scheduler_error_mailer: Migration to v12
  scheduler_error_mailer/README.rst
  scheduler_error_mailer/__init__.py
  scheduler_error_mailer/__manifest__.py
  scheduler_error_mailer/data/ir_cron_email_tpl.xml
  scheduler_error_mailer/demo/ir_cron_demo.xml
  scheduler_error_mailer/i18n/de.po
  scheduler_error_mailer/i18n/es.po
  scheduler_error_mailer/i18n/hr.po
  scheduler_error_mailer/i18n/pt_BR.po
  scheduler_error_mailer/i18n/scheduler_error_mailer.pot
  scheduler_error_mailer/i18n/sl.po
  scheduler_error_mailer/i18n/zh_CN.po
  scheduler_error_mailer/images/scheduler_error_mailer.jpg
  scheduler_error_mailer/models/__init__.py
  scheduler_error_mailer/models/ir_cron.py
  scheduler_error_mailer/readme/CONFIGURE.rst
  scheduler_error_mailer/readme/CONTRIBUTORS.rst
  scheduler_error_mailer/readme/DESCRIPTION.rst
  scheduler_error_mailer/static/description/icon.png
  scheduler_error_mailer/views/ir_cron.xml
Labels: approved

#1526 [FIX] Monkeypatch TestCursor in auth_brute_force's tests
  auth_brute_force/tests/test_brute_force.py
Labels: approved, bug, needs review

#1489 [10.0] base user role multicompany adapting
  base_user_role/__manifest__.py
  base_user_role/models/role.py
  base_user_role/models/user.py
  base_user_role/tests/test_user_role.py
  base_user_role/views/role.xml
  base_user_role/views/user.xml
Labels: approved

#1527 module_auto_update: remove maintainer
  module_auto_update/__manifest__.py
Labels: approved

#1506 [FIX][database_cleanup] don't destroy values when there are empty default properties
  database_cleanup/models/purge_properties.py
  database_cleanup/views/create_indexes.xml
  database_cleanup/views/purge_columns.xml
  database_cleanup/views/purge_data.xml
  database_cleanup/views/purge_menus.xml
  database_cleanup/views/purge_models.xml
  database_cleanup/views/purge_modules.xml
  database_cleanup/views/purge_properties.xml
  database_cleanup/views/purge_tables.xml
Labels: approved, needs review

#1507 [PRT][11.0][database_cleanup] forward port features
  database_cleanup/models/purge_modules.py
  database_cleanup/models/purge_properties.py
Labels: approved, needs review

#1505 [12.0][IMP] module_auto_update: UI button
  module_auto_update/README.rst
  module_auto_update/__init__.py
  module_auto_update/__manifest__.py
  module_auto_update/addon_hash.py
  module_auto_update/hooks.py
  module_auto_update/models/__init__.py
  module_auto_update/models/module.py
  module_auto_update/readme/USAGE.rst
  module_auto_update/static/description/index.html
  module_auto_update/tests/__init__.py
  module_auto_update/tests/test_addon_hash.py
  module_auto_update/tests/test_module.py
  module_auto_update/views/ir_module_module.xml
Labels: approved, ready to merge

#1522 Excel Import/Export/Report
  excel_import_export/README.rst
  excel_import_export/__init__.py
  excel_import_export/__manifest__.py
  excel_import_export/models/__init__.py
  excel_import_export/models/common.py
  excel_import_export/models/styles.py
  excel_import_export/models/xlsx_export.py
  excel_import_export/models/xlsx_import.py
  excel_import_export/models/xlsx_report.py
  excel_import_export/models/xlsx_template.py
  excel_import_export/readme/CONTRIBUTORS.rst
  excel_import_export/readme/DESCRIPTION.rst
  excel_import_export/readme/HISTORY.rst
  excel_import_export/readme/INSTALL.rst
  excel_import_export/readme/ROADMAP.rst
  excel_import_export/readme/USAGE.rst
  excel_import_export/security/ir.model.access.csv
  excel_import_export/static/description/index.html
  excel_import_export/views/xlsx_report.xml
  excel_import_export/views/xlsx_template_view.xml
  excel_import_export/wizard/__init__.py
  excel_import_export/wizard/export_xlsx_wizard.py
  excel_import_export/wizard/export_xlsx_wizard.xml
  excel_import_export/wizard/import_xlsx_wizard.py
  excel_import_export/wizard/import_xlsx_wizard.xml
  excel_import_export_demo/README.rst
  excel_import_export_demo/__init__.py
  excel_import_export_demo/__manifest__.py
  excel_import_export_demo/import_export_sale_order/actions.xml
  excel_import_export_demo/import_export_sale_order/sale_order.xlsx
  excel_import_export_demo/import_export_sale_order/templates.xml
  excel_import_export_demo/import_sale_orders/import_sale_order.xlsx
  excel_import_export_demo/import_sale_orders/menu_action.xml
  excel_import_export_demo/import_sale_orders/templates.xml
  excel_import_export_demo/readme/CONTRIBUTORS.rst
  excel_import_export_demo/readme/DESCRIPTION.rst
  excel_import_export_demo/readme/HISTORY.rst
  excel_import_export_demo/readme/INSTALL.rst
  excel_import_export_demo/readme/USAGE.rst
  excel_import_export_demo/report_sale_order/__init__.py
  excel_import_export_demo/report_sale_order/report_sale_order.py
  excel_import_export_demo/report_sale_order/report_sale_order.xlsx
  excel_import_export_demo/report_sale_order/report_sale_order.xml
  excel_import_export_demo/report_sale_order/templates.xml
  excel_import_export_demo/static/description/index.html
  excel_import_export_demo/tests/__init__.py
  excel_import_export_demo/tests/sale_order.xlsx
  excel_import_export_demo/tests/test_common.py
  excel_import_export_demo/tests/test_xlsx_import_export.py
  excel_import_export_demo/tests/test_xlsx_report.py
  excel_import_export_demo/tests/test_xlsx_template.py
  requirements.txt
Labels: approved, ready to merge

#1517 [11.0][resource_calendar_schedule_iterations]
  resource_calendar_schedule_iteration/README.rst
  resource_calendar_schedule_iteration/__init__.py
  resource_calendar_schedule_iteration/__manifest__.py
  resource_calendar_schedule_iteration/data/ir_config_parameter_data.xml
  resource_calendar_schedule_iteration/hooks.py
  resource_calendar_schedule_iteration/model/__init__.py
  resource_calendar_schedule_iteration/model/resource_calendar.py
  resource_calendar_schedule_iteration/readme/CONFIGURE.rst
  resource_calendar_schedule_iteration/readme/CONTRIBUTORS.rst
  resource_calendar_schedule_iteration/readme/DESCRIPTION.rst
  resource_calendar_schedule_iteration/static/description/icon.png
  resource_calendar_schedule_iteration/static/description/index.html
  resource_calendar_schedule_iteration/tests/__init__.py
  resource_calendar_schedule_iteration/tests/test_resource_calendar_schedule_iteration.py
Labels: approved, ready to merge

#1472 [12.0][MIG] base_jsonify
  base_jsonify/README.rst
  base_jsonify/__init__.py
  base_jsonify/__manifest__.py
  base_jsonify/demo/export_demo.xml
  base_jsonify/demo/ir.exports.line.csv
  base_jsonify/i18n/base_jsonify.pot
  base_jsonify/models/__init__.py
  base_jsonify/models/ir_export.py
  base_jsonify/models/ir_exports_line.py
  base_jsonify/models/models.py
  base_jsonify/readme/CONTRIBUTORS.rst
  base_jsonify/readme/DESCRIPTION.rst
  base_jsonify/static/description/index.html
  base_jsonify/tests/__init__.py
  base_jsonify/tests/test_get_parser.py
  base_jsonify/tests/test_ir_exports_line.py
  base_jsonify/views/ir_exports_view.xml
Labels: approved

#1531 [FIX] users_ldap_populate: Wrong attribute usage
  users_ldap_populate/README.rst
  users_ldap_populate/models/users_ldap.py
Labels: bug

#1495 [FIX] Use _compute_session_token to invalidate user sessions on auth_session_timeout
  auth_session_timeout/models/res_users.py
  auth_session_timeout/tests/test_res_users.py
Labels: approved, needs review, ready to merge
