Repository OCA/server-tools, pull requests merged in 2019-06, with the labels that each got.

#1586 [10.0][base_exception] Simplifies code and fix rules by domain
  base_exception/README.rst
  base_exception/__manifest__.py
  base_exception/models/base_exception.py
  base_exception/views/base_exception_view.xml
Labels: approved

#1587 12.0 fontawesome
  base_fontawesome/README.rst
  base_fontawesome/__init__.py
  base_fontawesome/__manifest__.py
  base_fontawesome/i18n/base_fontawesome.pot
  base_fontawesome/i18n/es_ES.po
  base_fontawesome/readme/CONTRIBUTORS.rst
  base_fontawesome/readme/DESCRIPTION.rst
  base_fontawesome/readme/USAGE.rst
  base_fontawesome/static/description/icon.png
  base_fontawesome/static/description/index.html
  base_fontawesome/static/lib/fontawesome-5.7.1/css/all.css
  base_fontawesome/static/lib/fontawesome-5.7.1/css/v4-shims.css
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-brands-400.eot
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-brands-400.svg
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-brands-400.ttf
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-brands-400.woff
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-brands-400.woff2
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-regular-400.eot
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-regular-400.svg
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-regular-400.ttf
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-regular-400.woff
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-regular-400.woff2
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-solid-900.eot
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-solid-900.svg
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-solid-900.ttf
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-solid-900.woff
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-solid-900.woff2
  base_fontawesome/static/src/css/fontawesome.css
  base_fontawesome/static/src/js/form_renderer.js
  base_fontawesome/static/src/js/list_renderer.js
  base_fontawesome/templates/assets.xml
Labels: approved, ready to merge

#1589 [12.0][base_exception] Refactore base_exception in order to drastically simplify it
  base_exception/__manifest__.py
  base_exception/models/base_exception.py
  base_exception/tests/purchase_test.py
  base_exception/tests/test_base_exception.py
  base_exception/views/base_exception_view.xml
Labels: approved

#1597 FIX base_exception: typo
  base_exception/__manifest__.py
  base_exception/models/base_exception.py
Labels: approved

#1598 [10.0][FIX] base_exception fix intersection operator
  base_exception/__manifest__.py
  base_exception/models/base_exception.py
Labels: approved

#1599 [12.0][FIX] base_exception fix intersection operator
  base_exception/__manifest__.py
  base_exception/models/base_exception.py
Labels: approved

#1602 [12.0][base_exception] Fix union between recordset and parent recordset in base_exception
  base_exception/__manifest__.py
  base_exception/models/base_exception.py
Labels: approved

#1601 [10.0][base_exception] Fix union between recordset and parent recordset in base_exception
  base_exception/__manifest__.py
  base_exception/models/base_exception.py
Labels: approved

#1491 [FIX] Import safe_eval function instead of module.
  auth_admin_passkey/models/res_config.py
Labels: approved, ready to merge

#1575 [DEL] auth_dynamic_groups lives in server-auth by now
  auth_dynamic_groups/README.rst
  auth_dynamic_groups/__init__.py
  auth_dynamic_groups/__manifest__.py
  auth_dynamic_groups/i18n/de.po
  auth_dynamic_groups/i18n/es.po
  auth_dynamic_groups/i18n/fr.po
  auth_dynamic_groups/i18n/pt_BR.po
  auth_dynamic_groups/i18n/sl.po
  auth_dynamic_groups/model/__init__.py
  auth_dynamic_groups/model/res_groups.py
  auth_dynamic_groups/model/res_users.py
  auth_dynamic_groups/static/description/icon.png
  auth_dynamic_groups/view/res_groups.xml
Labels: needs review
