Repository OCA/server-tools, pull requests merged in 2019-01, with the labels that each got.

#1471 Switch AGPL to LGPL license
  base_user_role/README.rst
  base_user_role/__manifest__.py
  base_user_role/data/ir_cron.xml
  base_user_role/data/ir_module_category.xml
  base_user_role/models/role.py
  base_user_role/models/user.py
  base_user_role/tests/test_user_role.py
  base_user_role/views/role.xml
  base_user_role/views/user.xml
Labels: approved, needs review, ready to merge

#1470 Switch AGPL to LGPL license
  base_user_role/README.rst
  base_user_role/__openerp__.py
  base_user_role/data/ir_cron.xml
  base_user_role/data/ir_module_category.xml
  base_user_role/models/role.py
  base_user_role/models/user.py
  base_user_role/tests/test_user_role.py
  base_user_role/views/role.xml
  base_user_role/views/user.xml
Labels: approved, needs review

#1474 [10][IMP] base_exception allow to filter rules
  base_exception/__manifest__.py
  base_exception/models/base_exception.py
Labels: approved, ready to merge

#1407 [11.0] [MIG] base_view_inheritance_extension: Migration to v11.0
  base_view_inheritance_extension/README.rst
  base_view_inheritance_extension/__init__.py
  base_view_inheritance_extension/__manifest__.py
  base_view_inheritance_extension/demo/ir_ui_view.xml
  base_view_inheritance_extension/i18n/base_view_inheritance_extension.pot
  base_view_inheritance_extension/i18n/ca.po
  base_view_inheritance_extension/i18n/de.po
  base_view_inheritance_extension/i18n/es.po
  base_view_inheritance_extension/i18n/hr.po
  base_view_inheritance_extension/i18n/it.po
  base_view_inheritance_extension/i18n/sl.po
  base_view_inheritance_extension/i18n/tr.po
  base_view_inheritance_extension/models/__init__.py
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/readme/CONTRIBUTORS.rst
  base_view_inheritance_extension/readme/DESCRIPTION.rst
  base_view_inheritance_extension/readme/ROADMAP.rst
  base_view_inheritance_extension/readme/USAGE.rst
  base_view_inheritance_extension/static/description/icon.png
  base_view_inheritance_extension/static/description/index.html
  base_view_inheritance_extension/tests/__init__.py
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
Labels: approved, needs review

#1481 [10.0][ADD] Add new module sequence_date_range
  sequence_date_range/README.rst
  sequence_date_range/__init__.py
  sequence_date_range/__manifest__.py
  sequence_date_range/demo/ir_sequence.xml
  sequence_date_range/models/__init__.py
  sequence_date_range/models/ir_sequence.py
  sequence_date_range/models/ir_sequence_date_range.py
  sequence_date_range/readme/CONTRIBUTORS.rst
  sequence_date_range/readme/DESCRIPTION.rst
  sequence_date_range/static/description/index.html
  sequence_date_range/tests/__init__.py
  sequence_date_range/tests/test_ir_sequence_date_range.py
  sequence_date_range/views/ir_sequence.xml
  setup/sequence_date_range/odoo/__init__.py
  setup/sequence_date_range/odoo/addons/__init__.py
  setup/sequence_date_range/odoo/addons/sequence_date_range
  setup/sequence_date_range/setup.py
Labels: approved

#1477 [FIX] strange behavior of users_ldap_populate
  users_ldap_populate/models/users_ldap.py
Labels: approved

#1484 [FIX] don't remove computed fields with inverse method of the onchange values
  onchange_helper/models/models.py
Labels: approved, ready to merge

#1486 [FIX][10.0]Make a defensive check before processing table and model rename
  base_exception/migrations/10.0.2.0.0/pre-migration.py
Labels: approved

#1487 [8.0] auth_ldap_populate: backport fix of #1477
  users_ldap_populate/model/users_ldap.py
Labels: approved
