Repository OCA/server-tools, pull requests merged in 2019-10, with the labels that each got.

#1609 [IMP][12.0][base_exception] Improvements on base_exception
  base_exception/README.rst
  base_exception/__manifest__.py
  base_exception/models/base_exception.py
  base_exception/readme/CONTRIBUTORS.rst
Labels: approved, merged 🎉

#1644 [10.0] base_exception: Remove side effect from api.constrains
  base_exception/models/base_exception.py
Labels: approved

#1703 [8.0][shell] force rollback on exit
  shell/cli/shell.py
Labels: approved, needs review

#1708 IMP print failed query to help debugging
  sql_request_abstract/models/sql_request_mixin.py
Labels: approved

#1711 [12.0][FIX] base_jsonify: In odoo 12, Date and Datetime fields values are d…
  base_jsonify/models/models.py
  base_jsonify/tests/test_get_parser.py
Labels: approved
