Repository OCA/server-tools, pull requests merged in 2020-11, with the labels that each got.

#1923 [IMP] update dotfiles
  .pylintrc
  .pylintrc-mandatory
Labels: bot is merging ⏳, needs review

#1749 [IMP][8.0] base_import_odoo: show inactive records also
  base_import_odoo/views/import_odoo_database.xml
Labels: approved, bot is merging ⏳, ready to merge

#1921 [12.0][FIX] excel_import_export, Change color in bold_red style
  excel_import_export/__manifest__.py
  excel_import_export/models/styles.py
  excel_import_export_demo/__manifest__.py
Labels: bot is merging ⏳

#1592 [FIX] fix security issue due to wrong cache invalidation
  base_suspend_security/models/ir_model_access.py
  base_suspend_security/tests/test_base_suspend_security.py
Labels: approved

#1567 [10.0] users_ldap_groups. Support for special characters.
  users_ldap_groups/models/res_company_ldap_operator.py
Labels: approved, bot is merging ⏳, ready to merge

#1912 [IMP] base_jsonify: Allow to export many2one and referene field as si…
  base_jsonify/models/models.py
Labels: approved, bot is merging ⏳
