Repository OCA/server-tools, pull requests merged in 2020-04, with the labels that each got.

#1787 [12.0][FIX] excel_import_export, problem on import with datetime field
  excel_import_export/models/common.py
  excel_import_export/models/xlsx_import.py
Labels: approved, bot is merging ⏳, ready to merge

#1731 [7.0][IMP][server_environment_files] Rename folder to sample to avoid local conflict
  .travis.yml
  server_environment_files_sample/__init__.py
  server_environment_files_sample/__openerp__.py
  server_environment_files_sample/default/base.conf
  server_environment_files_sample/default/mytopic.conf
  server_environment_files_sample/dev/base.conf
  server_environment_files_sample/dev/mytopic.conf
  server_environment_files_sample/i18n/server_environment_files.pot
  server_environment_files_sample/preprod/mytopic.conf
  server_environment_files_sample/prod/base.conf
  server_environment_files_sample/prod/mytopic.conf
Labels: approved

#1797 [IMP] purge uninstalled unavailable modules in bulk
  database_cleanup/models/purge_modules.py
  database_cleanup/tests/test_database_cleanup.py
Labels: approved, bot is merging ⏳

#1389 [FIX][8.0] Hard default True, dont break default name_search for models added after this module
  base_name_search_improved/__init__.py
  base_name_search_improved/__openerp__.py
  base_name_search_improved/hooks.py
  base_name_search_improved/migrations/8.0.1.2.0/post-migration.py
  base_name_search_improved/tests/test_name_search.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1039 [ADD] support user_ids for user specific view overrides
  base_view_inheritance_extension/README.rst
  base_view_inheritance_extension/demo/ir_ui_view.xml
  base_view_inheritance_extension/models/__init__.py
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/models/res_users.py
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
Labels: approved, ready to merge

#1607 [12.0][MIG] fetchmail_incoming_log
  fetchmail_incoming_log/README.rst
  fetchmail_incoming_log/__init__.py
  fetchmail_incoming_log/__manifest__.py
  fetchmail_incoming_log/i18n/ca.po
  fetchmail_incoming_log/i18n/de.po
  fetchmail_incoming_log/i18n/es.po
  fetchmail_incoming_log/i18n/fetchmail_incoming_log.pot
  fetchmail_incoming_log/i18n/fr.po
  fetchmail_incoming_log/i18n/it.po
  fetchmail_incoming_log/i18n/mail_log_message_to_process.pot
  fetchmail_incoming_log/i18n/pt_BR.po
  fetchmail_incoming_log/i18n/pt_PT.po
  fetchmail_incoming_log/i18n/sl.po
  fetchmail_incoming_log/i18n/tr.po
  fetchmail_incoming_log/models/__init__.py
  fetchmail_incoming_log/models/mail_thread.py
  fetchmail_incoming_log/readme/CONTRIBUTORS.rst
  fetchmail_incoming_log/readme/DESCRIPTION.rst
  fetchmail_incoming_log/static/description/icon.png
  fetchmail_incoming_log/static/description/index.html
  fetchmail_incoming_log/tests/__init__.py
  fetchmail_incoming_log/tests/test_fetchmail_incoming_log.py
Labels: approved, bot is merging ⏳, ready to merge

#1594 [12.0][MIG] base_remote
  base_remote/README.rst
  base_remote/__init__.py
  base_remote/__manifest__.py
  base_remote/i18n/base_remote.pot
  base_remote/i18n/es.po
  base_remote/models/__init__.py
  base_remote/models/base.py
  base_remote/models/res_remote.py
  base_remote/models/res_users.py
  base_remote/readme/CONTRIBUTORS.rst
  base_remote/readme/DESCRIPTION.rst
  base_remote/readme/USAGE.rst
  base_remote/security/ir.model.access.csv
  base_remote/static/description/index.html
  base_remote/tests/__init__.py
  base_remote/tests/test_remote.py
  base_remote/views/res_remote_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#1663 [8.0][FIX] users_ldap_push: Don't fail when having attribute values that are not ASCII
  users_ldap_push/models/res_users.py
Labels: approved, bot is merging ⏳, ready to merge

#1798 [13.0][ADD] base_time_window
  base_time_window/__init__.py
  base_time_window/__manifest__.py
  base_time_window/data/time_weekday.xml
  base_time_window/models/__init__.py
  base_time_window/models/time_weekday.py
  base_time_window/models/time_window_mixin.py
  base_time_window/readme/CONTRIBUTORS.rst
  base_time_window/readme/DESCRIPTION.rst
  base_time_window/readme/ROADMAP.rst
  base_time_window/readme/USAGE.rst
  base_time_window/security/ir.model.access.xml
  setup/base_time_window/odoo/addons/base_time_window
  setup/base_time_window/setup.py
  setup/test_base_time_window/odoo/addons/test_base_time_window
  setup/test_base_time_window/setup.py
  test_base_time_window/__init__.py
  test_base_time_window/__manifest__.py
  test_base_time_window/models/__init__.py
  test_base_time_window/models/partner_time_window.py
  test_base_time_window/models/res_partner.py
  test_base_time_window/readme/CONTRIBUTORS.rst
  test_base_time_window/readme/DESCRIPTION.rst
  test_base_time_window/security/ir.model.access.xml
  test_base_time_window/tests/__init__.py
  test_base_time_window/tests/test_base_time_window.py
Labels: approved, bot is merging ⏳

#1762 13.0 mig mail server relay disallowed
  mail_server_relay_disallowed/README.rst
  mail_server_relay_disallowed/__init__.py
  mail_server_relay_disallowed/__manifest__.py
  mail_server_relay_disallowed/models/__init__.py
  mail_server_relay_disallowed/models/ir_mail_server.py
  mail_server_relay_disallowed/readme/CONTRIBUTORS.rst
  mail_server_relay_disallowed/readme/DESCRIPTION.rst
  mail_server_relay_disallowed/readme/USAGE.rst
  mail_server_relay_disallowed/static/description/icon.png
  mail_server_relay_disallowed/static/description/index.html
Labels: bot is merging ⏳

#1814 [12.0][FIX] base_remote: search =ilike
  base_remote/models/res_remote.py
Labels: bot is merging ⏳

#1824 [IMP] add helper for getting a self env with the tech user
  base_technical_user/README.rst
  base_technical_user/models/__init__.py
  base_technical_user/models/models.py
  base_technical_user/tests/__init__.py
  base_technical_user/tests/test_sudo_tech.py
Labels: approved, bot is merging ⏳
