Repository OCA/server-tools, pull requests merged in 2020-09, with the labels that each got.

#1861 [WIP][12.0][ADD] add iap_alternative_provider
  .travis.yml
  iap_alternative_provider/__init__.py
  iap_alternative_provider/__manifest__.py
  iap_alternative_provider/models/__init__.py
  iap_alternative_provider/models/iap_account.py
  iap_alternative_provider/readme/CONTRIBUTORS.rst
  iap_alternative_provider/readme/DESCRIPTION.rst
  iap_alternative_provider/views/iap_account_view.xml
Labels: bot is merging ⏳

#1899 [12.0][FIX] excel_import_export: external ids naming.
  excel_import_export/models/xlsx_import.py
Labels: approved, bot is merging ⏳

#1903 [12.0] Adding oca_dependencies.txt to server_tools
  oca_dependencies.txt
Labels: approved, bot is merging ⏳

#1904 base_jsonify: allow export line exclusion
  base_jsonify/models/ir_exports_line.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1906 base_jsonify: return one record on demand
  base_jsonify/models/models.py
  base_jsonify/tests/test_get_parser.py
Labels: approved, bot is merging ⏳, needs review

#1873 [13.0][ADD] base_name_search_multi_lang
  base_name_search_multi_lang/__init__.py
  base_name_search_multi_lang/__manifest__.py
  base_name_search_multi_lang/models/__init__.py
  base_name_search_multi_lang/models/ir_model.py
  base_name_search_multi_lang/readme/CONFIGURE.rst
  base_name_search_multi_lang/readme/CONTRIBUTORS.rst
  base_name_search_multi_lang/readme/DESCRIPTION.rst
  base_name_search_multi_lang/readme/USAGE.rst
  base_name_search_multi_lang/static/description/icon.png
  base_name_search_multi_lang/tests/__init__.py
  base_name_search_multi_lang/tests/test_name_search.py
  base_name_search_multi_lang/views/ir_model_views.xml
  setup/base_name_search_multi_lang/odoo/addons/base_name_search_multi_lang
  setup/base_name_search_multi_lang/setup.py
Labels: approved, bot is merging ⏳, ready to merge
