Repository OCA/server-tools, pull requests merged in 2020-06, with the labels that each got.

#1838 [12.0][PORT] #1824 from 10.0: [IMP] add helper for getting a self env with the tech user
  base_technical_user/README.rst
  base_technical_user/models/__init__.py
  base_technical_user/models/models.py
  base_technical_user/readme/USAGE.rst
  base_technical_user/static/description/index.html
  base_technical_user/tests/__init__.py
  base_technical_user/tests/test_sudo_tech.py
Labels: approved, bot is merging ⏳, ready to merge

#1829 [13.0] base_jsonify: support callable parser
  base_jsonify/models/models.py
  base_jsonify/readme/DESCRIPTION.rst
  base_jsonify/tests/test_get_parser.py
Labels: approved, bot is merging ⏳, needs review

#1837 [13.0][MIG] base_technical_user
  base_technical_user/README.rst
  base_technical_user/__init__.py
  base_technical_user/__manifest__.py
  base_technical_user/i18n/ar.po
  base_technical_user/i18n/base_technical_user.pot
  base_technical_user/i18n/de.po
  base_technical_user/i18n/es.po
  base_technical_user/i18n/fr.po
  base_technical_user/i18n/hr.po
  base_technical_user/i18n/it.po
  base_technical_user/i18n/nl_NL.po
  base_technical_user/i18n/pt.po
  base_technical_user/i18n/zh_CN.po
  base_technical_user/models/__init__.py
  base_technical_user/models/models.py
  base_technical_user/models/res_company.py
  base_technical_user/readme/CONTRIBUTORS.rst
  base_technical_user/readme/DESCRIPTION.rst
  base_technical_user/readme/USAGE.rst
  base_technical_user/static/description/icon.png
  base_technical_user/static/description/index.html
  base_technical_user/tests/__init__.py
  base_technical_user/tests/test_sudo_tech.py
  base_technical_user/views/res_company_view.xml
  setup/base_technical_user/odoo/addons/base_technical_user
  setup/base_technical_user/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1845 [REF] sentry: Fix sentry title level
  sentry/README.rst
  sentry/readme/CONFIGURE.rst
Labels: bot is merging ⏳

#1844 [12.0][IMP] base_custom_info: Create a specific view
  base_custom_info/README.rst
  base_custom_info/__manifest__.py
  base_custom_info/demo/custom.info.property.csv
  base_custom_info/migrations/12.0.2.0.0/pre-migration.py
  base_custom_info/models/__init__.py
  base_custom_info/models/custom_info.py
  base_custom_info/models/custom_info_property.py
  base_custom_info/models/custom_info_value.py
  base_custom_info/models/ir_actions_act_window_view.py
  base_custom_info/models/ir_ui_view.py
  base_custom_info/readme/CONTRIBUTORS.rst
  base_custom_info/static/description/index.html
  base_custom_info/static/src/js/custom_info_renderer.js
  base_custom_info/static/src/js/custom_info_view.js
  base_custom_info/static/src/js/relational_fields.js
  base_custom_info/static/src/scss/custom_info.scss
  base_custom_info/static/src/xml/custom_info_item.xml
  base_custom_info/tests/__init__.py
  base_custom_info/tests/test_partner.py
  base_custom_info/tests/test_required.py
  base_custom_info/tests/test_value_conversion.py
  base_custom_info/views/custom_info_property_view.xml
  base_custom_info/views/custom_info_value_view.xml
  base_custom_info/views/res_partner_view.xml
  base_custom_info/views/webclient_templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#1779 [MIG][13.0] base_view_inheritance_extension: Migration to v13.0
  base_view_inheritance_extension/README.rst
  base_view_inheritance_extension/__init__.py
  base_view_inheritance_extension/__manifest__.py
  base_view_inheritance_extension/demo/ir_ui_view.xml
  base_view_inheritance_extension/i18n/base_view_inheritance_extension.pot
  base_view_inheritance_extension/i18n/ca.po
  base_view_inheritance_extension/i18n/de.po
  base_view_inheritance_extension/i18n/es.po
  base_view_inheritance_extension/i18n/hr.po
  base_view_inheritance_extension/i18n/it.po
  base_view_inheritance_extension/i18n/sl.po
  base_view_inheritance_extension/i18n/tr.po
  base_view_inheritance_extension/models/__init__.py
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/readme/CONTRIBUTORS.rst
  base_view_inheritance_extension/readme/DESCRIPTION.rst
  base_view_inheritance_extension/readme/ROADMAP.rst
  base_view_inheritance_extension/readme/USAGE.rst
  base_view_inheritance_extension/static/description/icon.png
  base_view_inheritance_extension/static/description/index.html
  base_view_inheritance_extension/tests/__init__.py
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
  setup/base_view_inheritance_extension/odoo/addons/base_view_inheritance_extension
  setup/base_view_inheritance_extension/setup.py
Labels: bot is merging ⏳

#1341 11.0 auto backup hourly
  auto_backup/README.rst
  auto_backup/__manifest__.py
  auto_backup/data/ir_cron.xml
  auto_backup/models/db_backup.py
  auto_backup/tests/test_db_backup.py
  auto_backup/view/db_backup_view.xml
Labels: approved, merged 🎉, ready to merge

#1719 [FIX] don't use patch_method in tests, this confuses overrides
  auth_session_timeout/tests/test_ir_config_parameter.py
Labels: approved, bot is merging ⏳, ready to merge

#1720 [10.0][FIX] issue 1227. auth_admin_passkey. Error on editing general settings.
  auth_admin_passkey/models/res_config.py
  auth_admin_passkey/tests/__init__.py
  auth_admin_passkey/tests/test_config.py
Labels: approved, bot is merging ⏳, ready to merge

#1764 [13.0][ADD] base_changeset
  base_changeset/README.rst
  base_changeset/__init__.py
  base_changeset/__manifest__.py
  base_changeset/demo/changeset_field_rule.xml
  base_changeset/models/__init__.py
  base_changeset/models/base.py
  base_changeset/models/changeset_field_rule.py
  base_changeset/models/record_changeset.py
  base_changeset/models/record_changeset_change.py
  base_changeset/readme/CONFIGURE.rst
  base_changeset/readme/CONTRIBUTORS.rst
  base_changeset/readme/DESCRIPTION.rst
  base_changeset/readme/ROADMAP.rst
  base_changeset/readme/USAGE.rst
  base_changeset/security/groups.xml
  base_changeset/security/ir.model.access.csv
  base_changeset/security/rules.xml
  base_changeset/static/description/icon.png
  base_changeset/static/src/img/badge.png
  base_changeset/static/src/img/badge_click.png
  base_changeset/static/src/img/changeset.png
  base_changeset/static/src/img/rules.png
  base_changeset/static/src/js/backend.js
  base_changeset/static/src/scss/backend.scss
  base_changeset/static/src/xml/backend.xml
  base_changeset/templates/assets.xml
  base_changeset/tests/__init__.py
  base_changeset/tests/common.py
  base_changeset/tests/test_changeset_field_rule.py
  base_changeset/tests/test_changeset_field_type.py
  base_changeset/tests/test_changeset_flow.py
  base_changeset/tests/test_changeset_origin.py
  base_changeset/views/changeset_field_rule_views.xml
  base_changeset/views/menu.xml
  base_changeset/views/record_changeset_change_views.xml
  base_changeset/views/record_changeset_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#1850 [10.0][IMP] .travis.yml: Update to latest template
  .travis.yml
Labels: bot is merging ⏳

#1849 [10.0][BCK][IMP] add security groups to mass editing action
  mass_editing/models/mass_object.py
  mass_editing/views/mass_editing_view.xml
Labels: bot is merging ⏳

#1854 [FIX] sql_request_abstract: allow XML-RPC calls
  sql_request_abstract/models/sql_request_mixin.py
Labels: bot is merging ⏳
