Repository OCA/server-tools, pull requests merged in 2020-03, with the labels that each got.

#1529 [12.0][MIG] base_view_inheritance_extension: Migration to 12.0
  base_view_inheritance_extension/README.rst
  base_view_inheritance_extension/__init__.py
  base_view_inheritance_extension/__manifest__.py
  base_view_inheritance_extension/demo/ir_ui_view.xml
  base_view_inheritance_extension/i18n/base_view_inheritance_extension.pot
  base_view_inheritance_extension/i18n/ca.po
  base_view_inheritance_extension/i18n/de.po
  base_view_inheritance_extension/i18n/es.po
  base_view_inheritance_extension/i18n/hr.po
  base_view_inheritance_extension/i18n/it.po
  base_view_inheritance_extension/i18n/sl.po
  base_view_inheritance_extension/i18n/tr.po
  base_view_inheritance_extension/models/__init__.py
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/readme/CONTRIBUTORS.rst
  base_view_inheritance_extension/readme/DESCRIPTION.rst
  base_view_inheritance_extension/readme/ROADMAP.rst
  base_view_inheritance_extension/readme/USAGE.rst
  base_view_inheritance_extension/static/description/icon.png
  base_view_inheritance_extension/static/description/index.html
  base_view_inheritance_extension/tests/__init__.py
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
Labels: merged 🎉, needs review

#1701 [10.0][IMP] base_view_inheritance_extension : Add new feature 'target_position'
  base_view_inheritance_extension/README.rst
  base_view_inheritance_extension/__manifest__.py
  base_view_inheritance_extension/demo/ir_ui_view.xml
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
Labels: approved, merged 🎉, needs review, ready to merge

#1792 [10.0][FIX] pin packages to pre-python3 or pre-deprecation
  .travis.yml
Labels: approved

#1796 [IMP] company_country: Fix and improve README and error messages
  company_country/README.rst
  company_country/i18n/company_country.pot
  company_country/models/res_config.py
  company_country/readme/CONFIGURE.rst
  company_country/readme/CREDITS.rst
  company_country/readme/DESCRIPTION.rst
  company_country/readme/INSTALL.rst
  company_country/readme/USAGE.rst
  company_country/static/description/index.html
Labels: bot is merging ⏳
