Repository OCA/server-tools, pull requests merged in 2020-12, with the labels that each got.

#1946 base_view_inheritance_extension: fix pyyaml dependency
  base_view_inheritance_extension/__manifest__.py
Labels: bot is merging ⏳, needs review

#1917 [12.0][WIP][REF] refactor code, rename enabled to active, and simplifie run code
  attachment_synchronize/models/attachment_synchronize_task.py
  attachment_synchronize/tests/test_import.py
  attachment_synchronize/views/attachment_queue_views.xml
  attachment_synchronize/views/attachment_synchronize_task_views.xml
Labels: approved, bot is merging ⏳, needs review

#1262 [FIX] remove ondelete cascade on auditlog_log_line
  auditlog/README.rst
  auditlog/__openerp__.py
  auditlog/migrations/8.0.1.4.0/pre-migration.py
  auditlog/models/http_request.py
  auditlog/models/http_session.py
  auditlog/models/log.py
  auditlog/models/rule.py
  auditlog/tests/test_auditlog.py
  auditlog/views/auditlog_view.xml
Labels: approved, bot is merging ⏳

#1781 [13.0][MIG] dbfilter_from_header
  dbfilter_from_header/README.rst
  dbfilter_from_header/__init__.py
  dbfilter_from_header/__manifest__.py
  dbfilter_from_header/i18n/dbfilter_from_header.pot
  dbfilter_from_header/i18n/zh_CN.po
  dbfilter_from_header/override.py
  dbfilter_from_header/readme/CONFIGURE.rst
  dbfilter_from_header/readme/CONTRIBUTORS.rst
  dbfilter_from_header/readme/DESCRIPTION.rst
  dbfilter_from_header/readme/INSTALL.rst
  dbfilter_from_header/readme/USAGE.rst
  dbfilter_from_header/static/description/icon.png
  dbfilter_from_header/static/description/index.html
Labels: approved, bot is merging ⏳

#1966 [8.0][FIX] base_multi_image: Fix hook
  base_multi_image/hooks.py
Labels: bot is merging ⏳

#1945 [MIG] 14.0 base_technical_user
  base_technical_user/README.rst
  base_technical_user/__init__.py
  base_technical_user/__manifest__.py
  base_technical_user/i18n/ar.po
  base_technical_user/i18n/base_technical_user.pot
  base_technical_user/i18n/de.po
  base_technical_user/i18n/es.po
  base_technical_user/i18n/fr.po
  base_technical_user/i18n/hr.po
  base_technical_user/i18n/it.po
  base_technical_user/i18n/nl_NL.po
  base_technical_user/i18n/pt.po
  base_technical_user/i18n/zh_CN.po
  base_technical_user/models/__init__.py
  base_technical_user/models/models.py
  base_technical_user/models/res_company.py
  base_technical_user/readme/CONTRIBUTORS.rst
  base_technical_user/readme/DESCRIPTION.rst
  base_technical_user/readme/USAGE.rst
  base_technical_user/static/description/icon.png
  base_technical_user/static/description/index.html
  base_technical_user/tests/__init__.py
  base_technical_user/tests/test_sudo_tech.py
  base_technical_user/views/res_company_view.xml
  setup/base_technical_user/odoo/addons/base_technical_user
  setup/base_technical_user/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1967 [12.0][FIX] sql_export: fix warning two fields have same label
  sql_export/demo/sql_export.xml
Labels: bot is merging ⏳

#1964 [IMP] Dont query non-stored related or computed fields on full auditlog
  auditlog/README.rst
  auditlog/models/rule.py
Labels: approved, bot is merging ⏳, ready to merge

#1936 [14.0][MIG] onchange_helper: Migration to 14.0
  onchange_helper/README.rst
  onchange_helper/__init__.py
  onchange_helper/__manifest__.py
  onchange_helper/i18n/cs_CZ.po
  onchange_helper/i18n/de.po
  onchange_helper/i18n/es.po
  onchange_helper/i18n/fr.po
  onchange_helper/i18n/hr.po
  onchange_helper/i18n/onchange_helper.pot
  onchange_helper/i18n/sl.po
  onchange_helper/i18n/zh_CN.po
  onchange_helper/models/__init__.py
  onchange_helper/models/base.py
  onchange_helper/readme/CONTRIBUTORS.rst
  onchange_helper/readme/DESCRIPTION.rst
  onchange_helper/readme/USAGE.rst
  onchange_helper/static/description/icon.png
  onchange_helper/static/description/index.html
  onchange_helper/tests/__init__.py
  onchange_helper/tests/test_onchange_helper.py
  setup/onchange_helper/odoo/addons/onchange_helper
  setup/onchange_helper/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1950 14.0 add base sparse field list support
  base_sparse_field_list_support/__init__.py
  base_sparse_field_list_support/__manifest__.py
  base_sparse_field_list_support/models/__init__.py
  base_sparse_field_list_support/models/fields.py
  base_sparse_field_list_support/readme/CONTRIBUTORS.rst
  base_sparse_field_list_support/readme/DESCRIPTION.rst
  setup/base_sparse_field_list_support/odoo/addons/base_sparse_field_list_support
  setup/base_sparse_field_list_support/setup.py
Labels: approved, bot is merging ⏳
