Repository OCA/server-tools, pull requests merged in 2020-08, with the labels that each got.

#1876 Pin pyotp to last version compatible with py 2.7
  requirements.txt
Labels: approved, bot is merging ⏳

#1875 [10.0][FIX] Update requirements.txt
  requirements.txt
Labels: bot is merging ⏳

#1872 [REF] company_country: Deprecate module
  company_country/README.rst
  company_country/__manifest__.py
  company_country/readme/DESCRIPTION.rst
  company_country/static/description/index.html
Labels: bot is merging ⏳

#1886 [13.0][FIX] base_view_inheritance_extension: add missing params on function apply_inheritance_specs
  base_view_inheritance_extension/models/ir_ui_view.py
Labels: approved, bot is merging ⏳

#1757 [12] Migrate and rename external_file_location.
  .travis.yml
  attachment_synchronize/README.rst
  attachment_synchronize/__init__.py
  attachment_synchronize/__manifest__.py
  attachment_synchronize/data/cron.xml
  attachment_synchronize/demo/attachment_synchronize_task_demo.xml
  attachment_synchronize/models/__init__.py
  attachment_synchronize/models/attachment_queue.py
  attachment_synchronize/models/attachment_synchronize_task.py
  attachment_synchronize/models/storage_backend.py
  attachment_synchronize/readme/CONTRIBUTORS.rst
  attachment_synchronize/readme/DESCRIPTION.rst
  attachment_synchronize/readme/USAGE.rst
  attachment_synchronize/security/ir.model.access.csv
  attachment_synchronize/static/description/export_task.png
  attachment_synchronize/static/description/icon.png
  attachment_synchronize/static/description/import_task.png
  attachment_synchronize/static/description/index.html
  attachment_synchronize/tests/__init__.py
  attachment_synchronize/tests/common.py
  attachment_synchronize/tests/test_export.py
  attachment_synchronize/tests/test_import.py
  attachment_synchronize/views/attachment_queue_views.xml
  attachment_synchronize/views/attachment_synchronize_task_views.xml
  attachment_synchronize/views/storage_backend_views.xml
Labels: approved, merged 🎉

#1831 [WIP][12.0][IMP] add by_method exception
  base_exception/__manifest__.py
  base_exception/models/__init__.py
  base_exception/models/base_exception.py
  base_exception/tests/__init__.py
  base_exception/tests/common.py
  base_exception/tests/purchase_test.py
  base_exception/tests/test_base_exception.py
  base_exception/wizard/__init__.py
  base_exception/wizard/base_exception_confirm.py
Labels: approved, bot is merging ⏳, ready to merge

#1659 [12.0] Add module sql_export_excel
  sql_export/models/sql_export.py
  sql_export/views/sql_export_view.xml
  sql_export/wizard/wizard_file.py
  sql_export_excel/README.rst
  sql_export_excel/__init__.py
  sql_export_excel/__manifest__.py
  sql_export_excel/models/__init__.py
  sql_export_excel/models/sql_export.py
  sql_export_excel/readme/CONFIGURE.rst
  sql_export_excel/readme/CONTRIBUTORS.rst
  sql_export_excel/readme/DESCRIPTION.rst
  sql_export_excel/tests/__init__.py
  sql_export_excel/tests/test_sql_query_excel.py
  sql_export_excel/views/sql_export_view.xml
  sql_request_abstract/models/sql_request_mixin.py
Labels: approved, bot is merging ⏳, ready to merge
