Repository OCA/server-tools, pull requests merged in 2021-12, with the labels that each got.

#2169 [14.0][MIG] base_model_restrict_update
  base_model_restrict_update/README.rst
  base_model_restrict_update/__init__.py
  base_model_restrict_update/__manifest__.py
  base_model_restrict_update/i18n/base_model_restrict_update.po
  base_model_restrict_update/i18n/base_model_restrict_update.pot
  base_model_restrict_update/i18n/ja_JP.po
  base_model_restrict_update/models/__init__.py
  base_model_restrict_update/models/ir_model.py
  base_model_restrict_update/models/ir_model_access.py
  base_model_restrict_update/models/res_users.py
  base_model_restrict_update/readme/CONFIGURE.rst
  base_model_restrict_update/readme/CONTRIBUTORS.rst
  base_model_restrict_update/readme/CREDITS.rst
  base_model_restrict_update/readme/DESCRIPTION.rst
  base_model_restrict_update/static/description/icon.png
  base_model_restrict_update/static/description/index.html
  base_model_restrict_update/tests/__init__.py
  base_model_restrict_update/tests/test_base_model_restrict_update.py
  base_model_restrict_update/views/ir_model_views.xml
  base_model_restrict_update/views/res_users_views.xml
  setup/base_model_restrict_update/odoo/addons/base_model_restrict_update
  setup/base_model_restrict_update/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2181 [14.0][FIX] sentry: enable use of "sentry_odoo_dir" config parameter
  sentry/__init__.py
  sentry/tests/test_client.py
Labels: approved, ready to merge, bot is merging ⏳

#2149 [12.0][IMP] base_fontawesome: Updated fontawesome to 5.15.3
  base_fontawesome/README.rst
  base_fontawesome/__manifest__.py
  base_fontawesome/readme/DESCRIPTION.rst
  base_fontawesome/static/description/index.html
  base_fontawesome/static/lib/fontawesome-5.15.3/css/all.css
  base_fontawesome/static/lib/fontawesome-5.15.3/css/v4-shims.css
  base_fontawesome/static/lib/fontawesome-5.15.3/webfonts/fa-brands-400.eot
  base_fontawesome/static/lib/fontawesome-5.15.3/webfonts/fa-brands-400.svg
  base_fontawesome/static/lib/fontawesome-5.15.3/webfonts/fa-brands-400.ttf
  base_fontawesome/static/lib/fontawesome-5.15.3/webfonts/fa-brands-400.woff
  base_fontawesome/static/lib/fontawesome-5.15.3/webfonts/fa-brands-400.woff2
  base_fontawesome/static/lib/fontawesome-5.15.3/webfonts/fa-regular-400.eot
  base_fontawesome/static/lib/fontawesome-5.15.3/webfonts/fa-regular-400.svg
  base_fontawesome/static/lib/fontawesome-5.15.3/webfonts/fa-regular-400.ttf
  base_fontawesome/static/lib/fontawesome-5.15.3/webfonts/fa-regular-400.woff
  base_fontawesome/static/lib/fontawesome-5.15.3/webfonts/fa-regular-400.woff2
  base_fontawesome/static/lib/fontawesome-5.15.3/webfonts/fa-solid-900.eot
  base_fontawesome/static/lib/fontawesome-5.15.3/webfonts/fa-solid-900.svg
  base_fontawesome/static/lib/fontawesome-5.15.3/webfonts/fa-solid-900.ttf
  base_fontawesome/static/lib/fontawesome-5.15.3/webfonts/fa-solid-900.woff
  base_fontawesome/static/lib/fontawesome-5.15.3/webfonts/fa-solid-900.woff2
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-brands-400.eot
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-brands-400.ttf
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-brands-400.woff
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-brands-400.woff2
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-regular-400.eot
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-regular-400.ttf
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-regular-400.woff
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-regular-400.woff2
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-solid-900.eot
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-solid-900.ttf
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-solid-900.woff
  base_fontawesome/static/lib/fontawesome-5.7.1/webfonts/fa-solid-900.woff2
  base_fontawesome/static/src/css/fontawesome.css
  base_fontawesome/templates/assets.xml
Labels: bot is merging ⏳

#2113 [13.0][MIG] autovacuum_message_attachment: Migration to 13.0
  autovacuum_message_attachment/README.rst
  autovacuum_message_attachment/__init__.py
  autovacuum_message_attachment/__manifest__.py
  autovacuum_message_attachment/data/data.xml
  autovacuum_message_attachment/i18n/autovacuum_mail_message.pot
  autovacuum_message_attachment/i18n/autovacuum_message_attachment.pot
  autovacuum_message_attachment/i18n/fr.po
  autovacuum_message_attachment/models/__init__.py
  autovacuum_message_attachment/models/autovacuum_mixin.py
  autovacuum_message_attachment/models/base.py
  autovacuum_message_attachment/models/ir_attachment.py
  autovacuum_message_attachment/models/mail_message.py
  autovacuum_message_attachment/models/vacuum_rule.py
  autovacuum_message_attachment/readme/CONFIGURE.rst
  autovacuum_message_attachment/readme/CONTRIBUTORS.rst
  autovacuum_message_attachment/readme/DESCRIPTION.rst
  autovacuum_message_attachment/readme/ROADMAP.rst
  autovacuum_message_attachment/security/ir.model.access.csv
  autovacuum_message_attachment/static/description/icon.png
  autovacuum_message_attachment/static/description/index.html
  autovacuum_message_attachment/tests/__init__.py
  autovacuum_message_attachment/tests/test_vacuum_rule.py
  autovacuum_message_attachment/views/rule_vacuum.xml
  setup/autovacuum_message_attachment/odoo/addons/autovacuum_message_attachment
  setup/autovacuum_message_attachment/setup.py
Labels: bot is merging ⏳

#2220 [14.0] base_jsonify: fail gracefully
  base_jsonify/models/models.py
  base_jsonify/tests/test_get_parser.py
Labels: approved, bot is merging ⏳

#2228 [IMP] add base_video_link
  base_video_link/__init__.py
  base_video_link/__manifest__.py
  base_video_link/data/video_provider_data.xml
  base_video_link/demo/video_demo.xml
  base_video_link/models/__init__.py
  base_video_link/models/video_link_mixin.py
  base_video_link/models/video_provider.py
  base_video_link/models/video_video.py
  base_video_link/readme/CONTRIBUTORS.rst
  base_video_link/readme/DESCRIPTION.rst
  base_video_link/readme/ROADMAP.rst
  base_video_link/readme/USAGE.rst
  base_video_link/security/ir.model.access.csv
  base_video_link/views/menu_view.xml
  base_video_link/views/video_provider_view.xml
  base_video_link/views/video_video_view.xml
  setup/base_video_link/odoo/addons/base_video_link
  setup/base_video_link/setup.py
Labels: approved, bot is merging ⏳

#2230 base_video_link: misc fix/imp
  base_video_link/__manifest__.py
  base_video_link/demo/video_demo.xml
  base_video_link/i18n/base_video_link.pot
  base_video_link/models/video_provider.py
  base_video_link/models/video_video.py
  base_video_link/readme/CONTRIBUTORS.rst
  base_video_link/views/video_video_view.xml
Labels: approved, bot is merging ⏳

#2233 [FIX] fix compute url and add test
  base_video_link/data/video_provider_data.xml
  base_video_link/models/video_video.py
  base_video_link/tests/__init__.py
  base_video_link/tests/test_url.py
Labels: approved, bot is merging ⏳

#2126 [12.0] module_analysis fix _get_files_to_analyse
  module_analysis/models/ir_module_module.py
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#2225 [15.0][MIG] base_cron_exclusion
  base_cron_exclusion/README.rst
  base_cron_exclusion/__init__.py
  base_cron_exclusion/__manifest__.py
  base_cron_exclusion/i18n/base_cron_exclusion.pot
  base_cron_exclusion/i18n/cs_CZ.po
  base_cron_exclusion/i18n/es.po
  base_cron_exclusion/i18n/fr.po
  base_cron_exclusion/i18n/zh_CN.po
  base_cron_exclusion/models/__init__.py
  base_cron_exclusion/models/ir_cron.py
  base_cron_exclusion/readme/CONTRIBUTORS.rst
  base_cron_exclusion/readme/DESCRIPTION.rst
  base_cron_exclusion/readme/USAGE.rst
  base_cron_exclusion/static/description/icon.png
  base_cron_exclusion/static/description/index.html
  base_cron_exclusion/views/ir_cron_view.xml
  setup/base_cron_exclusion/odoo/addons/base_cron_exclusion
  setup/base_cron_exclusion/setup.py
Labels: approved, bot is merging ⏳

#2243 [FIX] module_change_auto_install : auto_install is now a set of dependencies. (before, was boolean)
  module_change_auto_install/patch.py
Labels: bot is merging ⏳

#2214 [15.0] [MIG] fetchmail incoming log: Migration to 15.0
  fetchmail_incoming_log/README.rst
  fetchmail_incoming_log/__init__.py
  fetchmail_incoming_log/__manifest__.py
  fetchmail_incoming_log/i18n/ca.po
  fetchmail_incoming_log/i18n/de.po
  fetchmail_incoming_log/i18n/es.po
  fetchmail_incoming_log/i18n/fetchmail_incoming_log.pot
  fetchmail_incoming_log/i18n/fr.po
  fetchmail_incoming_log/i18n/it.po
  fetchmail_incoming_log/i18n/pt_BR.po
  fetchmail_incoming_log/i18n/pt_PT.po
  fetchmail_incoming_log/i18n/sl.po
  fetchmail_incoming_log/i18n/tr.po
  fetchmail_incoming_log/models/__init__.py
  fetchmail_incoming_log/models/mail_thread.py
  fetchmail_incoming_log/readme/CONTRIBUTORS.rst
  fetchmail_incoming_log/readme/DESCRIPTION.rst
  fetchmail_incoming_log/static/description/icon.png
  fetchmail_incoming_log/static/description/index.html
  fetchmail_incoming_log/tests/__init__.py
  fetchmail_incoming_log/tests/test_fetchmail_incoming_log.py
  setup/fetchmail_incoming_log/odoo/addons/fetchmail_incoming_log
  setup/fetchmail_incoming_log/setup.py
Labels: needs review, approved, bot is merging ⏳

#2250 [FIX][13.0] module_analysis: correct syntax
  module_analysis/models/ir_module_module.py
Labels: approved, bot is merging ⏳
