Repository OCA/server-tools, pull requests merged in 2021-03, with the labels that each got.

#2034 [14.0][MIG] slow_statement_logger
  setup/slow_statement_logger/odoo/addons/slow_statement_logger
  setup/slow_statement_logger/setup.py
  slow_statement_logger/README.rst
  slow_statement_logger/__init__.py
  slow_statement_logger/__manifest__.py
  slow_statement_logger/i18n/slow_statement_logger.pot
  slow_statement_logger/readme/CONTRIBUTORS.rst
  slow_statement_logger/readme/DESCRIPTION.rst
  slow_statement_logger/readme/USAGE.rst
  slow_statement_logger/static/description/icon.png
  slow_statement_logger/static/description/index.html
Labels: approved, bot is merging ⏳

#2029 [13.0][MIG] datetime_formatter: Migration to 13.0
  datetime_formatter/README.rst
  datetime_formatter/__init__.py
  datetime_formatter/__manifest__.py
  datetime_formatter/i18n/ar.po
  datetime_formatter/i18n/ca.po
  datetime_formatter/i18n/datetime_formatter.pot
  datetime_formatter/i18n/de.po
  datetime_formatter/i18n/es.po
  datetime_formatter/i18n/fr.po
  datetime_formatter/i18n/hr.po
  datetime_formatter/i18n/it.po
  datetime_formatter/i18n/nl_NL.po
  datetime_formatter/i18n/pt.po
  datetime_formatter/i18n/sl.po
  datetime_formatter/i18n/tr.po
  datetime_formatter/i18n/zh_CN.po
  datetime_formatter/models/__init__.py
  datetime_formatter/models/res_lang.py
  datetime_formatter/readme/CONTRIBUTORS.rst
  datetime_formatter/readme/DESCRIPTION.rst
  datetime_formatter/readme/USAGE.rst
  datetime_formatter/static/description/icon.png
  datetime_formatter/static/description/index.html
  datetime_formatter/tests/__init__.py
  datetime_formatter/tests/test_best_matcher.py
  datetime_formatter/tests/test_formatter.py
  setup/datetime_formatter/odoo/addons/datetime_formatter
  setup/datetime_formatter/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#2031 [PORT] 14.0 forward port PR 2012
  base_jsonify/models/ir_exports_line.py
  base_jsonify/models/models.py
Labels: approved, bot is merging ⏳

#2033 [13.0][MIG] slow_statement_logger
  setup/slow_statement_logger/odoo/addons/slow_statement_logger
  setup/slow_statement_logger/setup.py
  slow_statement_logger/README.rst
  slow_statement_logger/__init__.py
  slow_statement_logger/__manifest__.py
  slow_statement_logger/i18n/slow_statement_logger.pot
  slow_statement_logger/readme/CONTRIBUTORS.rst
  slow_statement_logger/readme/DESCRIPTION.rst
  slow_statement_logger/readme/USAGE.rst
  slow_statement_logger/static/description/icon.png
  slow_statement_logger/static/description/index.html
Labels: approved, bot is merging ⏳, ready to merge

#1971 [10.0][FIX] Dont query non-stored related or computed fields on full auditlog
  auditlog/README.rst
  auditlog/models/rule.py
Labels: approved, bot is merging ⏳

#2036 [12.0] Replaced Pygount source analysis deprecation method
  module_analysis/models/ir_module_module.py
Labels: approved, bot is merging ⏳

#2038 [12.0][FIX] Update pygount version info in README INSTALL.rst and requirements.txt
  module_analysis/models/ir_module_module.py
  module_analysis/readme/INSTALL.rst
  requirements.txt
Labels: bot is merging ⏳

#2005 [11.0][ADD] profiler icon
  profiler/static/description/icon.png
Labels: approved, bot is merging ⏳, ready to merge

#1962 11.0 auth ldap groups
  users_ldap_groups/README.rst
  users_ldap_groups/__init__.py
  users_ldap_groups/__manifest__.py
  users_ldap_groups/i18n/de.po
  users_ldap_groups/i18n/es.po
  users_ldap_groups/i18n/fr.po
  users_ldap_groups/i18n/pt_BR.po
  users_ldap_groups/i18n/sl.po
  users_ldap_groups/i18n/users_ldap_groups.pot
  users_ldap_groups/models/__init__.py
  users_ldap_groups/models/res_company_ldap.py
  users_ldap_groups/models/res_company_ldap_group_mapping.py
  users_ldap_groups/models/res_company_ldap_operator.py
  users_ldap_groups/models/res_users.py
  users_ldap_groups/readme/CONTRIBUTORS.rst
  users_ldap_groups/readme/DESCRIPTION.rst
  users_ldap_groups/readme/USAGE.rst
  users_ldap_groups/security/ir.model.access.csv
  users_ldap_groups/static/description/icon.png
  users_ldap_groups/tests/__init__.py
  users_ldap_groups/tests/test_users_ldap_groups.py
  users_ldap_groups/views/base_config_settings.xml
Labels: approved, bot is merging ⏳, ready to merge

#2042 [13.0][fix][base_exception] search only active exception rules
  base_exception/models/base_exception.py
Labels: approved, bot is merging ⏳, ready to merge

#2053 [14.0][UPD] openupgrade_records: forward-port from v13
  upgrade_analysis/compare.py
  upgrade_analysis/models/upgrade_record.py
  upgrade_analysis/upgrade_log.py
Labels: approved, bot is merging ⏳

#2052 [14.0][IMP] upgrade_analysis: make us of odoorpc/openupgradelib master
  test-requirements.txt
  upgrade_analysis/blacklist.py
  upgrade_analysis/compare.py
  upgrade_analysis/models/upgrade_analysis.py
  upgrade_analysis/odoo_patch/odoo_patch.py
  upgrade_analysis/wizards/upgrade_install_wizard.py
Labels: approved, bot is merging ⏳

#2009 [FIX] fix access right
  base_exception/models/base_exception.py
Labels: approved, bot is merging ⏳

#2048 [IMP] base_custom_info enable to easily import custom info values
  base_custom_info/models/custom_info_value.py
Labels: bot is merging ⏳

#2057 [14.0][FIX] upgrade_analysis: fix methods related to noupdate data
  upgrade_analysis/__manifest__.py
  upgrade_analysis/models/upgrade_analysis.py
  upgrade_analysis/models/upgrade_record.py
  upgrade_analysis/readme/CONTRIBUTORS.rst
  upgrade_analysis/static/description/index.html
  upgrade_analysis/wizards/upgrade_generate_record_wizard.py
Labels: approved, bot is merging ⏳
