Repository OCA/server-tools, pull requests merged in 2021-08, with the labels that each got.

#2152 [14.0][FIX] base_exception, error if rule's description is null
  base_exception/models/base_exception.py
Labels: approved, ready to merge, bot is merging ⏳

#2120 [14.0] [mig] base_remote
  base_remote/README.rst
  base_remote/__init__.py
  base_remote/__manifest__.py
  base_remote/i18n/base_remote.pot
  base_remote/i18n/es.po
  base_remote/models/__init__.py
  base_remote/models/base.py
  base_remote/models/res_remote.py
  base_remote/models/res_users.py
  base_remote/readme/CONTRIBUTORS.rst
  base_remote/readme/DESCRIPTION.rst
  base_remote/readme/USAGE.rst
  base_remote/security/ir.model.access.csv
  base_remote/static/description/icon.png
  base_remote/static/description/index.html
  base_remote/tests/__init__.py
  base_remote/tests/test_remote.py
  base_remote/views/res_remote_views.xml
  setup/base_remote/odoo/addons/base_remote
  setup/base_remote/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2119 [14.0][mig]base_kanban_stage_state
  base_kanban_stage_state/README.rst
  base_kanban_stage_state/__init__.py
  base_kanban_stage_state/__manifest__.py
  base_kanban_stage_state/i18n/base_kanban_stage_state.pot
  base_kanban_stage_state/i18n/ca.po
  base_kanban_stage_state/i18n/cs.po
  base_kanban_stage_state/i18n/da.po
  base_kanban_stage_state/i18n/de.po
  base_kanban_stage_state/i18n/es.po
  base_kanban_stage_state/i18n/es_ES.po
  base_kanban_stage_state/i18n/es_MX.po
  base_kanban_stage_state/i18n/es_VE.po
  base_kanban_stage_state/i18n/fi.po
  base_kanban_stage_state/i18n/fr.po
  base_kanban_stage_state/i18n/fr_CH.po
  base_kanban_stage_state/i18n/gl.po
  base_kanban_stage_state/i18n/hr.po
  base_kanban_stage_state/i18n/hr_HR.po
  base_kanban_stage_state/i18n/hu.po
  base_kanban_stage_state/i18n/it.po
  base_kanban_stage_state/i18n/nb.po
  base_kanban_stage_state/i18n/nb_NO.po
  base_kanban_stage_state/i18n/nl.po
  base_kanban_stage_state/i18n/pl.po
  base_kanban_stage_state/i18n/pt.po
  base_kanban_stage_state/i18n/pt_BR.po
  base_kanban_stage_state/i18n/pt_PT.po
  base_kanban_stage_state/i18n/ro.po
  base_kanban_stage_state/i18n/sl.po
  base_kanban_stage_state/i18n/sv.po
  base_kanban_stage_state/i18n/tr.po
  base_kanban_stage_state/i18n/tr_TR.po
  base_kanban_stage_state/i18n/zh_CN.po
  base_kanban_stage_state/models/__init__.py
  base_kanban_stage_state/models/base_kanban_stage.py
  base_kanban_stage_state/readme/CONTRIBUTORS.rst
  base_kanban_stage_state/readme/DESCRIPTION.rst
  base_kanban_stage_state/static/description/icon.png
  base_kanban_stage_state/static/description/index.html
  base_kanban_stage_state/tests/__init__.py
  base_kanban_stage_state/tests/test_base_kanban_stage.py
  base_kanban_stage_state/views/base_kanban_stage_state_view.xml
  setup/base_kanban_stage_state/odoo/addons/base_kanban_stage_state
  setup/base_kanban_stage_state/setup.py
Labels: approved, bot is merging ⏳

#1888 [11.0] base_exception improvements
  base_exception/models/base_exception.py
Labels: needs review, bot is merging ⏳

#2162 [14.0][IMP] auditlog, add auditlog.log.line view
  auditlog/models/log.py
  auditlog/readme/CONTRIBUTORS.rst
  auditlog/views/auditlog_view.xml
  auditlog/views/http_request_view.xml
  auditlog/views/http_session_view.xml
Labels: approved, ready to merge, bot is merging ⏳
