Repository OCA/server-tools, pull requests merged in 2021-01, with the labels that each got.

#1972 [11.0][FIX] Dont query non-stored related or computed fields on full auditlog
  auditlog/README.rst
  auditlog/models/rule.py
Labels: approved, bot is merging ⏳, ready to merge

#1974 [13.0][FIX] Dont query non-stored related or computed fields on full auditlog
  auditlog/README.rst
  auditlog/models/rule.py
Labels: approved, bot is merging ⏳, ready to merge

#1973 [12.0][FIX] Dont query non-stored related or computed fields on full auditlog
  auditlog/README.rst
  auditlog/models/rule.py
Labels: approved, bot is merging ⏳, ready to merge

#1901 [12.0][MIG] mail_cleanup
  mail_cleanup/README.rst
  mail_cleanup/__init__.py
  mail_cleanup/__manifest__.py
  mail_cleanup/i18n/ca.po
  mail_cleanup/i18n/de.po
  mail_cleanup/i18n/es.po
  mail_cleanup/i18n/fr.po
  mail_cleanup/i18n/hr.po
  mail_cleanup/i18n/it.po
  mail_cleanup/i18n/mail_cleanup.pot
  mail_cleanup/i18n/pt_BR.po
  mail_cleanup/i18n/sl.po
  mail_cleanup/i18n/tr.po
  mail_cleanup/i18n/zh_CN.po
  mail_cleanup/models/__init__.py
  mail_cleanup/models/fetchmail_server.py
  mail_cleanup/readme/CONFIGURE.rst
  mail_cleanup/readme/CONTRIBUTORS.rst
  mail_cleanup/readme/DESCRIPTION.rst
  mail_cleanup/static/description/index.html
  mail_cleanup/views/mail_view.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳

#1985 [12.0][FIX] auditlog: Add sudo() to retrieve record vals
  auditlog/models/rule.py
Labels: approved, bot is merging ⏳

#1995 [13.0][FIX] Add sudo() to retrieve record vals
  auditlog/models/rule.py
Labels: approved, bot is merging ⏳

#1894 [IMP] base_jsonify: add lang, custom resolvers, alias* support
  base_jsonify/README.rst
  base_jsonify/__manifest__.py
  base_jsonify/demo/resolver_demo.xml
  base_jsonify/i18n/base_jsonify.pot
  base_jsonify/i18n/zh_CN.po
  base_jsonify/migrations/13.0.2.0.0/pre-migrate.py
  base_jsonify/models/__init__.py
  base_jsonify/models/ir_export.py
  base_jsonify/models/ir_exports_line.py
  base_jsonify/models/ir_exports_resolver.py
  base_jsonify/models/models.py
  base_jsonify/models/utils.py
  base_jsonify/readme/CONTRIBUTORS.rst
  base_jsonify/readme/DESCRIPTION.rst
  base_jsonify/security/ir.model.access.csv
  base_jsonify/static/description/index.html
  base_jsonify/tests/test_get_parser.py
  base_jsonify/tests/test_ir_exports_line.py
  base_jsonify/views/ir_exports_resolver_view.xml
  base_jsonify/views/ir_exports_view.xml
Labels: approved, bot is merging ⏳

#1911 [14.0] [MIG] base_jsonify module
  base_jsonify/README.rst
  base_jsonify/__init__.py
  base_jsonify/__manifest__.py
  base_jsonify/demo/export_demo.xml
  base_jsonify/demo/ir.exports.line.csv
  base_jsonify/demo/resolver_demo.xml
  base_jsonify/i18n/base_jsonify.pot
  base_jsonify/i18n/zh_CN.po
  base_jsonify/models/__init__.py
  base_jsonify/models/ir_export.py
  base_jsonify/models/ir_exports_line.py
  base_jsonify/models/ir_exports_resolver.py
  base_jsonify/models/models.py
  base_jsonify/models/utils.py
  base_jsonify/readme/CONTRIBUTORS.rst
  base_jsonify/readme/DESCRIPTION.rst
  base_jsonify/security/ir.model.access.csv
  base_jsonify/static/description/icon.png
  base_jsonify/static/description/index.html
  base_jsonify/tests/__init__.py
  base_jsonify/tests/test_get_parser.py
  base_jsonify/tests/test_ir_exports_line.py
  base_jsonify/views/ir_exports_resolver_view.xml
  base_jsonify/views/ir_exports_view.xml
  setup/base_jsonify/odoo/addons/base_jsonify
  setup/base_jsonify/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1975 [14.0][FIX] Dont query non-stored related or computed fields on full auditlog
  auditlog/README.rst
  auditlog/models/rule.py
Labels: approved, bot is merging ⏳, ready to merge

#1623 [IMP] auto_backup: Count files instead of looking at dates
  auto_backup/models/db_backup.py
  auto_backup/tests/test_auto_backup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1986 [11.0][IMP] profiler: 'Per HTTP request' mode
  profiler/README.rst
  profiler/__manifest__.py
  profiler/models/__init__.py
  profiler/models/ir_http.py
  profiler/models/profiler_profile.py
  profiler/security/ir.model.access.csv
  profiler/static/src/js/tour.js
  profiler/tests/__init__.py
  profiler/tests/test_profiling.py
  profiler/tests/test_profiling_ui.py
  profiler/views/assets.xml
  profiler/views/profiler_profile_view.xml
Labels: approved, bot is merging ⏳, ready to merge
