Repository OCA/server-tools, pull requests merged in 2021-06, with the labels that each got.

#2061 [IMP] sql_export : add preview button
  sql_export/views/sql_export_view.xml
  sql_request_abstract/models/sql_request_mixin.py
Labels: approved, bot is merging ⏳, ready to merge

#1988 [MIG] base_time_window: Migration to 14.0
  base_time_window/README.rst
  base_time_window/__init__.py
  base_time_window/__manifest__.py
  base_time_window/data/time_weekday.xml
  base_time_window/i18n/base_time_window.pot
  base_time_window/models/__init__.py
  base_time_window/models/time_weekday.py
  base_time_window/models/time_window_mixin.py
  base_time_window/readme/CONTRIBUTORS.rst
  base_time_window/readme/CREDITS.rst
  base_time_window/readme/DESCRIPTION.rst
  base_time_window/readme/ROADMAP.rst
  base_time_window/readme/USAGE.rst
  base_time_window/security/ir.model.access.xml
  base_time_window/static/description/icon.png
  base_time_window/static/description/index.html
  setup/base_time_window/odoo/addons/base_time_window
  setup/base_time_window/setup.py
Labels: approved, bot is merging ⏳

#2112 [ADD]Auditlog Unlink Record
  auditlog/models/rule.py
  auditlog/readme/CONTRIBUTORS.rst
  auditlog/tests/test_auditlog.py
  auditlog/views/auditlog_view.xml
Labels: approved, bot is merging ⏳

#2102 [14.0][mig] fetchmail_notify_error_to_sender : deprecated field remove
  fetchmail_notify_error_to_sender/README.rst
  fetchmail_notify_error_to_sender/__init__.py
  fetchmail_notify_error_to_sender/__manifest__.py
  fetchmail_notify_error_to_sender/data/email_template_data.xml
  fetchmail_notify_error_to_sender/i18n/ca.po
  fetchmail_notify_error_to_sender/i18n/de.po
  fetchmail_notify_error_to_sender/i18n/es.po
  fetchmail_notify_error_to_sender/i18n/fetchmail_notify_error_to_sender.pot
  fetchmail_notify_error_to_sender/i18n/fr.po
  fetchmail_notify_error_to_sender/i18n/hr.po
  fetchmail_notify_error_to_sender/i18n/it.po
  fetchmail_notify_error_to_sender/i18n/pt_BR.po
  fetchmail_notify_error_to_sender/i18n/pt_PT.po
  fetchmail_notify_error_to_sender/i18n/sl.po
  fetchmail_notify_error_to_sender/i18n/tr.po
  fetchmail_notify_error_to_sender/i18n/zh_CN.po
  fetchmail_notify_error_to_sender/models/__init__.py
  fetchmail_notify_error_to_sender/models/fetchmail.py
  fetchmail_notify_error_to_sender/models/mail_thread.py
  fetchmail_notify_error_to_sender/readme/CONFIGURE.rst
  fetchmail_notify_error_to_sender/readme/CONTRIBUTORS.rst
  fetchmail_notify_error_to_sender/readme/DESCRIPTION.rst
  fetchmail_notify_error_to_sender/static/description/icon.png
  fetchmail_notify_error_to_sender/static/description/index.html
  fetchmail_notify_error_to_sender/views/fetchmail_view.xml
  setup/fetchmail_notify_error_to_sender/odoo/addons/fetchmail_notify_error_to_sender
  setup/fetchmail_notify_error_to_sender/setup.py
Labels: approved, bot is merging ⏳

#2116 [14.0][ENH] auditlog: track unlink record
  auditlog/models/rule.py
  auditlog/readme/CONTRIBUTORS.rst
  auditlog/tests/test_auditlog.py
  auditlog/views/auditlog_view.xml
Labels: approved, bot is merging ⏳

#2114 [13.0][ENH] auditlog: track unlink record
  auditlog/models/rule.py
  auditlog/readme/CONTRIBUTORS.rst
  auditlog/tests/test_auditlog.py
  auditlog/views/auditlog_view.xml
Labels: approved, bot is merging ⏳

#1942 [12.0] [IMP] sentry: migrate sentry-raven to new api sentry-sdk
  requirements.txt
  sentry/README.rst
  sentry/__init__.py
  sentry/__manifest__.py
  sentry/const.py
  sentry/generalutils.py
  sentry/hooks.py
  sentry/logutils.py
  sentry/processor.py
  sentry/readme/CONFIGURE.rst
  sentry/readme/CONTRIBUTORS.rst
  sentry/readme/CREDITS.rst
  sentry/readme/DESCRIPTION.rst
  sentry/readme/INSTALL.rst
  sentry/readme/ROADMAP.rst
  sentry/readme/USAGE.rst
  sentry/static/description/index.html
  sentry/tests/test_client.py
  sentry/tests/test_logutils.py
Labels: bot is merging ⏳, enhancement, needs review
