Repository OCA/server-tools, pull requests merged in 2021-09, with the labels that each got.

#2130 [14.0] [mig] base_changeset
  base_changeset/README.rst
  base_changeset/__init__.py
  base_changeset/__manifest__.py
  base_changeset/demo/changeset_field_rule.xml
  base_changeset/i18n/base_changeset.pot
  base_changeset/i18n/es.po
  base_changeset/models/__init__.py
  base_changeset/models/base.py
  base_changeset/models/changeset_field_rule.py
  base_changeset/models/record_changeset.py
  base_changeset/models/record_changeset_change.py
  base_changeset/readme/CONFIGURE.rst
  base_changeset/readme/CONTRIBUTORS.rst
  base_changeset/readme/DESCRIPTION.rst
  base_changeset/readme/ROADMAP.rst
  base_changeset/readme/USAGE.rst
  base_changeset/security/groups.xml
  base_changeset/security/ir.model.access.csv
  base_changeset/security/rules.xml
  base_changeset/static/description/icon.png
  base_changeset/static/description/index.html
  base_changeset/static/src/img/badge.png
  base_changeset/static/src/img/badge_click.png
  base_changeset/static/src/img/changeset.png
  base_changeset/static/src/img/rules.png
  base_changeset/static/src/js/backend.js
  base_changeset/static/src/scss/backend.scss
  base_changeset/static/src/xml/backend.xml
  base_changeset/templates/assets.xml
  base_changeset/tests/__init__.py
  base_changeset/tests/common.py
  base_changeset/tests/test_changeset_field_rule.py
  base_changeset/tests/test_changeset_field_type.py
  base_changeset/tests/test_changeset_flow.py
  base_changeset/tests/test_changeset_origin.py
  base_changeset/views/changeset_field_rule_views.xml
  base_changeset/views/menu.xml
  base_changeset/views/record_changeset_change_views.xml
  base_changeset/views/record_changeset_views.xml
  setup/base_changeset/odoo/addons/base_changeset
  setup/base_changeset/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2168 [12.0][FIX] base_search_fuzzy: delete unused imports
  base_search_fuzzy/tests/test_query_generation.py
Labels: bot is merging ⏳

#2136 [14.0] mig scheduler_error_mailer
  scheduler_error_mailer/README.rst
  scheduler_error_mailer/__init__.py
  scheduler_error_mailer/__manifest__.py
  scheduler_error_mailer/data/ir_cron_email_tpl.xml
  scheduler_error_mailer/demo/ir_cron_demo.xml
  scheduler_error_mailer/i18n/de.po
  scheduler_error_mailer/i18n/es.po
  scheduler_error_mailer/i18n/hr.po
  scheduler_error_mailer/i18n/pt.po
  scheduler_error_mailer/i18n/pt_BR.po
  scheduler_error_mailer/i18n/scheduler_error_mailer.pot
  scheduler_error_mailer/i18n/sl.po
  scheduler_error_mailer/i18n/zh_CN.po
  scheduler_error_mailer/images/scheduler_error_mailer.jpg
  scheduler_error_mailer/models/__init__.py
  scheduler_error_mailer/models/ir_cron.py
  scheduler_error_mailer/readme/CONFIGURE.rst
  scheduler_error_mailer/readme/CONTRIBUTORS.rst
  scheduler_error_mailer/readme/DESCRIPTION.rst
  scheduler_error_mailer/static/description/icon.png
  scheduler_error_mailer/static/description/index.html
  scheduler_error_mailer/tests/__init__.py
  scheduler_error_mailer/tests/test_scheduler_error_mailer.py
  scheduler_error_mailer/views/ir_cron.xml
Labels: approved, ready to merge, bot is merging ⏳

#2175 [13.0][FIX] base_time_window: Disallow hours > 23
  base_time_window/models/time_window_mixin.py
  test_base_time_window/tests/test_base_time_window.py
Labels: approved, bot is merging ⏳

#2171 [8.0] pin unidecode==1.2.0
  requirements.txt
Labels: approved

#2177 [14.0] Updated from template
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/stale.yml
  .pre-commit-config.yaml
  .travis.yml
  README.md
Labels: approved
