Repository OCA/server-tools, pull requests merged in 2021-05, with the labels that each got.

#2075 [FIX] onchange_helper: compute related values for onchange applications
  onchange_helper/models/base.py
Labels: bot is merging ⏳

#2077 [12.0] Add module base_import_module_group
  base_import_module_group/README.rst
  base_import_module_group/__init__.py
  base_import_module_group/__manifest__.py
  base_import_module_group/models/__init__.py
  base_import_module_group/models/ir_module.py
  base_import_module_group/readme/CONTRIBUTORS.rst
  base_import_module_group/readme/DESCRIPTION.rst
  base_import_module_group/security/res_groups.xml
  base_import_module_group/views/import_module_group.xml
Labels: approved, bot is merging ⏳

#2087 [14.0][FIX] auditlog: invalid XML
  auditlog/views/auditlog_view.xml
Labels: approved, bot is merging ⏳

#1836 [MIG] base_fontawesome: Migration to 13.0
  base_fontawesome/README.rst
  base_fontawesome/__init__.py
  base_fontawesome/__manifest__.py
  base_fontawesome/i18n/base_fontawesome.pot
  base_fontawesome/i18n/es_ES.po
  base_fontawesome/i18n/zh_CN.po
  base_fontawesome/readme/CONTRIBUTORS.rst
  base_fontawesome/readme/DESCRIPTION.rst
  base_fontawesome/readme/USAGE.rst
  base_fontawesome/static/description/icon.png
  base_fontawesome/static/description/index.html
  base_fontawesome/static/lib/fontawesome-5.13.0/css/all.css
  base_fontawesome/static/lib/fontawesome-5.13.0/css/v4-shims.css
  base_fontawesome/static/lib/fontawesome-5.13.0/webfonts/fa-brands-400.eot
  base_fontawesome/static/lib/fontawesome-5.13.0/webfonts/fa-brands-400.svg
  base_fontawesome/static/lib/fontawesome-5.13.0/webfonts/fa-brands-400.ttf
  base_fontawesome/static/lib/fontawesome-5.13.0/webfonts/fa-brands-400.woff
  base_fontawesome/static/lib/fontawesome-5.13.0/webfonts/fa-brands-400.woff2
  base_fontawesome/static/lib/fontawesome-5.13.0/webfonts/fa-regular-400.eot
  base_fontawesome/static/lib/fontawesome-5.13.0/webfonts/fa-regular-400.svg
  base_fontawesome/static/lib/fontawesome-5.13.0/webfonts/fa-regular-400.ttf
  base_fontawesome/static/lib/fontawesome-5.13.0/webfonts/fa-regular-400.woff
  base_fontawesome/static/lib/fontawesome-5.13.0/webfonts/fa-regular-400.woff2
  base_fontawesome/static/lib/fontawesome-5.13.0/webfonts/fa-solid-900.eot
  base_fontawesome/static/lib/fontawesome-5.13.0/webfonts/fa-solid-900.svg
  base_fontawesome/static/lib/fontawesome-5.13.0/webfonts/fa-solid-900.ttf
  base_fontawesome/static/lib/fontawesome-5.13.0/webfonts/fa-solid-900.woff
  base_fontawesome/static/lib/fontawesome-5.13.0/webfonts/fa-solid-900.woff2
  base_fontawesome/static/src/css/fontawesome.css
  base_fontawesome/static/src/js/form_renderer.js
  base_fontawesome/static/src/js/list_renderer.js
  base_fontawesome/templates/assets.xml
  setup/base_fontawesome/odoo/addons/base_fontawesome
  setup/base_fontawesome/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1812 [9.0][IMP] auth_from_http_remote_user: allow multiple sessions for same user
  auth_from_http_remote_user/README.rst
  auth_from_http_remote_user/controllers/main.py
  auth_from_http_remote_user/models/res_users.py
Labels: approved

#1868 [13.0][MIG] base_remote
  base_remote/README.rst
  base_remote/__init__.py
  base_remote/__manifest__.py
  base_remote/i18n/base_remote.pot
  base_remote/i18n/es.po
  base_remote/models/__init__.py
  base_remote/models/base.py
  base_remote/models/res_remote.py
  base_remote/models/res_users.py
  base_remote/readme/CONTRIBUTORS.rst
  base_remote/readme/DESCRIPTION.rst
  base_remote/readme/USAGE.rst
  base_remote/security/ir.model.access.csv
  base_remote/static/description/icon.png
  base_remote/static/description/index.html
  base_remote/tests/__init__.py
  base_remote/tests/test_remote.py
  base_remote/views/res_remote_views.xml
  setup/base_remote/odoo/addons/base_remote
  setup/base_remote/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1937 [MIG][14.0] base_view_inheritance_extension
  base_view_inheritance_extension/README.rst
  base_view_inheritance_extension/__init__.py
  base_view_inheritance_extension/__manifest__.py
  base_view_inheritance_extension/demo/ir_ui_view.xml
  base_view_inheritance_extension/i18n/base_view_inheritance_extension.pot
  base_view_inheritance_extension/i18n/ca.po
  base_view_inheritance_extension/i18n/de.po
  base_view_inheritance_extension/i18n/es.po
  base_view_inheritance_extension/i18n/hr.po
  base_view_inheritance_extension/i18n/it.po
  base_view_inheritance_extension/i18n/sl.po
  base_view_inheritance_extension/i18n/tr.po
  base_view_inheritance_extension/models/__init__.py
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/readme/CONTRIBUTORS.rst
  base_view_inheritance_extension/readme/DESCRIPTION.rst
  base_view_inheritance_extension/readme/ROADMAP.rst
  base_view_inheritance_extension/readme/USAGE.rst
  base_view_inheritance_extension/static/description/icon.png
  base_view_inheritance_extension/static/description/index.html
  base_view_inheritance_extension/tests/__init__.py
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
  requirements.txt
  setup/base_view_inheritance_extension/odoo/addons/base_view_inheritance_extension
  setup/base_view_inheritance_extension/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#2091 [ADD] new module module_change_auto_install to configure auto installable modules by configuration
  module_change_auto_install/README.rst
  module_change_auto_install/__init__.py
  module_change_auto_install/__manifest__.py
  module_change_auto_install/patch.py
  module_change_auto_install/readme/CONFIGURE.rst
  module_change_auto_install/readme/CONTRIBUTORS.rst
  module_change_auto_install/readme/DESCRIPTION.rst
  module_change_auto_install/readme/DEVELOP.rst
  module_change_auto_install/readme/INSTALL.rst
  setup/module_change_auto_install/odoo/addons/module_change_auto_install
  setup/module_change_auto_install/setup.py
Labels: approved, bot is merging ⏳

#2082 [FIX] sentry: Warning when using classes from collections.abc
  sentry/__init__.py
Labels: bot is merging ⏳

#2093 [FIX] module_change_auto_install: Split string sep by comma
  module_change_auto_install/patch.py
Labels: bot is merging ⏳

#2094 [14.0][FIX] base_report_auto_create_qweb, conflict test report name
  base_report_auto_create_qweb/tests/test_base_report_auto_create_qweb.py
Labels: approved, bot is merging ⏳
