Repository OCA/server-tools, pull requests merged in 2021-11, with the labels that each got.

#2167 [MIG][12.0] backport base_changeset
  base_changeset/README.rst
  base_changeset/__init__.py
  base_changeset/__manifest__.py
  base_changeset/demo/changeset_field_rule.xml
  base_changeset/i18n/base_changeset.pot
  base_changeset/i18n/es.po
  base_changeset/models/__init__.py
  base_changeset/models/base.py
  base_changeset/models/changeset_field_rule.py
  base_changeset/models/record_changeset.py
  base_changeset/models/record_changeset_change.py
  base_changeset/readme/CONFIGURE.rst
  base_changeset/readme/CONTRIBUTORS.rst
  base_changeset/readme/DESCRIPTION.rst
  base_changeset/readme/ROADMAP.rst
  base_changeset/readme/USAGE.rst
  base_changeset/security/groups.xml
  base_changeset/security/ir.model.access.csv
  base_changeset/security/rules.xml
  base_changeset/static/description/icon.png
  base_changeset/static/description/index.html
  base_changeset/static/src/img/badge.png
  base_changeset/static/src/img/badge_click.png
  base_changeset/static/src/img/changeset.png
  base_changeset/static/src/img/rules.png
  base_changeset/static/src/js/backend.js
  base_changeset/static/src/scss/backend.scss
  base_changeset/static/src/xml/backend.xml
  base_changeset/templates/assets.xml
  base_changeset/tests/__init__.py
  base_changeset/tests/common.py
  base_changeset/tests/test_changeset_field_rule.py
  base_changeset/tests/test_changeset_field_type.py
  base_changeset/tests/test_changeset_flow.py
  base_changeset/tests/test_changeset_origin.py
  base_changeset/views/changeset_field_rule_views.xml
  base_changeset/views/menu.xml
  base_changeset/views/record_changeset_change_views.xml
  base_changeset/views/record_changeset_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2203 Update dotfiles, rebel fetchmail_notify_error_to_sender
  .copier-answers.yml
  .eslintrc.yml
  .travis.yml
Labels: bot is merging ⏳

#2007 [14.0][MIG] dbfilter_from_header
  dbfilter_from_header/README.rst
  dbfilter_from_header/__init__.py
  dbfilter_from_header/__manifest__.py
  dbfilter_from_header/i18n/dbfilter_from_header.pot
  dbfilter_from_header/i18n/zh_CN.po
  dbfilter_from_header/override.py
  dbfilter_from_header/readme/CONFIGURE.rst
  dbfilter_from_header/readme/CONTRIBUTORS.rst
  dbfilter_from_header/readme/DESCRIPTION.rst
  dbfilter_from_header/readme/INSTALL.rst
  dbfilter_from_header/readme/USAGE.rst
  dbfilter_from_header/static/description/icon.png
  dbfilter_from_header/static/description/index.html
  setup/dbfilter_from_header/odoo/addons/dbfilter_from_header
  setup/dbfilter_from_header/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2196 [15.0][MIG] upgrade_analysis: Migration to 15.0
  requirements.txt
  setup/upgrade_analysis/odoo/addons/upgrade_analysis
  setup/upgrade_analysis/setup.py
  upgrade_analysis/README.rst
  upgrade_analysis/__init__.py
  upgrade_analysis/__manifest__.py
  upgrade_analysis/blacklist.py
  upgrade_analysis/compare.py
  upgrade_analysis/i18n/fr.po
  upgrade_analysis/i18n/upgrade_analysis.pot
  upgrade_analysis/models/__init__.py
  upgrade_analysis/models/ir_module_module.py
  upgrade_analysis/models/upgrade_analysis.py
  upgrade_analysis/models/upgrade_attribute.py
  upgrade_analysis/models/upgrade_comparison_config.py
  upgrade_analysis/models/upgrade_record.py
  upgrade_analysis/odoo_patch/__init__.py
  upgrade_analysis/odoo_patch/addons/__init__.py
  upgrade_analysis/odoo_patch/addons/mrp/__init__.py
  upgrade_analysis/odoo_patch/addons/point_of_sale/__init__.py
  upgrade_analysis/odoo_patch/addons/stock/__init__.py
  upgrade_analysis/odoo_patch/odoo/__init__.py
  upgrade_analysis/odoo_patch/odoo/models.py
  upgrade_analysis/odoo_patch/odoo/modules/__init__.py
  upgrade_analysis/odoo_patch/odoo/modules/registry.py
  upgrade_analysis/odoo_patch/odoo/tools/__init__.py
  upgrade_analysis/odoo_patch/odoo/tools/convert.py
  upgrade_analysis/odoo_patch/odoo_patch.py
  upgrade_analysis/readme/CONTRIBUTORS.rst
  upgrade_analysis/readme/DESCRIPTION.rst
  upgrade_analysis/readme/ROADMAP.rst
  upgrade_analysis/security/ir.model.access.csv
  upgrade_analysis/static/description/icon.png
  upgrade_analysis/static/description/index.html
  upgrade_analysis/tests/__init__.py
  upgrade_analysis/tests/test_module.py
  upgrade_analysis/upgrade_log.py
  upgrade_analysis/views/menu.xml
  upgrade_analysis/views/view_upgrade_analysis.xml
  upgrade_analysis/views/view_upgrade_comparison_config.xml
  upgrade_analysis/views/view_upgrade_record.xml
  upgrade_analysis/wizards/__init__.py
  upgrade_analysis/wizards/upgrade_generate_record_wizard.py
  upgrade_analysis/wizards/upgrade_install_wizard.py
  upgrade_analysis/wizards/view_upgrade_generate_record_wizard.xml
  upgrade_analysis/wizards/view_upgrade_install_wizard.xml
Labels: approved, bot is merging ⏳

#2189 [14.0][IMP] base_jsonify: Allow to export many2one and referene field as simple field
  base_jsonify/models/models.py
  base_jsonify/tests/test_get_parser.py
Labels: approved, ready to merge, bot is merging ⏳

#2179 14.0 mig sequence python
  sequence_python/README.rst
  sequence_python/__init__.py
  sequence_python/__manifest__.py
  sequence_python/i18n/sequence_python.pot
  sequence_python/models/__init__.py
  sequence_python/models/ir_sequence.py
  sequence_python/readme/CONTRIBUTORS.rst
  sequence_python/readme/DESCRIPTION.rst
  sequence_python/readme/USAGE.rst
  sequence_python/static/description/icon.png
  sequence_python/static/description/index.html
  sequence_python/tests/__init__.py
  sequence_python/tests/test_ir_sequence.py
  sequence_python/views/ir_sequence.xml
Labels: approved, ready to merge, bot is merging ⏳

#2206 [IMP] upgrade_analysis: generate coverage module file
  requirements.txt
  upgrade_analysis/__manifest__.py
  upgrade_analysis/models/upgrade_analysis.py
  upgrade_analysis/static/src/module_coverage_template.rst.mako
Labels: approved, bot is merging ⏳

#2080 [14.0][ADD] base_sequence_option
  base_sequence_option/__init__.py
  base_sequence_option/__manifest__.py
  base_sequence_option/models/__init__.py
  base_sequence_option/models/ir_sequence.py
  base_sequence_option/models/ir_sequence_option.py
  base_sequence_option/readme/CONTRIBUTORS.rst
  base_sequence_option/readme/DESCRIPTION.rst
  base_sequence_option/readme/USAGE.rst
  base_sequence_option/security/ir.model.access.csv
  base_sequence_option/security/sequence_option_security.xml
  base_sequence_option/static/description/icon.png
  base_sequence_option/static/description/index.html
  base_sequence_option/tests/__init__.py
  base_sequence_option/tests/base_sequence_tester.py
  base_sequence_option/tests/common.py
  base_sequence_option/tests/test_ir_sequence_option.py
  base_sequence_option/views/sequence_option_view.xml
  setup/base_sequence_option/odoo/addons/base_sequence_option
  setup/base_sequence_option/setup.py
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#2215 [FIX] base_exception: use odoo-test-helper
  base_exception/tests/__init__.py
  base_exception/tests/_purchase_test_models.py
  base_exception/tests/common.py
  base_exception/tests/test_base_exception.py
  test-requirements.txt
Labels: bug, approved, bot is merging ⏳

#2197 [14.0][IMP] base_exception: Allow to skip exception checks through context
  base_exception/models/base_exception.py
Labels: approved, ready to merge, bot is merging ⏳

#1665 [12.0][ADD] base_deterministic_session_gc
  base_deterministic_session_gc/README.rst
  base_deterministic_session_gc/__init__.py
  base_deterministic_session_gc/__manifest__.py
  base_deterministic_session_gc/data/ir_cron_data.xml
  base_deterministic_session_gc/http.py
  base_deterministic_session_gc/models/__init__.py
  base_deterministic_session_gc/models/ir_autovacuum.py
  base_deterministic_session_gc/readme/CONFIGURE.rst
  base_deterministic_session_gc/readme/CONTRIBUTORS.rst
  base_deterministic_session_gc/readme/DESCRIPTION.rst
  base_deterministic_session_gc/readme/INSTALL.rst
  base_deterministic_session_gc/static/description/icon.png
  base_deterministic_session_gc/static/description/index.html
Labels: approved, bot is merging ⏳

#1811 [10.0] backport slow_statement_logger from 10.0
  setup/slow_statement_logger/odoo/__init__.py
  setup/slow_statement_logger/odoo/addons/__init__.py
  setup/slow_statement_logger/odoo/addons/slow_statement_logger
  setup/slow_statement_logger/setup.py
  slow_statement_logger/README.rst
  slow_statement_logger/__init__.py
  slow_statement_logger/__manifest__.py
  slow_statement_logger/i18n/slow_statement_logger.pot
  slow_statement_logger/readme/CONTRIBUTORS.rst
  slow_statement_logger/readme/DESCRIPTION.rst
  slow_statement_logger/readme/USAGE.rst
  slow_statement_logger/static/description/icon.png
  slow_statement_logger/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#1847 [WIP][MIG] base_name_search_improved: Migration to 13.0
  base_name_search_improved/README.rst
  base_name_search_improved/__init__.py
  base_name_search_improved/__manifest__.py
  base_name_search_improved/hooks.py
  base_name_search_improved/i18n/ca.po
  base_name_search_improved/i18n/de.po
  base_name_search_improved/i18n/es.po
  base_name_search_improved/i18n/es_ES.po
  base_name_search_improved/i18n/eu.po
  base_name_search_improved/i18n/fi.po
  base_name_search_improved/i18n/fr.po
  base_name_search_improved/i18n/hr.po
  base_name_search_improved/i18n/hr_HR.po
  base_name_search_improved/i18n/it.po
  base_name_search_improved/i18n/nb_NO.po
  base_name_search_improved/i18n/nl.po
  base_name_search_improved/i18n/pt_BR.po
  base_name_search_improved/i18n/sl.po
  base_name_search_improved/i18n/tr.po
  base_name_search_improved/i18n/tr_TR.po
  base_name_search_improved/i18n/zh_CN.po
  base_name_search_improved/images/image0.png
  base_name_search_improved/images/image1.png
  base_name_search_improved/images/image2.png
  base_name_search_improved/models/__init__.py
  base_name_search_improved/models/ir_model.py
  base_name_search_improved/readme/CONFIGURE.rst
  base_name_search_improved/readme/CONTRIBUTORS.rst
  base_name_search_improved/readme/CREDITS.rst
  base_name_search_improved/readme/DESCRIPTION.rst
  base_name_search_improved/readme/ROADMAP.rst
  base_name_search_improved/readme/USAGE.rst
  base_name_search_improved/static/description/icon.png
  base_name_search_improved/tests/__init__.py
  base_name_search_improved/tests/test_name_search.py
  base_name_search_improved/views/ir_model_views.xml
  setup/base_name_search_improved/odoo/addons/base_name_search_improved
  setup/base_name_search_improved/setup.py
Labels: approved, bot is merging ⏳

#2205 [10.0][IMP] use acme client
  .travis.yml
  letsencrypt/README.rst
  letsencrypt/__manifest__.py
  letsencrypt/controllers/main.py
  letsencrypt/data/ir_config_parameter.xml
  letsencrypt/data/ir_cron.xml
  letsencrypt/demo/ir_cron.xml
  letsencrypt/hooks.py
  letsencrypt/migrations/10.0.2.0.0/post-migrate.py
  letsencrypt/models/__init__.py
  letsencrypt/models/base_config_settings.py
  letsencrypt/models/letsencrypt.py
  letsencrypt/readme/CONFIGURE.rst
  letsencrypt/readme/CONTRIBUTORS.rst
  letsencrypt/readme/CREDITS.rst
  letsencrypt/readme/DESCRIPTION.rst
  letsencrypt/readme/INSTALL.rst
  letsencrypt/readme/USAGE.rst
  letsencrypt/static/description/index.html
  letsencrypt/tests/__init__.py
  letsencrypt/tests/test_letsencrypt.py
  letsencrypt/views/base_config_settings.xml
  requirements.txt
Labels: bot is merging ⏳

#2201 [IMP] base_changeset: overhaul security
  base_changeset/models/base.py
  base_changeset/models/changeset_field_rule.py
  base_changeset/models/record_changeset_change.py
  base_changeset/readme/USAGE.rst
  base_changeset/security/groups.xml
  base_changeset/security/rules.xml
  base_changeset/tests/__init__.py
  base_changeset/tests/test_changeset_flow.py
  base_changeset/tests/test_changeset_security.py
  base_changeset/views/changeset_field_rule_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2135 [MIG] base_user_role_company: Backport to 10.0
  base_user_role_company/README.rst
  base_user_role_company/__init__.py
  base_user_role_company/__manifest__.py
  base_user_role_company/i18n/base_user_role_company.pot
  base_user_role_company/models/__init__.py
  base_user_role_company/models/ir_http.py
  base_user_role_company/models/role.py
  base_user_role_company/readme/CONFIGURE.rst
  base_user_role_company/readme/CONTRIBUTORS.rst
  base_user_role_company/readme/DESCRIPTION.rst
  base_user_role_company/readme/USAGE.rst
  base_user_role_company/static/description/icon.png
  base_user_role_company/static/description/index.html
  base_user_role_company/tests/__init__.py
  base_user_role_company/tests/test_role_per_company.py
  base_user_role_company/views/role.xml
Labels: approved, ready to merge, bot is merging ⏳

#2198 [14.0] [FW] base_exception: forward port PR#2042, PR#2054
  base_exception/models/base_exception.py
  base_exception/tests/test_base_exception.py
  base_exception/views/base_exception_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1890 [10.0][FIX] Authadmin passkey doesn't validate param before eval
  auth_admin_passkey/models/res_users.py
Labels: approved, bot is merging ⏳

#1895 [13.0][MIG] bus_alt_connection
  bus_alt_connection/README.rst
  bus_alt_connection/__init__.py
  bus_alt_connection/__manifest__.py
  bus_alt_connection/i18n/bus_alt_connection.pot
  bus_alt_connection/models/__init__.py
  bus_alt_connection/models/bus.py
  bus_alt_connection/readme/CONFIGURE.rst
  bus_alt_connection/readme/CONTRIBUTORS.rst
  bus_alt_connection/readme/DESCRIPTION.rst
  bus_alt_connection/readme/INSTALL.rst
  bus_alt_connection/static/description/icon.png
  bus_alt_connection/static/description/index.html
  setup/bus_alt_connection/odoo/addons/bus_alt_connection
  setup/bus_alt_connection/setup.py
Labels: bot is merging ⏳

#1949 [MIG] 14.0 iap_alternative_provider
  iap_alternative_provider/README.rst
  iap_alternative_provider/__init__.py
  iap_alternative_provider/__manifest__.py
  iap_alternative_provider/i18n/iap_alternative_provider.pot
  iap_alternative_provider/models/__init__.py
  iap_alternative_provider/models/iap_account.py
  iap_alternative_provider/readme/CONTRIBUTORS.rst
  iap_alternative_provider/readme/DESCRIPTION.rst
  iap_alternative_provider/static/description/icon.png
  iap_alternative_provider/static/description/index.html
  iap_alternative_provider/views/iap_account_view.xml
  setup/iap_alternative_provider/odoo/addons/iap_alternative_provider
  setup/iap_alternative_provider/setup.py
Labels: approved, bot is merging ⏳

#2188 [12.0] base_model_restrict_update Add option 'Readonly User' to all models
  base_model_restrict_update/models/ir_model_access.py
  base_model_restrict_update/models/res_users.py
  base_model_restrict_update/readme/CONFIGURE.rst
  base_model_restrict_update/tests/test_base_model_restrict_update.py
  base_model_restrict_update/views/res_users_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2209 [14.0][MIG] base_name_search_multi_lang
  base_name_search_multi_lang/README.rst
  base_name_search_multi_lang/__init__.py
  base_name_search_multi_lang/__manifest__.py
  base_name_search_multi_lang/i18n/base_name_search_multi_lang.pot
  base_name_search_multi_lang/models/__init__.py
  base_name_search_multi_lang/models/ir_model.py
  base_name_search_multi_lang/readme/CONFIGURE.rst
  base_name_search_multi_lang/readme/CONTRIBUTORS.rst
  base_name_search_multi_lang/readme/DESCRIPTION.rst
  base_name_search_multi_lang/readme/USAGE.rst
  base_name_search_multi_lang/static/description/icon.png
  base_name_search_multi_lang/static/description/index.html
  base_name_search_multi_lang/tests/__init__.py
  base_name_search_multi_lang/tests/test_name_search.py
  base_name_search_multi_lang/views/ir_model_views.xml
  setup/base_name_search_multi_lang/odoo/addons/base_name_search_multi_lang
  setup/base_name_search_multi_lang/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#785 10.0 mig save translation file
  save_translation_file/README.rst
  save_translation_file/__init__.py
  save_translation_file/__manifest__.py
  save_translation_file/i18n/de.po
  save_translation_file/i18n/es.po
  save_translation_file/i18n/fr.po
  save_translation_file/i18n/it.po
  save_translation_file/i18n/save_translation_file.pot
  save_translation_file/i18n/sl.po
  save_translation_file/i18n/tr.po
  save_translation_file/models/__init__.py
  save_translation_file/models/save_translation_file.py
  save_translation_file/static/description/icon.png
  save_translation_file/tests/__init__.py
  save_translation_file/tests/test_save_translation_file.py
  save_translation_file/views/save_translation_file_view.xml
Labels: bot is merging ⏳

#2216 [14.0][IMP] base_view_inheritance_extension: real python_dict from ast tree
  base_view_inheritance_extension/__manifest__.py
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/readme/CONTRIBUTORS.rst
  base_view_inheritance_extension/readme/ROADMAP.rst
  base_view_inheritance_extension/readme/USAGE.rst
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳
