Repository OCA/server-tools, pull requests merged in 2021-07, with the labels that each got.

#2107 [14.0][mig] sql_export_mail
  setup/sql_export_mail/odoo/addons/sql_export_mail
  setup/sql_export_mail/setup.py
  sql_export_mail/README.rst
  sql_export_mail/__init__.py
  sql_export_mail/__manifest__.py
  sql_export_mail/i18n/fr.po
  sql_export_mail/i18n/sql_export_mail.pot
  sql_export_mail/mail_template.xml
  sql_export_mail/models/__init__.py
  sql_export_mail/models/sql_export.py
  sql_export_mail/readme/CONFIGURE.rst
  sql_export_mail/readme/CONTRIBUTORS.rst
  sql_export_mail/readme/DESCRIPTION.rst
  sql_export_mail/static/description/icon.png
  sql_export_mail/static/description/index.html
  sql_export_mail/tests/__init__.py
  sql_export_mail/tests/test_sql_query_mail.py
  sql_export_mail/views/sql_export_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1629 [12.0][ADD] bus_alt_connection
  bus_alt_connection/README.rst
  bus_alt_connection/__init__.py
  bus_alt_connection/__manifest__.py
  bus_alt_connection/models/__init__.py
  bus_alt_connection/models/bus.py
  bus_alt_connection/readme/CONFIGURE.rst
  bus_alt_connection/readme/CONTRIBUTORS.rst
  bus_alt_connection/readme/DESCRIPTION.rst
  bus_alt_connection/readme/INSTALL.rst
  bus_alt_connection/static/description/icon.png
  bus_alt_connection/static/description/index.html
Labels: approved, bot is merging ⏳

#2129 [13.0][MIG] attachment_unindex_content: Migration to 13.0
  attachment_unindex_content/README.rst
  attachment_unindex_content/__init__.py
  attachment_unindex_content/__manifest__.py
  attachment_unindex_content/hooks.py
  attachment_unindex_content/i18n/attachment_unindex_content.pot
  attachment_unindex_content/models/__init__.py
  attachment_unindex_content/models/ir_attachment.py
  attachment_unindex_content/readme/CONTRIBUTORS.rst
  attachment_unindex_content/readme/DESCRIPTION.rst
  attachment_unindex_content/static/description/icon.png
  attachment_unindex_content/static/description/index.html
  excel_import_export/models/xlsx_template.py
  setup/attachment_unindex_content/odoo/addons/attachment_unindex_content
  setup/attachment_unindex_content/setup.py
Labels: bot is merging ⏳

#2122 [14.0][mig]test_base_time_window
  setup/test_base_time_window/odoo/addons/test_base_time_window
  setup/test_base_time_window/setup.py
  test_base_time_window/README.rst
  test_base_time_window/__init__.py
  test_base_time_window/__manifest__.py
  test_base_time_window/i18n/es.po
  test_base_time_window/i18n/test_base_time_window.pot
  test_base_time_window/models/__init__.py
  test_base_time_window/models/partner_time_window.py
  test_base_time_window/models/res_partner.py
  test_base_time_window/readme/CONTRIBUTORS.rst
  test_base_time_window/readme/DESCRIPTION.rst
  test_base_time_window/security/ir.model.access.xml
  test_base_time_window/static/description/icon.png
  test_base_time_window/static/description/index.html
  test_base_time_window/tests/__init__.py
  test_base_time_window/tests/test_base_time_window.py
Labels: approved, bot is merging ⏳, ready to merge

#2095 [14.0][MIG] fetchmail_incoming_log: Migration to 14.0
  .travis.yml
  fetchmail_incoming_log/README.rst
  fetchmail_incoming_log/__init__.py
  fetchmail_incoming_log/__manifest__.py
  fetchmail_incoming_log/i18n/ca.po
  fetchmail_incoming_log/i18n/de.po
  fetchmail_incoming_log/i18n/es.po
  fetchmail_incoming_log/i18n/fetchmail_incoming_log.pot
  fetchmail_incoming_log/i18n/fr.po
  fetchmail_incoming_log/i18n/it.po
  fetchmail_incoming_log/i18n/pt_BR.po
  fetchmail_incoming_log/i18n/pt_PT.po
  fetchmail_incoming_log/i18n/sl.po
  fetchmail_incoming_log/i18n/tr.po
  fetchmail_incoming_log/models/__init__.py
  fetchmail_incoming_log/models/mail_thread.py
  fetchmail_incoming_log/readme/CONTRIBUTORS.rst
  fetchmail_incoming_log/readme/DESCRIPTION.rst
  fetchmail_incoming_log/static/description/icon.png
  fetchmail_incoming_log/static/description/index.html
  fetchmail_incoming_log/tests/__init__.py
  fetchmail_incoming_log/tests/test_fetchmail_incoming_log.py
  setup/fetchmail_incoming_log/odoo/addons/fetchmail_incoming_log
  setup/fetchmail_incoming_log/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#2146 14.0: sql_request_abstract : add legalsylvain as maintainers
  sql_request_abstract/__manifest__.py
Labels: approved, bot is merging ⏳

#2144 [Fix]: Add header feature in latest v14.
  sql_request_abstract/__manifest__.py
  sql_request_abstract/models/sql_request_mixin.py
  sql_request_abstract/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#2090 [14.0][MIG] html_text : Migration to 14.0
  html_text/README.rst
  html_text/__init__.py
  html_text/__manifest__.py
  html_text/i18n/ca.po
  html_text/i18n/de.po
  html_text/i18n/es.po
  html_text/i18n/es_ES.po
  html_text/i18n/hr.po
  html_text/i18n/html_text.pot
  html_text/i18n/it.po
  html_text/i18n/tr.po
  html_text/i18n/zh_CN.po
  html_text/models/__init__.py
  html_text/models/ir_fields_converter.py
  html_text/readme/CONTRIBUTORS.rst
  html_text/readme/DESCRIPTION.rst
  html_text/readme/ROADMAP.rst
  html_text/readme/USAGE.rst
  html_text/static/description/icon.png
  html_text/static/description/index.html
  html_text/tests/__init__.py
  html_text/tests/test_extractor.py
  setup/html_text/odoo/addons/html_text
  setup/html_text/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#2140 [14.0][MIG] attachment_unindex_content: Migration to 14.0
  attachment_unindex_content/README.rst
  attachment_unindex_content/__init__.py
  attachment_unindex_content/__manifest__.py
  attachment_unindex_content/hooks.py
  attachment_unindex_content/i18n/attachment_unindex_content.pot
  attachment_unindex_content/models/__init__.py
  attachment_unindex_content/models/ir_attachment.py
  attachment_unindex_content/readme/CONTRIBUTORS.rst
  attachment_unindex_content/readme/DESCRIPTION.rst
  attachment_unindex_content/static/description/icon.png
  attachment_unindex_content/static/description/index.html
  setup/attachment_unindex_content/odoo/addons/attachment_unindex_content
  setup/attachment_unindex_content/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#2121 [14.0] [mig] datetime_formatter
  datetime_formatter/README.rst
  datetime_formatter/__init__.py
  datetime_formatter/__manifest__.py
  datetime_formatter/i18n/ar.po
  datetime_formatter/i18n/ca.po
  datetime_formatter/i18n/datetime_formatter.pot
  datetime_formatter/i18n/de.po
  datetime_formatter/i18n/es.po
  datetime_formatter/i18n/fr.po
  datetime_formatter/i18n/hr.po
  datetime_formatter/i18n/it.po
  datetime_formatter/i18n/nl_NL.po
  datetime_formatter/i18n/pt.po
  datetime_formatter/i18n/sl.po
  datetime_formatter/i18n/tr.po
  datetime_formatter/i18n/zh_CN.po
  datetime_formatter/models/__init__.py
  datetime_formatter/models/res_lang.py
  datetime_formatter/readme/CONTRIBUTORS.rst
  datetime_formatter/readme/DESCRIPTION.rst
  datetime_formatter/readme/USAGE.rst
  datetime_formatter/static/description/icon.png
  datetime_formatter/static/description/index.html
  datetime_formatter/tests/__init__.py
  datetime_formatter/tests/test_best_matcher.py
  datetime_formatter/tests/test_formatter.py
  setup/datetime_formatter/odoo/addons/datetime_formatter
  setup/datetime_formatter/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#2115 [14.0][mig]sql_export_excel
  setup/sql_export_excel/odoo/addons/sql_export_excel
  setup/sql_export_excel/setup.py
  sql_export_excel/README.rst
  sql_export_excel/__init__.py
  sql_export_excel/__manifest__.py
  sql_export_excel/i18n/sql_export_excel.pot
  sql_export_excel/models/__init__.py
  sql_export_excel/models/sql_export.py
  sql_export_excel/readme/CONFIGURE.rst
  sql_export_excel/readme/CONTRIBUTORS.rst
  sql_export_excel/readme/DESCRIPTION.rst
  sql_export_excel/static/description/icon.png
  sql_export_excel/static/description/index.html
  sql_export_excel/tests/__init__.py
  sql_export_excel/tests/test_sql_query_excel.py
  sql_export_excel/views/sql_export_view.xml
Labels: approved, bot is merging ⏳, ready to merge
