Repository OCA/server-tools, pull requests merged in 2022-05, with the labels that each got.

#2332 [14.0] jsonifier: fix date handling
  jsonifier/models/models.py
Labels: bug, approved, bot is merging ⏳

#2338 [15.0][ADD] link to usage instructions
  upgrade_analysis/readme/USAGE.rst
Labels: bot is merging ⏳

#2336 [12.0][FIX] company_country: handle nonexisting env variable gracefully
  company_country/models/res_config.py
  company_country/tests/test_company_country.py
Labels: bot is merging ⏳

#2347 [14.0] [IMP] `base_exception`: log traceback when code eval exception is raised
  base_exception/models/base_exception.py
Labels: approved, bot is merging ⏳

#2349 [REF] excel_import_export: remove xlrd & xlwt from external dependencies
  excel_import_export/__manifest__.py
  requirements.txt
Labels: approved, bot is merging ⏳
