Repository OCA/server-tools, pull requests merged in 2022-03, with the labels that each got.

#2298 14.0 1831 port rebased and cleanup
  base_exception/__manifest__.py
  base_exception/models/base_exception.py
  base_exception/tests/__init__.py
  base_exception/tests/common.py
  base_exception/tests/purchase_test.py
  base_exception/tests/test_base_exception.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#2294 [14.0] rpc_helper: add config via UI
  rpc_helper/__init__.py
  rpc_helper/__manifest__.py
  rpc_helper/models/__init__.py
  rpc_helper/models/ir_model.py
  rpc_helper/patch.py
  rpc_helper/readme/CONFIGURATION.rst
  rpc_helper/readme/USAGE.rst
  rpc_helper/rpc_test_example.py
  rpc_helper/tests/test_xmlrpc.py
  rpc_helper/views/ir_model_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2307 [14.0][IMP] onchange_helper: Call onchange only if fields are concerned by
  onchange_helper/models/base.py
Labels: approved, bot is merging ⏳

#2286 [15.0] [MIG] fetchmail_notify_error_to_sender
  fetchmail_notify_error_to_sender/README.rst
  fetchmail_notify_error_to_sender/__init__.py
  fetchmail_notify_error_to_sender/__manifest__.py
  fetchmail_notify_error_to_sender/data/email_template_data.xml
  fetchmail_notify_error_to_sender/i18n/ca.po
  fetchmail_notify_error_to_sender/i18n/de.po
  fetchmail_notify_error_to_sender/i18n/es.po
  fetchmail_notify_error_to_sender/i18n/fetchmail_notify_error_to_sender.pot
  fetchmail_notify_error_to_sender/i18n/fr.po
  fetchmail_notify_error_to_sender/i18n/hr.po
  fetchmail_notify_error_to_sender/i18n/it.po
  fetchmail_notify_error_to_sender/i18n/pt_BR.po
  fetchmail_notify_error_to_sender/i18n/pt_PT.po
  fetchmail_notify_error_to_sender/i18n/sl.po
  fetchmail_notify_error_to_sender/i18n/tr.po
  fetchmail_notify_error_to_sender/i18n/zh_CN.po
  fetchmail_notify_error_to_sender/models/__init__.py
  fetchmail_notify_error_to_sender/models/fetchmail.py
  fetchmail_notify_error_to_sender/models/mail_thread.py
  fetchmail_notify_error_to_sender/readme/CONFIGURE.rst
  fetchmail_notify_error_to_sender/readme/CONTRIBUTORS.rst
  fetchmail_notify_error_to_sender/readme/DESCRIPTION.rst
  fetchmail_notify_error_to_sender/static/description/icon.png
  fetchmail_notify_error_to_sender/static/description/index.html
  fetchmail_notify_error_to_sender/views/fetchmail_view.xml
  setup/fetchmail_notify_error_to_sender/odoo/addons/fetchmail_notify_error_to_sender
  setup/fetchmail_notify_error_to_sender/setup.py
Labels: approved, bot is merging ⏳

#2200 [13.0][BACKPORT] base_sparse_field_list_support
  base_sparse_field_list_support/__init__.py
  base_sparse_field_list_support/__manifest__.py
  base_sparse_field_list_support/models/__init__.py
  base_sparse_field_list_support/models/fields.py
  base_sparse_field_list_support/readme/CONTRIBUTORS.rst
  base_sparse_field_list_support/readme/DESCRIPTION.rst
  setup/base_sparse_field_list_support/odoo/addons/base_sparse_field_list_support
  setup/base_sparse_field_list_support/setup.py
Labels: approved, bot is merging ⏳

#1891 [Updated] database_cleanup icon
  database_cleanup/static/description/icon.png
  database_cleanup/static/description/icon.svg
Labels: approved, ready to merge, bot is merging ⏳

#2291 [14.0][IMP] sql_export: Make possible to make sql queries on an external database
  sql_export/tests/test_sql_query.py
  sql_export/views/sql_export_view.xml
  sql_request_abstract/__init__.py
  sql_request_abstract/models/sql_request_mixin.py
  sql_request_abstract/readme/CONFIGURE.rst
  sql_request_abstract/readme/DESCRIPTION.rst
  sql_request_abstract/sql_db.py
Labels: approved, ready to merge, bot is merging ⏳

#2235 [15.0][MIG] onchange_helper
  onchange_helper/README.rst
  onchange_helper/__init__.py
  onchange_helper/__manifest__.py
  onchange_helper/i18n/cs_CZ.po
  onchange_helper/i18n/de.po
  onchange_helper/i18n/es.po
  onchange_helper/i18n/fr.po
  onchange_helper/i18n/hr.po
  onchange_helper/i18n/onchange_helper.pot
  onchange_helper/i18n/sl.po
  onchange_helper/i18n/zh_CN.po
  onchange_helper/models/__init__.py
  onchange_helper/models/base.py
  onchange_helper/readme/CONTRIBUTORS.rst
  onchange_helper/readme/DESCRIPTION.rst
  onchange_helper/readme/USAGE.rst
  onchange_helper/static/description/icon.png
  onchange_helper/static/description/index.html
  onchange_helper/tests/__init__.py
  onchange_helper/tests/test_onchange_helper.py
  setup/onchange_helper/odoo/addons/onchange_helper
  setup/onchange_helper/setup.py
Labels: approved, bot is merging ⏳

#2274 [MIG] datetime formatter: Migration to 15.0
  datetime_formatter/README.rst
  datetime_formatter/__init__.py
  datetime_formatter/__manifest__.py
  datetime_formatter/i18n/ar.po
  datetime_formatter/i18n/ca.po
  datetime_formatter/i18n/datetime_formatter.pot
  datetime_formatter/i18n/de.po
  datetime_formatter/i18n/es.po
  datetime_formatter/i18n/fr.po
  datetime_formatter/i18n/hr.po
  datetime_formatter/i18n/it.po
  datetime_formatter/i18n/nl_NL.po
  datetime_formatter/i18n/pt.po
  datetime_formatter/i18n/sl.po
  datetime_formatter/i18n/tr.po
  datetime_formatter/i18n/zh_CN.po
  datetime_formatter/models/__init__.py
  datetime_formatter/models/res_lang.py
  datetime_formatter/readme/CONTRIBUTORS.rst
  datetime_formatter/readme/DESCRIPTION.rst
  datetime_formatter/readme/USAGE.rst
  datetime_formatter/static/description/icon.png
  datetime_formatter/static/description/index.html
  datetime_formatter/tests/__init__.py
  datetime_formatter/tests/test_best_matcher.py
  datetime_formatter/tests/test_formatter.py
  module_auto_update/tests/sample_module/README.rst
  setup/datetime_formatter/odoo/addons/datetime_formatter
  setup/datetime_formatter/setup.py
Labels: bot is merging ⏳
