Repository OCA/server-tools, pull requests merged in 2022-01, with the labels that each got.

#2231 [14.0][IMP] upgrade_analysis: log sql_constraints in analysis
  upgrade_analysis/compare.py
  upgrade_analysis/models/upgrade_analysis.py
  upgrade_analysis/models/upgrade_record.py
  upgrade_analysis/odoo_patch/odoo/__init__.py
  upgrade_analysis/odoo_patch/odoo/addons/__init__.py
  upgrade_analysis/odoo_patch/odoo/addons/base/__init__.py
  upgrade_analysis/odoo_patch/odoo/addons/base/models/__init__.py
  upgrade_analysis/odoo_patch/odoo/addons/base/models/ir_model.py
  upgrade_analysis/upgrade_log.py
  upgrade_analysis/wizards/upgrade_generate_record_wizard.py
Labels: bot is merging ⏳

#2213 [14.0][FW] base_time_window: Forward updates from 13.0
  base_time_window/models/time_window_mixin.py
  test_base_time_window/tests/test_base_time_window.py
Labels: approved, ready to merge, bot is merging ⏳

#2257 [14.0] base_jsonify: re-license to LGPL
  base_jsonify/__manifest__.py
  base_jsonify/models/ir_export.py
  base_jsonify/models/ir_exports_line.py
  base_jsonify/models/ir_exports_resolver.py
  base_jsonify/models/models.py
  base_jsonify/tests/test_get_parser.py
  base_jsonify/tests/test_ir_exports_line.py
Labels: approved, bot is merging ⏳

#2247 [FIX][14.0] base_changeset : fix images path in readme files
  base_changeset/readme/CONFIGURE.rst
  base_changeset/readme/USAGE.rst
Labels: approved, ready to merge, bot is merging ⏳

#2238 [14.0][IMP] `base_jsonify`: Add `_jsonify_x2m_to_ids` and `_jsonify_format_duration` helpers
  base_jsonify/models/models.py
  base_jsonify/tests/__init__.py
  base_jsonify/tests/test_helpers.py
  base_jsonify/tests/test_ir_exports_line.py
Labels: approved, ready to merge, bot is merging ⏳

#2262 [12.0][FIX] Scheduler_error_mailer: fixed error printing in email
  scheduler_error_mailer/__manifest__.py
  scheduler_error_mailer/data/ir_cron_email_tpl.xml
  scheduler_error_mailer/migrations/12.0.1.1.0/post-migration.py
  scheduler_error_mailer/models/ir_cron.py
Labels: approved, bot is merging ⏳

#2101 [FIX] sql_request_abstract: make call to button idempotens
  sql_request_abstract/models/sql_request_mixin.py
Labels: bot is merging ⏳, stale

#2208 [14.0][IMP] base_jsonify: review
  base_jsonify/README.rst
  base_jsonify/__manifest__.py
  base_jsonify/i18n/base_jsonify.pot
  base_jsonify/i18n/zh_CN.po
  base_jsonify/models/__init__.py
  base_jsonify/models/ir_exports.py
  base_jsonify/models/ir_exports_line.py
  base_jsonify/models/ir_exports_resolver.py
  base_jsonify/models/models.py
  base_jsonify/models/utils.py
  base_jsonify/readme/DESCRIPTION.rst
  base_jsonify/static/description/index.html
  base_jsonify/tests/test_ir_exports_line.py
Labels: approved, ready to merge, bot is merging ⏳

#2264 [12.0][FIX] scheduler_error_mailer: fixed email template fields
  scheduler_error_mailer/__manifest__.py
  scheduler_error_mailer/data/ir_cron_email_tpl.xml
  scheduler_error_mailer/migrations/12.0.1.2.0/post-migration.py
Labels: approved, bot is merging ⏳

#2260 [13.0][MIG] scheduler_error_mailer: Migration to 13.0
  scheduler_error_mailer/README.rst
  scheduler_error_mailer/__init__.py
  scheduler_error_mailer/__manifest__.py
  scheduler_error_mailer/data/ir_cron_email_tpl.xml
  scheduler_error_mailer/demo/ir_cron_demo.xml
  scheduler_error_mailer/i18n/de.po
  scheduler_error_mailer/i18n/es.po
  scheduler_error_mailer/i18n/fr.po
  scheduler_error_mailer/i18n/hr.po
  scheduler_error_mailer/i18n/pt.po
  scheduler_error_mailer/i18n/pt_BR.po
  scheduler_error_mailer/i18n/scheduler_error_mailer.pot
  scheduler_error_mailer/i18n/sl.po
  scheduler_error_mailer/i18n/zh_CN.po
  scheduler_error_mailer/images/scheduler_error_mailer.jpg
  scheduler_error_mailer/models/__init__.py
  scheduler_error_mailer/models/ir_cron.py
  scheduler_error_mailer/readme/CONFIGURE.rst
  scheduler_error_mailer/readme/CONTRIBUTORS.rst
  scheduler_error_mailer/readme/DESCRIPTION.rst
  scheduler_error_mailer/static/description/icon.png
  scheduler_error_mailer/static/description/index.html
  scheduler_error_mailer/views/ir_cron.xml
  setup/scheduler_error_mailer/odoo/addons/scheduler_error_mailer
  setup/scheduler_error_mailer/setup.py
Labels: approved, bot is merging ⏳
