Repository OCA/server-tools, pull requests merged in 2022-12, with the labels that each got.

#2462 [16.0][MIG] base_fontawesome
  base_fontawesome/README.rst
  base_fontawesome/__init__.py
  base_fontawesome/__manifest__.py
  base_fontawesome/i18n/base_fontawesome.pot
  base_fontawesome/i18n/es_AR.po
  base_fontawesome/i18n/es_ES.po
  base_fontawesome/i18n/zh_CN.po
  base_fontawesome/readme/CONTRIBUTORS.rst
  base_fontawesome/readme/DESCRIPTION.rst
  base_fontawesome/readme/USAGE.rst
  base_fontawesome/static/description/icon.png
  base_fontawesome/static/description/index.html
  base_fontawesome/static/lib/fontawesome-5.15.4/css/all.css
  base_fontawesome/static/lib/fontawesome-5.15.4/css/v4-shims.css
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-brands-400.eot
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-brands-400.svg
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-brands-400.ttf
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-brands-400.woff
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-brands-400.woff2
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-regular-400.eot
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-regular-400.svg
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-regular-400.ttf
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-regular-400.woff
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-regular-400.woff2
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-solid-900.eot
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-solid-900.svg
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-solid-900.ttf
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-solid-900.woff
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-solid-900.woff2
  base_fontawesome/static/src/css/fontawesome.css
  base_fontawesome/static/src/js/form_renderer.js
  base_fontawesome/static/src/js/list_renderer.js
  setup/base_fontawesome/odoo/addons/base_fontawesome
  setup/base_fontawesome/setup.py
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#2484 [14.0][IMP] base_time_parameter: JSON data type
  base_time_parameter/models/base_time_parameter.py
  base_time_parameter/models/base_time_parameter_version.py
  base_time_parameter/tests/test_time_parameter.py
Labels: bot is merging ⏳

#2494 [MIG] base_view_inheritance_extension: Migration to 16.0
  base_view_inheritance_extension/README.rst
  base_view_inheritance_extension/__init__.py
  base_view_inheritance_extension/__manifest__.py
  base_view_inheritance_extension/demo/ir_ui_view.xml
  base_view_inheritance_extension/i18n/base_view_inheritance_extension.pot
  base_view_inheritance_extension/i18n/ca.po
  base_view_inheritance_extension/i18n/de.po
  base_view_inheritance_extension/i18n/es.po
  base_view_inheritance_extension/i18n/es_AR.po
  base_view_inheritance_extension/i18n/hr.po
  base_view_inheritance_extension/i18n/it.po
  base_view_inheritance_extension/i18n/sl.po
  base_view_inheritance_extension/i18n/tr.po
  base_view_inheritance_extension/models/__init__.py
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/readme/CONTRIBUTORS.rst
  base_view_inheritance_extension/readme/DESCRIPTION.rst
  base_view_inheritance_extension/readme/ROADMAP.rst
  base_view_inheritance_extension/readme/USAGE.rst
  base_view_inheritance_extension/static/description/icon.png
  base_view_inheritance_extension/static/description/index.html
  base_view_inheritance_extension/tests/__init__.py
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
  requirements.txt
  setup/base_view_inheritance_extension/odoo/addons/base_view_inheritance_extension
  setup/base_view_inheritance_extension/setup.py
Labels: approved, bot is merging ⏳

#2485 [14.0][FIX] auditlog: consistency with Many2one fields
  auditlog/models/rule.py
  auditlog/tests/test_auditlog.py
Labels: bug, approved, bot is merging ⏳

#2497 [14.0][IMP] base_time_parameter: value_reference: standard selection
  base_time_parameter/models/__init__.py
  base_time_parameter/models/base_time_parameter_version.py
  base_time_parameter/readme/USAGE.rst
  base_time_parameter/tests/test_time_parameter.py
  base_time_parameter/views/base_time_parameter_views.xml
Labels: bot is merging ⏳

#2501 [IMP] base_time_parameter: Added Reference ID type
  base_time_parameter/models/base_time_parameter.py
Labels: approved, bot is merging ⏳

#2503 [FIX] letsencrypt: freeze acme lib before version 2.0.0
  letsencrypt/__manifest__.py
  requirements.txt
Labels: bot is merging ⏳

#2340 [MIG][15.0] iap_alternative_provider
  iap_alternative_provider/README.rst
  iap_alternative_provider/__init__.py
  iap_alternative_provider/__manifest__.py
  iap_alternative_provider/i18n/ca.po
  iap_alternative_provider/i18n/iap_alternative_provider.pot
  iap_alternative_provider/models/__init__.py
  iap_alternative_provider/models/iap_account.py
  iap_alternative_provider/readme/CONTRIBUTORS.rst
  iap_alternative_provider/readme/DESCRIPTION.rst
  iap_alternative_provider/static/description/icon.png
  iap_alternative_provider/static/description/index.html
  iap_alternative_provider/tests/__init__.py
  iap_alternative_provider/tests/test_iap_account.py
  iap_alternative_provider/views/iap_account_view.xml
  setup/iap_alternative_provider/odoo/addons/iap_alternative_provider
  setup/iap_alternative_provider/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2493 [14.0] base_conditional_image: Migrate to new image fields
  base_conditional_image/__manifest__.py
  base_conditional_image/data/ir_cron.xml
  base_conditional_image/migrations/14.0.2.0.0/pre-migrate.py
  base_conditional_image/models/__init__.py
  base_conditional_image/models/abstract_image.py
  base_conditional_image/models/conditional_image.py
  base_conditional_image/models/conditional_image_consumer_mixin.py
  base_conditional_image/models/image.py
  base_conditional_image/readme/CONTRIBUTORS.rst
  base_conditional_image/readme/INSTALL.rst
  base_conditional_image/security/ir.model.access.csv
  base_conditional_image/views/image_view.xml
Labels: approved, bot is merging ⏳

#2504 [16.0][MIG] iap_alternative_provider: Migration to 16.0
  iap_alternative_provider/README.rst
  iap_alternative_provider/__init__.py
  iap_alternative_provider/__manifest__.py
  iap_alternative_provider/i18n/ca.po
  iap_alternative_provider/i18n/iap_alternative_provider.pot
  iap_alternative_provider/models/__init__.py
  iap_alternative_provider/models/iap_account.py
  iap_alternative_provider/readme/CONTRIBUTORS.rst
  iap_alternative_provider/readme/DESCRIPTION.rst
  iap_alternative_provider/static/description/icon.png
  iap_alternative_provider/static/description/index.html
  iap_alternative_provider/tests/__init__.py
  iap_alternative_provider/tests/test_iap_account.py
  iap_alternative_provider/views/iap_account_view.xml
  setup/iap_alternative_provider/odoo/addons/iap_alternative_provider
  setup/iap_alternative_provider/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2511 [14.0][FIX] base_time_parameter: type reference_id: show value_reference
  base_time_parameter/views/base_time_parameter_views.xml
Labels: bot is merging ⏳

#2509 [IMP] auditlog: make the line views using a non auto model
  auditlog/migrations/14.0.1.2.0/pre-migration.py
  auditlog/models/__init__.py
  auditlog/models/auditlog_log_line_view.py
  auditlog/models/log.py
  auditlog/security/ir.model.access.csv
  auditlog/tests/test_auditlog.py
  auditlog/views/auditlog_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2512 [15.0][IMP] auditlog: make the line views using a non auto model
  auditlog/migrations/14.0.1.1.0/pre-migration.py
  auditlog/models/__init__.py
  auditlog/models/auditlog_log_line_view.py
  auditlog/models/log.py
  auditlog/security/ir.model.access.csv
  auditlog/tests/test_auditlog.py
  auditlog/views/auditlog_view.xml
Labels: approved, bot is merging ⏳

#2513 [16.0][IMP] auditlog: make the line views using a non auto model
  auditlog/models/__init__.py
  auditlog/models/auditlog_log_line_view.py
  auditlog/models/log.py
  auditlog/security/ir.model.access.csv
  auditlog/views/auditlog_view.xml
Labels: approved, bot is merging ⏳

#2425 [16.0][MIG] dbfilter_from_header
  dbfilter_from_header/README.rst
  dbfilter_from_header/__init__.py
  dbfilter_from_header/__manifest__.py
  dbfilter_from_header/i18n/dbfilter_from_header.pot
  dbfilter_from_header/i18n/es_AR.po
  dbfilter_from_header/i18n/zh_CN.po
  dbfilter_from_header/override.py
  dbfilter_from_header/readme/CONFIGURE.rst
  dbfilter_from_header/readme/CONTRIBUTORS.rst
  dbfilter_from_header/readme/DESCRIPTION.rst
  dbfilter_from_header/readme/INSTALL.rst
  dbfilter_from_header/readme/USAGE.rst
  dbfilter_from_header/static/description/icon.png
  dbfilter_from_header/static/description/index.html
  setup/dbfilter_from_header/odoo/addons/dbfilter_from_header
  setup/dbfilter_from_header/setup.py
Labels: approved, ready to merge, bot is merging ⏳
