Repository OCA/server-tools, pull requests merged in 2022-09, with the labels that each got.

#2252 [14.0][FIX] base_changeset: models may not have a `name` field
  base_changeset/models/record_changeset.py
  base_changeset/tests/test_changeset_flow.py
Labels: approved, ready to merge, bot is merging ⏳

#2111 [MIG] nsca_client: Migration to 13.0
  .travis.yml
  nsca_client/README.rst
  nsca_client/__init__.py
  nsca_client/__manifest__.py
  nsca_client/demo/demo_data.xml
  nsca_client/i18n/fr.po
  nsca_client/i18n/nsca_client.pot
  nsca_client/models/__init__.py
  nsca_client/models/nsca_check.py
  nsca_client/models/nsca_server.py
  nsca_client/readme/CONFIGURE.rst
  nsca_client/readme/CONTRIBUTORS.rst
  nsca_client/readme/DESCRIPTION.rst
  nsca_client/readme/INSTALL.rst
  nsca_client/security/ir.model.access.csv
  nsca_client/static/description/check.png
  nsca_client/static/description/icon.png
  nsca_client/static/description/server.png
  nsca_client/tests/__init__.py
  nsca_client/tests/test_nsca.py
  nsca_client/views/nsca_check.xml
  nsca_client/views/nsca_menu.xml
  nsca_client/views/nsca_server.xml
  setup/nsca_client/odoo/addons/nsca_client
  setup/nsca_client/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2341 [14.0][ADD] module : attachment_delete_restrict
  attachment_delete_restrict/README.rst
  attachment_delete_restrict/__init__.py
  attachment_delete_restrict/__manifest__.py
  attachment_delete_restrict/i18n/fr.po
  attachment_delete_restrict/i18n/ja.po
  attachment_delete_restrict/migrations/14.0.1.0.0/post-migrate.py
  attachment_delete_restrict/migrations/14.0.1.0.0/pre-migrate.py
  attachment_delete_restrict/models/__init__.py
  attachment_delete_restrict/models/ir_attachment.py
  attachment_delete_restrict/models/ir_model.py
  attachment_delete_restrict/models/res_config.py
  attachment_delete_restrict/models/res_groups.py
  attachment_delete_restrict/models/res_users.py
  attachment_delete_restrict/readme/CONFIGURE.rst
  attachment_delete_restrict/readme/CONTRIBUTORS.rst
  attachment_delete_restrict/readme/DESCRIPTION.rst
  attachment_delete_restrict/static/description/index.html
  attachment_delete_restrict/tests/__init__.py
  attachment_delete_restrict/tests/test_attachment_delete_restrict.py
  attachment_delete_restrict/views/ir_model_views.xml
  attachment_delete_restrict/views/res_config_view.xml
  attachment_delete_restrict/views/res_groups_views.xml
  attachment_delete_restrict/views/res_users_views.xml
  setup/attachment_delete_restrict/odoo/addons/attachment_delete_restrict
  setup/attachment_delete_restrict/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2245 [14.0][FIX] base_changeset: fix write return type
  base_changeset/models/base.py
Labels: approved, ready to merge, bot is merging ⏳

#2392 sql_export: improve menu position
  sql_export/views/sql_export_view.xml
Labels: approved, bot is merging ⏳

#1842 [13.0][ADD] Add new module: sequence_custom_data
  sequence_custom_data/README.rst
  sequence_custom_data/__init__.py
  sequence_custom_data/__manifest__.py
  sequence_custom_data/models/__init__.py
  sequence_custom_data/models/ir_sequence.py
  sequence_custom_data/readme/CONTRIBUTORS.rst
  sequence_custom_data/readme/DESCRIPTION.rst
  sequence_custom_data/readme/USAGE.rst
  sequence_custom_data/static/description/index.html
  sequence_custom_data/tests/__init__.py
  sequence_custom_data/tests/test_ir_sequence.py
  setup/sequence_custom_data/odoo/addons/sequence_custom_data
  setup/sequence_custom_data/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2396 [FIX][11.0] Make branch green
  company_country/models/res_config.py
  company_country/tests/test_company_country.py
  setup/letsencrypt/setup.py
Labels: approved, bot is merging ⏳

#2372 [MIG][15.0] base_conditional_image migration to 15.0
  base_conditional_image/README.rst
  base_conditional_image/__init__.py
  base_conditional_image/__manifest__.py
  base_conditional_image/i18n/base_conditional_image.pot
  base_conditional_image/models/__init__.py
  base_conditional_image/models/conditional_image.py
  base_conditional_image/models/conditional_image_consumer_mixin.py
  base_conditional_image/readme/CONTRIBUTORS.rst
  base_conditional_image/readme/CREDITS.rst
  base_conditional_image/readme/DESCRIPTION.rst
  base_conditional_image/readme/INSTALL.rst
  base_conditional_image/readme/USAGE.rst
  base_conditional_image/security/ir.model.access.csv
  base_conditional_image/static/description/icon.png
  base_conditional_image/static/description/index.html
  base_conditional_image/views/image_view.xml
  setup/base_conditional_image/odoo/addons/base_conditional_image
  setup/base_conditional_image/setup.py
Labels: approved, bot is merging ⏳

#2254 [14.0][MIG] sentry: migrate sentry-raven to new api sentry-sdk
  requirements.txt
  sentry/README.rst
  sentry/__init__.py
  sentry/__manifest__.py
  sentry/const.py
  sentry/generalutils.py
  sentry/hooks.py
  sentry/logutils.py
  sentry/processor.py
  sentry/readme/CONFIGURE.rst
  sentry/readme/CONTRIBUTORS.rst
  sentry/readme/CREDITS.rst
  sentry/readme/INSTALL.rst
  sentry/readme/USAGE.rst
  sentry/static/description/index.html
  sentry/tests/test_client.py
  sentry/tests/test_logutils.py
Labels: approved, ready to merge, bot is merging ⏳

#2318 [14.0] auditlog: Add option to Eliminate user and fields
  auditlog/models/rule.py
  auditlog/tests/test_auditlog.py
  auditlog/views/auditlog_view.xml
Labels: enhancement, bot is merging ⏳

#2406 [15.0][FW] [14.0] auditlog: Add option to Eliminate user and fields
  auditlog/models/rule.py
  auditlog/tests/test_auditlog.py
  auditlog/views/auditlog_view.xml
Labels: approved, bot is merging ⏳

#2408 [FIX] attachment_unindex_content: unsupported param on _index method
  attachment_unindex_content/__manifest__.py
  attachment_unindex_content/models/ir_attachment.py
Labels: bot is merging ⏳
