Repository OCA/server-tools, pull requests merged in 2022-08, with the labels that each got.

#2384 [14.0][FIX] base_search_fuzzy: fix syntax in Usage.rst
  base_search_fuzzy/readme/USAGE.rst
Labels: approved, bot is merging ⏳

#2387 [15.0][FIX] base_exception: Fix tests and add odoo_test_helper as dependency
  base_exception/tests/purchase_test.py
  base_exception/tests/test_base_exception.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#2092 12.0 backport module change auto install
  module_change_auto_install/README.rst
  module_change_auto_install/__init__.py
  module_change_auto_install/__manifest__.py
  module_change_auto_install/patch.py
  module_change_auto_install/readme/CONFIGURE.rst
  module_change_auto_install/readme/CONTRIBUTORS.rst
  module_change_auto_install/readme/DESCRIPTION.rst
  module_change_auto_install/readme/DEVELOP.rst
  module_change_auto_install/readme/INSTALL.rst
Labels: bot is merging ⏳, stale

#2218 [15.0] [MIG] dbfilter_from_header: Migration to 15.0
  dbfilter_from_header/README.rst
  dbfilter_from_header/__init__.py
  dbfilter_from_header/__manifest__.py
  dbfilter_from_header/i18n/dbfilter_from_header.pot
  dbfilter_from_header/i18n/zh_CN.po
  dbfilter_from_header/override.py
  dbfilter_from_header/readme/CONFIGURE.rst
  dbfilter_from_header/readme/CONTRIBUTORS.rst
  dbfilter_from_header/readme/DESCRIPTION.rst
  dbfilter_from_header/readme/INSTALL.rst
  dbfilter_from_header/readme/USAGE.rst
  dbfilter_from_header/static/description/icon.png
  dbfilter_from_header/static/description/index.html
  setup/dbfilter_from_header/odoo/addons/dbfilter_from_header
  setup/dbfilter_from_header/setup.py
Labels: approved, bot is merging ⏳

#2367 [REF] base_import_module_group: Remove not working auto-install
  base_import_module_group/__manifest__.py
Labels: approved, bot is merging ⏳

#2378 [12.0][FIX] auditlog: support update after data model changes in rules
  auditlog/models/rule.py
  auditlog/tests/test_auditlog.py
Labels: approved, ready to merge, bot is merging ⏳
