Repository OCA/server-tools, pull requests merged in 2022-11, with the labels that each got.

#2447 [14.0][IMP] base_time_parameter: hide form model except in technical settings
  base_time_parameter/readme/DESCRIPTION.rst
  base_time_parameter/readme/USAGE.rst
  base_time_parameter/views/base_time_parameter_views.xml
Labels: bot is merging ⏳

#2445 [FIX] auditlog: autovacuum performance
  auditlog/models/http_request.py
  auditlog/models/log.py
Labels: approved, bot is merging ⏳

#2444 [FIX] auditlog: autovacuum performance
  auditlog/models/http_request.py
  auditlog/models/log.py
Labels: approved, bot is merging ⏳

#2451 [14.0][IMP] base_time_parameter: date options, tests, documentation, fix views
  base_time_parameter/models/base.py
  base_time_parameter/readme/CONFIGURE.rst
  base_time_parameter/readme/DESCRIPTION.rst
  base_time_parameter/readme/USAGE.rst
  base_time_parameter/tests/test_time_parameter.py
  base_time_parameter/views/base_time_parameter_views.xml
Labels: bot is merging ⏳

#2246 [14.0][IMP] base_changeset: security overhaul and other ports from 12.0
  base_changeset/models/base.py
  base_changeset/models/changeset_field_rule.py
  base_changeset/models/record_changeset.py
  base_changeset/models/record_changeset_change.py
  base_changeset/readme/CONTRIBUTORS.rst
  base_changeset/readme/USAGE.rst
  base_changeset/security/groups.xml
  base_changeset/security/rules.xml
  base_changeset/tests/__init__.py
  base_changeset/tests/test_changeset_field_type.py
  base_changeset/tests/test_changeset_flow.py
  base_changeset/tests/test_changeset_origin.py
  base_changeset/tests/test_changeset_security.py
  base_changeset/views/changeset_field_rule_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2411 ]14.0][FIX] base_changeset: fix caching
  base_changeset/models/base.py
Labels: approved, ready to merge, bot is merging ⏳

#2453 [14.0][MIG] nsca_client: Migration to 14.0
  nsca_client/README.rst
  nsca_client/__init__.py
  nsca_client/__manifest__.py
  nsca_client/demo/demo_data.xml
  nsca_client/i18n/fr.po
  nsca_client/i18n/nsca_client.pot
  nsca_client/models/__init__.py
  nsca_client/models/nsca_check.py
  nsca_client/models/nsca_server.py
  nsca_client/readme/CONFIGURE.rst
  nsca_client/readme/CONTRIBUTORS.rst
  nsca_client/readme/DESCRIPTION.rst
  nsca_client/readme/INSTALL.rst
  nsca_client/security/ir.model.access.csv
  nsca_client/static/description/check.png
  nsca_client/static/description/icon.png
  nsca_client/static/description/index.html
  nsca_client/static/description/server.png
  nsca_client/tests/__init__.py
  nsca_client/tests/test_nsca.py
  nsca_client/views/nsca_check.xml
  nsca_client/views/nsca_menu.xml
  nsca_client/views/nsca_server.xml
  setup/nsca_client/odoo/addons/nsca_client
  setup/nsca_client/setup.py
Labels: approved, migration, bot is merging ⏳

#2464 [14.0][IMP] base_time_parameter: more data types
  base_time_parameter/migrations/14.0.3.0.0/pre-migration.py
  base_time_parameter/models/base_time_parameter.py
  base_time_parameter/models/base_time_parameter_version.py
  base_time_parameter/readme/USAGE.rst
  base_time_parameter/tests/test_time_parameter.py
  base_time_parameter/views/base_time_parameter_views.xml
Labels: bot is merging ⏳

#2469 [14.0][FIX] PyCQA no longer has a gitlab mirror of repos
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: approved

#2448 [15.0][IMP] auditlog: dedicated security groups for model access
  auditlog/__manifest__.py
  auditlog/readme/USAGE.rst
  auditlog/security/ir.model.access.csv
  auditlog/security/res_groups.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#2471 [OU] auditlog: Improve time of upgrade
  auditlog/migrations/14.0.1.2.0/pre-migration.py
Labels: approved

#2470 [14.0] [IMP] base_time_parameter: Add get param
  base_time_parameter/models/base.py
  base_time_parameter/models/base_time_parameter.py
  base_time_parameter/tests/test_time_parameter.py
Labels: bot is merging ⏳
