Repository OCA/server-tools, pull requests merged in 2022-10, with the labels that each got.

#2244 [14.0][FIX] base_changeset: assign values for all computed fields
  base_changeset/models/record_changeset_change.py
  base_changeset/tests/test_changeset_flow.py
Labels: approved, ready to merge, bot is merging ⏳

#2133 [14.0][MIG] base_deterministic_session_gc
  base_deterministic_session_gc/README.rst
  base_deterministic_session_gc/__init__.py
  base_deterministic_session_gc/__manifest__.py
  base_deterministic_session_gc/data/ir_cron_data.xml
  base_deterministic_session_gc/http.py
  base_deterministic_session_gc/models/__init__.py
  base_deterministic_session_gc/models/ir_autovacuum.py
  base_deterministic_session_gc/readme/CONFIGURE.rst
  base_deterministic_session_gc/readme/CONTRIBUTORS.rst
  base_deterministic_session_gc/readme/DESCRIPTION.rst
  base_deterministic_session_gc/readme/INSTALL.rst
  base_deterministic_session_gc/static/description/icon.png
  base_deterministic_session_gc/static/description/index.html
  setup/base_deterministic_session_gc/odoo/addons/base_deterministic_session_gc
  setup/base_deterministic_session_gc/setup.py
Labels: approved, bot is merging ⏳

#2271 [FP][FIX][ENG][14.0] base_name_search_improved: forward port of patches and fix to interactive search
  base_name_search_improved/__manifest__.py
  base_name_search_improved/models/ir_model.py
  base_name_search_improved/readme/CONTRIBUTORS.rst
  base_name_search_improved/tests/test_name_search.py
  base_name_search_improved/views/ir_model_views.xml
Labels: approved, bot is merging ⏳

#2164 [12.0][ADD] attachment_delete_restrict
  attachment_delete_restrict/README.rst
  attachment_delete_restrict/__init__.py
  attachment_delete_restrict/__manifest__.py
  attachment_delete_restrict/i18n/ja.po
  attachment_delete_restrict/models/__init__.py
  attachment_delete_restrict/models/ir_attachment.py
  attachment_delete_restrict/models/ir_model.py
  attachment_delete_restrict/models/res_groups.py
  attachment_delete_restrict/models/res_users.py
  attachment_delete_restrict/readme/CONFIGURE.rst
  attachment_delete_restrict/readme/CONTRIBUTORS.rst
  attachment_delete_restrict/readme/DESCRIPTION.rst
  attachment_delete_restrict/static/description/index.html
  attachment_delete_restrict/tests/__init__.py
  attachment_delete_restrict/tests/test_attachment_delete_restrict.py
  attachment_delete_restrict/views/ir_model_views.xml
  attachment_delete_restrict/views/res_groups_views.xml
  attachment_delete_restrict/views/res_users_views.xml
Labels: approved, bot is merging ⏳

#2132 [13.0][MIG] base_deterministic_session_gc
  base_deterministic_session_gc/README.rst
  base_deterministic_session_gc/__init__.py
  base_deterministic_session_gc/__manifest__.py
  base_deterministic_session_gc/data/ir_cron_data.xml
  base_deterministic_session_gc/http.py
  base_deterministic_session_gc/models/__init__.py
  base_deterministic_session_gc/models/ir_autovacuum.py
  base_deterministic_session_gc/readme/CONFIGURE.rst
  base_deterministic_session_gc/readme/CONTRIBUTORS.rst
  base_deterministic_session_gc/readme/DESCRIPTION.rst
  base_deterministic_session_gc/readme/INSTALL.rst
  base_deterministic_session_gc/static/description/icon.png
  base_deterministic_session_gc/static/description/index.html
  setup/base_deterministic_session_gc/odoo/addons/base_deterministic_session_gc
  setup/base_deterministic_session_gc/setup.py
Labels: approved, bot is merging ⏳

#2240 [IMP] sql_export_mail : add mute mechanism
  sql_export_mail/__manifest__.py
  sql_export_mail/i18n/fr.po
  sql_export_mail/i18n/sql_export_mail.pot
  sql_export_mail/mail_template.xml
  sql_export_mail/models/sql_export.py
  sql_export_mail/views/sql_export_view.xml
Labels: approved, bot is merging ⏳

#2401 [MIG] module_change_auto_install: Migration to 15.0
  README.md
  module_change_auto_install/README.rst
  module_change_auto_install/__init__.py
  module_change_auto_install/__manifest__.py
  module_change_auto_install/i18n/ca.po
  module_change_auto_install/i18n/module_change_auto_install.pot
  module_change_auto_install/patch.py
  module_change_auto_install/readme/CONFIGURE.rst
  module_change_auto_install/readme/CONTRIBUTORS.rst
  module_change_auto_install/readme/DESCRIPTION.rst
  module_change_auto_install/readme/DEVELOP.rst
  module_change_auto_install/readme/INSTALL.rst
  module_change_auto_install/static/description/icon.png
  module_change_auto_install/static/description/index.html
  setup/module_change_auto_install/odoo/addons/module_change_auto_install
  setup/module_change_auto_install/setup.py
Labels: approved, bot is merging ⏳

#2382 [14.0][FW] scheduler_error_mailer: Forward port fixes from 12.0
  scheduler_error_mailer/__manifest__.py
  scheduler_error_mailer/data/ir_cron_email_tpl.xml
  scheduler_error_mailer/migrations/14.0.1.1.0/post-migration.py
  scheduler_error_mailer/migrations/14.0.1.2.0/post-migration.py
  scheduler_error_mailer/models/ir_cron.py
Labels: approved, ready to merge, bot is merging ⏳

#2368 [ADD] upgrade_analysis: generate noupdate_changes for template tag
  upgrade_analysis/models/upgrade_analysis.py
Labels: bot is merging ⏳

#2415 [14.0][ADD] upgrade_analysis: generate noupdate_changes for template tag
  upgrade_analysis/models/upgrade_analysis.py
Labels: bot is merging ⏳

#2422 [FIX] base_time_dependent_parameter
  base_time_dependent_parameter/__manifest__.py
  base_time_dependent_parameter/models/base.py
  base_time_dependent_parameter/models/base_time_parameter.py
Labels: bot is merging ⏳

#2417 [MIG] upgrade_analysis: Migration to 16.0
  requirements.txt
  setup/upgrade_analysis/odoo/addons/upgrade_analysis
  setup/upgrade_analysis/setup.py
  upgrade_analysis/README.rst
  upgrade_analysis/__init__.py
  upgrade_analysis/__manifest__.py
  upgrade_analysis/blacklist.py
  upgrade_analysis/compare.py
  upgrade_analysis/i18n/es_AR.po
  upgrade_analysis/i18n/fr.po
  upgrade_analysis/i18n/upgrade_analysis.pot
  upgrade_analysis/models/__init__.py
  upgrade_analysis/models/ir_module_module.py
  upgrade_analysis/models/upgrade_analysis.py
  upgrade_analysis/models/upgrade_attribute.py
  upgrade_analysis/models/upgrade_comparison_config.py
  upgrade_analysis/models/upgrade_record.py
  upgrade_analysis/odoo_patch/__init__.py
  upgrade_analysis/odoo_patch/addons/__init__.py
  upgrade_analysis/odoo_patch/addons/mrp/__init__.py
  upgrade_analysis/odoo_patch/addons/point_of_sale/__init__.py
  upgrade_analysis/odoo_patch/addons/stock/__init__.py
  upgrade_analysis/odoo_patch/odoo/__init__.py
  upgrade_analysis/odoo_patch/odoo/addons/__init__.py
  upgrade_analysis/odoo_patch/odoo/addons/base/__init__.py
  upgrade_analysis/odoo_patch/odoo/addons/base/models/__init__.py
  upgrade_analysis/odoo_patch/odoo/addons/base/models/ir_model.py
  upgrade_analysis/odoo_patch/odoo/models.py
  upgrade_analysis/odoo_patch/odoo/modules/__init__.py
  upgrade_analysis/odoo_patch/odoo/modules/registry.py
  upgrade_analysis/odoo_patch/odoo/tools/__init__.py
  upgrade_analysis/odoo_patch/odoo/tools/convert.py
  upgrade_analysis/odoo_patch/odoo_patch.py
  upgrade_analysis/readme/CONTRIBUTORS.rst
  upgrade_analysis/readme/DESCRIPTION.rst
  upgrade_analysis/readme/ROADMAP.rst
  upgrade_analysis/readme/USAGE.rst
  upgrade_analysis/security/ir.model.access.csv
  upgrade_analysis/static/description/icon.png
  upgrade_analysis/static/description/index.html
  upgrade_analysis/static/src/module_coverage_template.rst.mako
  upgrade_analysis/tests/__init__.py
  upgrade_analysis/tests/test_module.py
  upgrade_analysis/upgrade_log.py
  upgrade_analysis/views/menu.xml
  upgrade_analysis/views/view_upgrade_analysis.xml
  upgrade_analysis/views/view_upgrade_comparison_config.xml
  upgrade_analysis/views/view_upgrade_record.xml
  upgrade_analysis/wizards/__init__.py
  upgrade_analysis/wizards/upgrade_generate_record_wizard.py
  upgrade_analysis/wizards/upgrade_install_wizard.py
  upgrade_analysis/wizards/view_upgrade_generate_record_wizard.xml
  upgrade_analysis/wizards/view_upgrade_install_wizard.xml
Labels: migration, bot is merging ⏳

#2432 [15.0][FIX] letsencrypt: workaround blocked domain name example.com
  letsencrypt/tests/test_letsencrypt.py
Labels: bot is merging ⏳

#2416 [15.0][FIX] upgrade_analysis: misleading representation of read/write computed fields
  upgrade_analysis/compare.py
  upgrade_analysis/models/upgrade_record.py
  upgrade_analysis/upgrade_log.py
  upgrade_analysis/wizards/upgrade_install_wizard.py
Labels: bot is merging ⏳

#2433 [14.0][FIX] letsencrypt: workaround blocked domain name example.com
  letsencrypt/tests/test_letsencrypt.py
Labels: bot is merging ⏳

#2431 [14.0][FIX] upgrade_analysis: misleading representation of read/write computed fields
  upgrade_analysis/compare.py
  upgrade_analysis/models/upgrade_record.py
  upgrade_analysis/upgrade_log.py
  upgrade_analysis/wizards/upgrade_install_wizard.py
Labels: bot is merging ⏳

#2344 [MIG] base_remote: Migration to 15.0
  base_remote/README.rst
  base_remote/__init__.py
  base_remote/__manifest__.py
  base_remote/i18n/base_remote.pot
  base_remote/i18n/es.po
  base_remote/i18n/es_AR.po
  base_remote/models/__init__.py
  base_remote/models/base.py
  base_remote/models/res_remote.py
  base_remote/models/res_users.py
  base_remote/readme/CONTRIBUTORS.rst
  base_remote/readme/DESCRIPTION.rst
  base_remote/readme/USAGE.rst
  base_remote/security/ir.model.access.csv
  base_remote/static/description/icon.png
  base_remote/static/description/index.html
  base_remote/tests/__init__.py
  base_remote/tests/test_remote.py
  base_remote/views/res_remote_views.xml
  setup/base_remote/odoo/addons/base_remote
  setup/base_remote/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2437 [15.0][FIX] base_view_inheritance_extension: fix parsing of 'update' operation
  base_view_inheritance_extension/models/ir_ui_view.py
Labels: bug, bot is merging ⏳

#2402 [15.0][MIG] base_technical_user
  base_technical_user/README.rst
  base_technical_user/__init__.py
  base_technical_user/__manifest__.py
  base_technical_user/i18n/ar.po
  base_technical_user/i18n/base_technical_user.pot
  base_technical_user/i18n/de.po
  base_technical_user/i18n/es.po
  base_technical_user/i18n/fr.po
  base_technical_user/i18n/hr.po
  base_technical_user/i18n/it.po
  base_technical_user/i18n/nl_NL.po
  base_technical_user/i18n/pt.po
  base_technical_user/i18n/zh_CN.po
  base_technical_user/models/__init__.py
  base_technical_user/models/models.py
  base_technical_user/models/res_company.py
  base_technical_user/readme/CONTRIBUTORS.rst
  base_technical_user/readme/DESCRIPTION.rst
  base_technical_user/readme/USAGE.rst
  base_technical_user/static/description/icon.png
  base_technical_user/static/description/index.html
  base_technical_user/tests/__init__.py
  base_technical_user/tests/test_sudo_tech.py
  base_technical_user/views/res_company_view.xml
  setup/base_technical_user/odoo/addons/base_technical_user
  setup/base_technical_user/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳

#2413 [MIG] base_m2m_custom_field: Migration to 16.0
  base_m2m_custom_field/README.rst
  base_m2m_custom_field/__init__.py
  base_m2m_custom_field/__manifest__.py
  base_m2m_custom_field/fields.py
  base_m2m_custom_field/i18n/base_m2m_custom_field.pot
  base_m2m_custom_field/readme/CONTRIBUTORS.rst
  base_m2m_custom_field/readme/DESCRIPTION.rst
  base_m2m_custom_field/readme/USAGE.rst
  base_m2m_custom_field/static/description/icon.png
  base_m2m_custom_field/static/description/index.html
  setup/base_m2m_custom_field/odoo/addons/base_m2m_custom_field
  setup/base_m2m_custom_field/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2427 [IMP] base_time_dependent_parameter -> base_time_parameter
  base_time_dependent_parameter/models/base_time_parameter.py
  base_time_dependent_parameter/models/base_time_parameter_value.py
  base_time_parameter/README.rst
  base_time_parameter/__init__.py
  base_time_parameter/__manifest__.py
  base_time_parameter/i18n/base_time_dependent_parameter.pot
  base_time_parameter/models/__init__.py
  base_time_parameter/models/base.py
  base_time_parameter/models/base_time_parameter.py
  base_time_parameter/models/base_time_parameter_value.py
  base_time_parameter/readme/CONTRIBUTORS.rst
  base_time_parameter/readme/DESCRIPTION.rst
  base_time_parameter/readme/USAGE.rst
  base_time_parameter/security/ir.model.access.csv
  base_time_parameter/security/security.xml
  base_time_parameter/static/description/icon.png
  base_time_parameter/static/description/index.html
  base_time_parameter/static/icon.png
  base_time_parameter/views/base_time_parameter_views.xml
  setup/base_time_dependent_parameter/odoo/addons/base_time_dependent_parameter
  setup/base_time_parameter/odoo/addons/base_time_parameter
  setup/base_time_parameter/setup.py
Labels: bot is merging ⏳

#2439 [14.0][IMP] base_time_parameter: LGPL-3; rename model to base.time.parameter.version
  base_time_parameter/__manifest__.py
  base_time_parameter/models/__init__.py
  base_time_parameter/models/base_time_parameter.py
  base_time_parameter/models/base_time_parameter_version.py
  base_time_parameter/security/ir.model.access.csv
  base_time_parameter/security/security.xml
  base_time_parameter/views/base_time_parameter_views.xml
Labels: bot is merging ⏳

#2440 [14.0][FIX] base_time_parameter: Beta status
  base_time_parameter/__manifest__.py
Labels: bot is merging ⏳

#2428 Migrate Sentry to 15.0
  requirements.txt
  sentry/README.rst
  sentry/__init__.py
  sentry/__manifest__.py
  sentry/const.py
  sentry/generalutils.py
  sentry/hooks.py
  sentry/i18n/ca.po
  sentry/i18n/sentry.pot
  sentry/i18n/zh_CN.po
  sentry/logutils.py
  sentry/processor.py
  sentry/readme/CONFIGURE.rst
  sentry/readme/CONTRIBUTORS.rst
  sentry/readme/CREDITS.rst
  sentry/readme/DESCRIPTION.rst
  sentry/readme/INSTALL.rst
  sentry/readme/ROADMAP.rst
  sentry/readme/USAGE.rst
  sentry/static/description/icon.png
  sentry/static/description/index.html
  sentry/tests/__init__.py
  sentry/tests/test_client.py
  sentry/tests/test_logutils.py
  setup/sentry/odoo/addons/sentry
  setup/sentry/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2442 [14.0][FIX] base_time_parameter: added tests, fixed errors
  base_time_parameter/__init__.py
  base_time_parameter/models/base.py
  base_time_parameter/models/base_time_parameter.py
  base_time_parameter/models/base_time_parameter_version.py
  base_time_parameter/tests/__init__.py
  base_time_parameter/tests/test_time_parameter.py
Labels: bot is merging ⏳
