Repository OCA/server-tools, pull requests merged in 2022-07, with the labels that each got.

#2364 [ADD] base_time_dependent_parameter
  base_time_dependent_parameter/__init__.py
  base_time_dependent_parameter/__manifest__.py
  base_time_dependent_parameter/models/__init__.py
  base_time_dependent_parameter/models/base.py
  base_time_dependent_parameter/models/base_time_parameter.py
  base_time_dependent_parameter/models/base_time_parameter_value.py
  base_time_dependent_parameter/readme/CONTRIBUTORS.rst
  base_time_dependent_parameter/readme/DESCRIPTION.rst
  base_time_dependent_parameter/readme/USAGE.rst
  base_time_dependent_parameter/security/ir.model.access.csv
  base_time_dependent_parameter/security/security.xml
  base_time_dependent_parameter/static/icon.png
  base_time_dependent_parameter/views/base_time_parameter_views.xml
  setup/base_time_dependent_parameter/odoo/addons/base_time_dependent_parameter
  setup/base_time_dependent_parameter/setup.py
Labels: bot is merging ⏳

#2370 [15.0] [MIG] base_time_window
  base_time_window/README.rst
  base_time_window/__init__.py
  base_time_window/__manifest__.py
  base_time_window/data/time_weekday.xml
  base_time_window/i18n/base_time_window.pot
  base_time_window/models/__init__.py
  base_time_window/models/time_weekday.py
  base_time_window/models/time_window_mixin.py
  base_time_window/readme/CONTRIBUTORS.rst
  base_time_window/readme/CREDITS.rst
  base_time_window/readme/DESCRIPTION.rst
  base_time_window/readme/ROADMAP.rst
  base_time_window/readme/USAGE.rst
  base_time_window/security/ir.model.access.xml
  base_time_window/static/description/icon.png
  base_time_window/static/description/index.html
  setup/base_time_window/odoo/addons/base_time_window
  setup/base_time_window/setup.py
Labels: approved, bot is merging ⏳

#2363 [12.0][ADD] auditlog: blacklist password fields
  auditlog/__manifest__.py
  auditlog/migrations/12.0.2.0.0/pre-migration.py
  auditlog/models/rule.py
  auditlog/readme/CONFIGURE.rst
Labels: approved, ready to merge, bot is merging ⏳

#2377 [15][FW] Keep computed editable field value when playing onchanges
  onchange_helper/models/base.py
Labels: approved, bot is merging ⏳
