Repository OCA/server-tools, pull requests merged in 2023-12, with the labels that each got.

#2631 [15.0][MIG] base_time_parameter
  base_time_parameter/README.rst
  base_time_parameter/__init__.py
  base_time_parameter/__manifest__.py
  base_time_parameter/i18n/base_time_dependent_parameter.pot
  base_time_parameter/i18n/base_time_parameter.pot
  base_time_parameter/i18n/pt.po
  base_time_parameter/models/__init__.py
  base_time_parameter/models/base.py
  base_time_parameter/models/base_time_parameter.py
  base_time_parameter/models/base_time_parameter_version.py
  base_time_parameter/readme/CONFIGURE.rst
  base_time_parameter/readme/CONTRIBUTORS.rst
  base_time_parameter/readme/DESCRIPTION.rst
  base_time_parameter/readme/USAGE.rst
  base_time_parameter/security/ir.model.access.csv
  base_time_parameter/security/security.xml
  base_time_parameter/static/description/icon.png
  base_time_parameter/static/description/index.html
  base_time_parameter/static/icon.png
  base_time_parameter/tests/__init__.py
  base_time_parameter/tests/test_time_parameter.py
  base_time_parameter/views/base_time_parameter_version_views.xml
  base_time_parameter/views/base_time_parameter_views.xml
  setup/base_time_parameter/odoo/addons/base_time_parameter
  setup/base_time_parameter/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2767 [14.0][FIX] base_technical_user - Error message when no technical user
  base_technical_user/models/models.py
  base_technical_user/tests/test_sudo_tech.py
Labels: approved, ready to merge, bot is merging ⏳

#2709 [16.0][IMP] base_view_inheritance_extension: missing commits from v15
  base_view_inheritance_extension/README.rst
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/readme/CONTRIBUTORS.rst
  base_view_inheritance_extension/readme/USAGE.rst
  base_view_inheritance_extension/static/description/index.html
Labels: approved, bot is merging ⏳

#2779 [IMP] model_read_only: added model description
  model_read_only/models/models.py
Labels: bot is merging ⏳

#2777 [17.0] [MIG] module_change_auto_install: Migration to 17.0
  module_change_auto_install/README.rst
  module_change_auto_install/__init__.py
  module_change_auto_install/__manifest__.py
  module_change_auto_install/i18n/ca.po
  module_change_auto_install/i18n/fr.po
  module_change_auto_install/i18n/module_change_auto_install.pot
  module_change_auto_install/patch.py
  module_change_auto_install/pyproject.toml
  module_change_auto_install/readme/CONFIGURE.md
  module_change_auto_install/readme/CONTRIBUTORS.md
  module_change_auto_install/readme/DESCRIPTION.md
  module_change_auto_install/readme/DEVELOP.md
  module_change_auto_install/readme/INSTALL.md
  module_change_auto_install/static/description/icon.png
  module_change_auto_install/static/description/index.html
  module_change_auto_install/tests/__init__.py
  module_change_auto_install/tests/test_module.py
Labels: approved, bot is merging ⏳

#2770 [IMP] base_sequence_default: better readme
  base_sequence_default/README.rst
  base_sequence_default/readme/CONFIGURE.md
  base_sequence_default/readme/DESCRIPTION.md
  base_sequence_default/readme/USAGE.md
  base_sequence_default/static/description/index.html
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#2775 [ADD] views_migration_17: module to migrate views
  .pre-commit-config.yaml
  views_migration_17/README.rst
  views_migration_17/__init__.py
  views_migration_17/__manifest__.py
  views_migration_17/patch_xml_import.py
  views_migration_17/readme/CONTRIBUTORS.rst
  views_migration_17/readme/DESCRIPTION.rst
  views_migration_17/readme/USAGE.rst
Labels: bot is merging ⏳

#2648 [15.0][FIX] database_cleanup: preserve spaces in quoted identifiers
  database_cleanup/identifier_adapter.py
  database_cleanup/tests/__init__.py
  database_cleanup/tests/test_identifier_adapter.py
Labels: approved, bot is merging ⏳

#2771 [16.0][IMP] excel_import_export: Set import wizard filename
  excel_import_export/wizard/import_xlsx_wizard.py
  excel_import_export/wizard/import_xlsx_wizard.xml
Labels: approved, ready to merge, bot is merging ⏳

#2790 IMP attachment_queue: allow to add activity
  attachment_queue/models/attachment_queue.py
  attachment_queue/views/attachment_queue_view.xml
Labels: approved, ready to merge, bot is merging ⏳
