Repository OCA/server-tools, pull requests merged in 2023-06, with the labels that each got.

#2636 [15.0][IMP] base_view_inheritance_extension: Add new options domain_add and text_add
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/readme/CONTRIBUTORS.rst
  base_view_inheritance_extension/readme/USAGE.rst
Labels: approved, bot is merging ⏳

#2647 [14.0][FIX] letsencrypt: PYOpenSSL 23.2.0 rejects invalid X509 version 2 set by acme
  letsencrypt/__manifest__.py
  requirements.txt
Labels: bot is merging ⏳

#2645 [14.0][FIX] database_cleanup: preserve spaces in quoted identifiers
  database_cleanup/identifier_adapter.py
  database_cleanup/tests/__init__.py
  database_cleanup/tests/test_identifier_adapter.py
Labels: approved, bot is merging ⏳

#2638 [FIX] sentry: downgrade sentry-sdk to compatible version
  requirements.txt
  sentry/__manifest__.py
  sentry/const.py
Labels: approved, bot is merging ⏳

#2649 [FIX] sentry: downgrade sentry-sdk to compatible version
  requirements.txt
  sentry/__manifest__.py
  sentry/const.py
Labels: approved, bot is merging ⏳

#2652 [15.0][FIX] *: remove lxml, cryptography from python depends
  html_image_url_extractor/__manifest__.py
  html_text/__manifest__.py
  letsencrypt/__manifest__.py
  requirements.txt
Labels: approved, bot is merging ⏳

#2646 [16.0][FIX] attachment_queue: adapt tests to fixed trap jobs helper
  attachment_queue/tests/test_attachment_queue.py
Labels: approved, bot is merging ⏳

#2602 [16.0][MIG] scheduler_error_mailer
  scheduler_error_mailer/README.rst
  scheduler_error_mailer/__init__.py
  scheduler_error_mailer/__manifest__.py
  scheduler_error_mailer/data/ir_cron_email_tpl.xml
  scheduler_error_mailer/demo/ir_cron_demo.xml
  scheduler_error_mailer/hooks.py
  scheduler_error_mailer/i18n/de.po
  scheduler_error_mailer/i18n/es.po
  scheduler_error_mailer/i18n/es_AR.po
  scheduler_error_mailer/i18n/fr.po
  scheduler_error_mailer/i18n/hr.po
  scheduler_error_mailer/i18n/pt.po
  scheduler_error_mailer/i18n/pt_BR.po
  scheduler_error_mailer/i18n/scheduler_error_mailer.pot
  scheduler_error_mailer/i18n/sl.po
  scheduler_error_mailer/i18n/zh_CN.po
  scheduler_error_mailer/images/scheduler_error_mailer.jpg
  scheduler_error_mailer/models/__init__.py
  scheduler_error_mailer/models/ir_cron.py
  scheduler_error_mailer/readme/CONFIGURE.rst
  scheduler_error_mailer/readme/CONTRIBUTORS.rst
  scheduler_error_mailer/readme/DESCRIPTION.rst
  scheduler_error_mailer/static/description/icon.png
  scheduler_error_mailer/static/description/index.html
  scheduler_error_mailer/tests/__init__.py
  scheduler_error_mailer/tests/test_scheduler_error_mailer.py
  scheduler_error_mailer/views/ir_cron.xml
  setup/scheduler_error_mailer/odoo/addons/scheduler_error_mailer
  setup/scheduler_error_mailer/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2639 [13.0][FIX] auditlog: autovacuum performance
  auditlog/models/http_request.py
  auditlog/models/log.py
Labels: approved, bot is merging ⏳

#2557 [13.0][IMP] base_view_inheritance_extension: Add new options domain_add and text_add
  base_view_inheritance_extension/README.rst
  base_view_inheritance_extension/demo/ir_ui_view.xml
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/readme/CONTRIBUTORS.rst
  base_view_inheritance_extension/readme/USAGE.rst
  base_view_inheritance_extension/static/description/index.html
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
Labels: approved, bot is merging ⏳

#2521 [14.0][IMP] base_time_parameter: type reference -> type record
  base_time_parameter/__manifest__.py
  base_time_parameter/migrations/14.0.4.0.0/pre-migration.py
  base_time_parameter/models/base_time_parameter.py
  base_time_parameter/views/base_time_parameter_version_views.xml
  base_time_parameter/views/base_time_parameter_views.xml
Labels: bot is merging ⏳

#2653 [UPD] onchange_helper - AGPL to LGPL
  onchange_helper/__init__.py
  onchange_helper/__manifest__.py
  onchange_helper/models/__init__.py
  onchange_helper/models/base.py
  onchange_helper/tests/__init__.py
  onchange_helper/tests/test_onchange_helper.py
Labels: bot is merging ⏳

#2637 [14.0][FIX] configuration_helper after change in odoo core
  configuration_helper/models/config.py
Labels: approved, bot is merging ⏳

#2659 [14.0] sentry: add optin to not send startup event to Sentry
  sentry/README.rst
  sentry/hooks.py
  sentry/readme/CONFIGURE.rst
  sentry/tests/test_client.py
Labels: approved, ready to merge, bot is merging ⏳

#2620 [15.0][MIG] base_model_restrict_update
  base_model_restrict_update/README.rst
  base_model_restrict_update/__init__.py
  base_model_restrict_update/__manifest__.py
  base_model_restrict_update/i18n/base_model_restrict_update.po
  base_model_restrict_update/i18n/base_model_restrict_update.pot
  base_model_restrict_update/i18n/es_AR.po
  base_model_restrict_update/i18n/ja_JP.po
  base_model_restrict_update/models/__init__.py
  base_model_restrict_update/models/ir_model.py
  base_model_restrict_update/models/ir_model_access.py
  base_model_restrict_update/models/res_users.py
  base_model_restrict_update/readme/CONFIGURE.rst
  base_model_restrict_update/readme/CONTRIBUTORS.rst
  base_model_restrict_update/readme/CREDITS.rst
  base_model_restrict_update/readme/DESCRIPTION.rst
  base_model_restrict_update/static/description/icon.png
  base_model_restrict_update/static/description/index.html
  base_model_restrict_update/tests/__init__.py
  base_model_restrict_update/tests/test_base_model_restrict_update.py
  base_model_restrict_update/views/ir_model_views.xml
  base_model_restrict_update/views/res_users_views.xml
  setup/base_model_restrict_update/odoo/addons/base_model_restrict_update
  setup/base_model_restrict_update/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2592 [16.0][MIG] base_domain_inverse_function: Migrate to version 16.0
  base_domain_inverse_function/README.rst
  base_domain_inverse_function/__init__.py
  base_domain_inverse_function/__manifest__.py
  base_domain_inverse_function/inverse_expression.py
  base_domain_inverse_function/readme/CONTRIBUTORS.rst
  base_domain_inverse_function/readme/CREDITS.rst
  base_domain_inverse_function/readme/DESCRIPTION.rst
  base_domain_inverse_function/readme/ROADMAP.rst
  base_domain_inverse_function/readme/USAGE.rst
  base_domain_inverse_function/static/description/index.html
  base_domain_inverse_function/tests/__init__.py
  base_domain_inverse_function/tests/test_inverse_function.py
  base_domain_inverse_function/tests/test_partner_domains.py
  setup/base_domain_inverse_function/odoo/addons/base_domain_inverse_function
  setup/base_domain_inverse_function/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2665 [IMP] base_future_response: add test
  base_future_response/tests/__init__.py
  base_future_response/tests/test_future_response.py
Labels: bot is merging ⏳

#2666 [14.0][ADD] base_contextvars
  base_contextvars/README.rst
  base_contextvars/__init__.py
  base_contextvars/__manifest__.py
  base_contextvars/contextvars_patch.py
  base_contextvars/readme/DESCRIPTION.rst
  base_contextvars/tests/__init__.py
  base_contextvars/tests/test_contextvars.py
  requirements.txt
  setup/base_contextvars/odoo/addons/base_contextvars
  setup/base_contextvars/setup.py
Labels: bot is merging ⏳

#2667 [14.0][IMP] base_contextvars: minor tweaks
  base_contextvars/contextvars_patch.py
Labels: bot is merging ⏳
