Repository OCA/server-tools, pull requests merged in 2023-04, with the labels that each got.

#2603 [REF] base_sequence_default: bump sequence only on creation
  base_sequence_default/__manifest__.py
  base_sequence_default/models/base.py
  base_sequence_default/readme/USAGE.rst
  base_sequence_default/tests/test_project_project.py
Labels: bot is merging ⏳

#2543 [16.0][MIG] module_auto_update
  module_auto_update/README.rst
  module_auto_update/__init__.py
  module_auto_update/__manifest__.py
  module_auto_update/addon_hash.py
  module_auto_update/hooks.py
  module_auto_update/i18n/ca.po
  module_auto_update/i18n/cs_CZ.po
  module_auto_update/i18n/de.po
  module_auto_update/i18n/es.po
  module_auto_update/i18n/es_AR.po
  module_auto_update/i18n/es_MX.po
  module_auto_update/i18n/fr.po
  module_auto_update/i18n/hr.po
  module_auto_update/i18n/it.po
  module_auto_update/i18n/module_auto_update.pot
  module_auto_update/i18n/nl_NL.po
  module_auto_update/i18n/pt_BR.po
  module_auto_update/i18n/sl.po
  module_auto_update/i18n/tr.po
  module_auto_update/i18n/zh_CN.po
  module_auto_update/models/__init__.py
  module_auto_update/models/module.py
  module_auto_update/readme/CONFIGURE.rst
  module_auto_update/readme/CONTRIBUTORS.rst
  module_auto_update/readme/DESCRIPTION.rst
  module_auto_update/readme/USAGE.rst
  module_auto_update/static/description/icon.png
  module_auto_update/static/description/index.html
  module_auto_update/tests/__init__.py
  module_auto_update/tests/sample_module/README.rst
  module_auto_update/tests/sample_module/data/f1.xml
  module_auto_update/tests/sample_module/data/f2.xml
  module_auto_update/tests/sample_module/i18n/en_US.po
  module_auto_update/tests/sample_module/i18n/fr.po
  module_auto_update/tests/sample_module/i18n/fr_BE.po
  module_auto_update/tests/sample_module/i18n/test.pot
  module_auto_update/tests/sample_module/i18n_extra/en.po
  module_auto_update/tests/sample_module/i18n_extra/fr.po
  module_auto_update/tests/sample_module/i18n_extra/nl_NL.po
  module_auto_update/tests/sample_module/models/stuff.py
  module_auto_update/tests/sample_module/models/stuff.pyc
  module_auto_update/tests/sample_module/models/stuff.pyo
  module_auto_update/tests/sample_module/static/src/some.js
  module_auto_update/tests/test_addon_hash.py
  module_auto_update/tests/test_module.py
  module_auto_update/views/ir_module_module.xml
  setup/module_auto_update/odoo/addons/module_auto_update
  setup/module_auto_update/setup.py
Labels: approved, ready to merge

#2591 [13.0][FIX] auditlog: Allow passing a chunk size for autovacuum
  auditlog/models/autovacuum.py
  auditlog/readme/CONFIGURE.rst
Labels: approved, ready to merge, bot is merging ⏳

#2595 [15.0][FIX] database_cleanup: 'Environment' object has no attribute 'invalidate_all'
  database_cleanup/models/purge_modules.py
Labels: bot is merging ⏳

#2350 [14.0 jsonifier: allow json_key override by resolver
  jsonifier/exceptions.py
  jsonifier/models/ir_exports_resolver.py
  jsonifier/models/models.py
  jsonifier/tests/test_get_parser.py
Labels: bot is merging ⏳
