Repository OCA/server-tools, pull requests merged in 2023-02, with the labels that each got.

#2552 [14.0][FIX] attachment_delete_restrict: adapt to Odoo permission change
  attachment_delete_restrict/tests/test_attachment_delete_restrict.py
Labels: approved, bot is merging ⏳

#2551 [14.0][FIX] attachment_synchronize & nsca_client: fix read
  attachment_synchronize/models/storage_backend.py
  nsca_client/models/nsca_server.py
Labels: approved, bot is merging ⏳

#2553 [15.0][MIG] scheduler_error_mailer: Migration to version 15.0
  scheduler_error_mailer/README.rst
  scheduler_error_mailer/__init__.py
  scheduler_error_mailer/__manifest__.py
  scheduler_error_mailer/data/ir_cron_email_tpl.xml
  scheduler_error_mailer/demo/ir_cron_demo.xml
  scheduler_error_mailer/i18n/de.po
  scheduler_error_mailer/i18n/es.po
  scheduler_error_mailer/i18n/es_AR.po
  scheduler_error_mailer/i18n/fr.po
  scheduler_error_mailer/i18n/hr.po
  scheduler_error_mailer/i18n/pt.po
  scheduler_error_mailer/i18n/pt_BR.po
  scheduler_error_mailer/i18n/scheduler_error_mailer.pot
  scheduler_error_mailer/i18n/sl.po
  scheduler_error_mailer/i18n/zh_CN.po
  scheduler_error_mailer/images/scheduler_error_mailer.jpg
  scheduler_error_mailer/models/__init__.py
  scheduler_error_mailer/models/ir_cron.py
  scheduler_error_mailer/readme/CONFIGURE.rst
  scheduler_error_mailer/readme/CONTRIBUTORS.rst
  scheduler_error_mailer/readme/DESCRIPTION.rst
  scheduler_error_mailer/static/description/icon.png
  scheduler_error_mailer/static/description/index.html
  scheduler_error_mailer/views/ir_cron.xml
  setup/scheduler_error_mailer/odoo/addons/scheduler_error_mailer
  setup/scheduler_error_mailer/setup.py
Labels: approved, bot is merging ⏳

#2550 [16.0] session_db: gevent and thread support
  session_db/pg_session_store.py
Labels: bot is merging ⏳

#2498 [14.0][MIG] session_db from 13.0
  session_db/__init__.py
  session_db/__manifest__.py
  session_db/pg_session_store.py
  session_db/readme/DESCRIPTION.rst
  session_db/readme/ROADMAP.rst
  session_db/readme/USAGE.rst
  setup/session_db/odoo/addons/session_db
  setup/session_db/setup.py
Labels: needs review, bot is merging ⏳

#2443 [13.0] session_db
  session_db/__init__.py
  session_db/__manifest__.py
  session_db/pg_session_store.py
  session_db/readme/DESCRIPTION.rst
  session_db/readme/ROADMAP.rst
  session_db/readme/USAGE.rst
  setup/session_db/odoo/addons/session_db
  setup/session_db/setup.py
Labels: needs review, bot is merging ⏳

#2479 [16.0][MIG] onchange_helper: Migration to 16.0
  onchange_helper/README.rst
  onchange_helper/__init__.py
  onchange_helper/__manifest__.py
  onchange_helper/i18n/cs_CZ.po
  onchange_helper/i18n/de.po
  onchange_helper/i18n/es.po
  onchange_helper/i18n/es_AR.po
  onchange_helper/i18n/fr.po
  onchange_helper/i18n/hr.po
  onchange_helper/i18n/onchange_helper.pot
  onchange_helper/i18n/sl.po
  onchange_helper/i18n/zh_CN.po
  onchange_helper/models/__init__.py
  onchange_helper/models/base.py
  onchange_helper/readme/CONTRIBUTORS.rst
  onchange_helper/readme/DESCRIPTION.rst
  onchange_helper/readme/ROADMAP.rst
  onchange_helper/readme/USAGE.rst
  onchange_helper/static/description/icon.png
  onchange_helper/static/description/index.html
  onchange_helper/tests/__init__.py
  onchange_helper/tests/test_onchange_helper.py
  setup/onchange_helper/odoo/addons/onchange_helper
  setup/onchange_helper/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2418 [16.0][MIG] jsonifier
  jsonifier/README.rst
  jsonifier/__init__.py
  jsonifier/__manifest__.py
  jsonifier/demo/export_demo.xml
  jsonifier/demo/ir.exports.line.csv
  jsonifier/demo/resolver_demo.xml
  jsonifier/i18n/ca.po
  jsonifier/i18n/jsonifier.pot
  jsonifier/i18n/zh_CN.po
  jsonifier/models/__init__.py
  jsonifier/models/ir_exports.py
  jsonifier/models/ir_exports_line.py
  jsonifier/models/ir_exports_resolver.py
  jsonifier/models/models.py
  jsonifier/models/utils.py
  jsonifier/readme/CONTRIBUTORS.rst
  jsonifier/readme/DESCRIPTION.rst
  jsonifier/security/ir.model.access.csv
  jsonifier/static/description/icon.png
  jsonifier/static/description/index.html
  jsonifier/tests/__init__.py
  jsonifier/tests/test_get_parser.py
  jsonifier/tests/test_helpers.py
  jsonifier/tests/test_ir_exports_line.py
  jsonifier/views/ir_exports_resolver_view.xml
  jsonifier/views/ir_exports_view.xml
  setup/jsonifier/odoo/addons/jsonifier
  setup/jsonifier/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳
