Repository OCA/server-tools, pull requests merged in 2023-03, with the labels that each got.

#2563 [MIG] attachment_unindex_content: Migration to 16.0
  attachment_unindex_content/README.rst
  attachment_unindex_content/__init__.py
  attachment_unindex_content/__manifest__.py
  attachment_unindex_content/hooks.py
  attachment_unindex_content/i18n/attachment_unindex_content.pot
  attachment_unindex_content/i18n/ca.po
  attachment_unindex_content/i18n/es_AR.po
  attachment_unindex_content/models/__init__.py
  attachment_unindex_content/models/ir_attachment.py
  attachment_unindex_content/readme/CONTRIBUTORS.rst
  attachment_unindex_content/readme/DESCRIPTION.rst
  attachment_unindex_content/static/description/icon.png
  attachment_unindex_content/static/description/index.html
  setup/attachment_unindex_content/odoo/addons/attachment_unindex_content
  setup/attachment_unindex_content/setup.py
Labels: approved, bot is merging ⏳

#2575 [14.0] Update pre-commit conf
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: needs review

#2576 [14.0] rpc_helper: fix readme
  rpc_helper/readme/CONFIGURE.rst
Labels: bot is merging ⏳

#2571 [ADD] url_attachment_search_fuzzy
  setup/url_attachment_search_fuzzy/odoo/addons/url_attachment_search_fuzzy
  setup/url_attachment_search_fuzzy/setup.py
  url_attachment_search_fuzzy/__manifest__.py
  url_attachment_search_fuzzy/data/url_attachment_index.xml
  url_attachment_search_fuzzy/readme/CONFIGURE.rst
  url_attachment_search_fuzzy/readme/CONTRIBUTORS.rst
  url_attachment_search_fuzzy/readme/DESCRIPTION.rst
  url_attachment_search_fuzzy/readme/INSTALL.rst
Labels: approved, bot is merging ⏳

#2434 [14.0][ADD] tracking_manager
  setup/tracking_manager/odoo/addons/tracking_manager
  setup/tracking_manager/setup.py
  tracking_manager/__init__.py
  tracking_manager/__manifest__.py
  tracking_manager/i18n/fr.po
  tracking_manager/models/__init__.py
  tracking_manager/models/ir_model.py
  tracking_manager/models/mail_thread.py
  tracking_manager/models/mail_tracking_value.py
  tracking_manager/models/models.py
  tracking_manager/readme/CONTRIBUTORS.rst
  tracking_manager/readme/DESCRIPTION.rst
  tracking_manager/readme/USAGE.rst
  tracking_manager/static/description/fields.png
  tracking_manager/static/description/model_view.png
  tracking_manager/tests/__init__.py
  tracking_manager/tests/models.py
  tracking_manager/tests/test_tracking_manager.py
  tracking_manager/tools.py
  tracking_manager/views/ir_model.xml
  tracking_manager/views/ir_model_fields.xml
  tracking_manager/views/message_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#2583 [15.0][FIX] fetchmail_notify_error_to_sender: jinja -> qweb
  fetchmail_notify_error_to_sender/__manifest__.py
  fetchmail_notify_error_to_sender/data/email_template_data.xml
  fetchmail_notify_error_to_sender/migrations/15.0.1.0.1/noupdate_changes.xml
  fetchmail_notify_error_to_sender/migrations/15.0.1.0.1/post-migration.py
Labels: bot is merging ⏳

#2586 [FIX] sentry: change with_locals to include_local_variables variable
  requirements.txt
  sentry/__manifest__.py
  sentry/const.py
Labels: approved, bot is merging ⏳

#2588 [FIX] sentry: change with_locals to include_local_variables variable
  requirements.txt
  sentry/__manifest__.py
  sentry/const.py
Labels: bot is merging ⏳

#2587 [FIX] sentry: change with_locals to include_local_variables variable
  requirements.txt
  sentry/__manifest__.py
  sentry/const.py
Labels: bot is merging ⏳

#2593 [13.0] session_db: reconnect if needed
  session_db/pg_session_store.py
  session_db/tests/__init__.py
  session_db/tests/test_pg_session_store.py
Labels: bot is merging ⏳

#2598 [ADD] base_sequence_default: add default values with sequences
  base_sequence_default/README.rst
  base_sequence_default/__init__.py
  base_sequence_default/__manifest__.py
  base_sequence_default/demo/ir_sequence_demo.xml
  base_sequence_default/models/__init__.py
  base_sequence_default/models/base.py
  base_sequence_default/readme/CONFIGURE.rst
  base_sequence_default/readme/CONTRIBUTORS.rst
  base_sequence_default/readme/DESCRIPTION.rst
  base_sequence_default/readme/USAGE.rst
  base_sequence_default/static/description/icon.png
  base_sequence_default/tests/__init__.py
  base_sequence_default/tests/test_project_project.py
  setup/base_sequence_default/odoo/addons/base_sequence_default
  setup/base_sequence_default/setup.py
Labels: enhancement, needs review, approved, bot is merging ⏳
