Repository OCA/server-tools, pull requests merged in 2023-10, with the labels that each got.

#2661 [16][IMP] Add index on attachment_queue
  attachment_queue/models/attachment_queue.py
Labels: approved, bot is merging ⏳

#2722 [13.0][BKP] url_attachment_search_fuzzy
  setup/url_attachment_search_fuzzy/odoo/addons/url_attachment_search_fuzzy
  setup/url_attachment_search_fuzzy/setup.py
  url_attachment_search_fuzzy/README.rst
  url_attachment_search_fuzzy/__manifest__.py
  url_attachment_search_fuzzy/data/url_attachment_index.xml
  url_attachment_search_fuzzy/readme/CONFIGURE.rst
  url_attachment_search_fuzzy/readme/CONTRIBUTORS.rst
  url_attachment_search_fuzzy/readme/DESCRIPTION.rst
  url_attachment_search_fuzzy/readme/INSTALL.rst
  url_attachment_search_fuzzy/static/description/icon.png
  url_attachment_search_fuzzy/static/description/index.html
Labels: approved, bot is merging ⏳

#2723 [14.0][FIX] base_kanban_stage: `image_small` -> `image_128`
  base_kanban_stage/views/base_kanban_abstract.xml
Labels: bot is merging ⏳

#2727 [15.0][FIX] base_kanban_stage: `image_128` -> `avatar_128`
  base_kanban_stage/views/base_kanban_abstract.xml
Labels: bot is merging ⏳

#2693 [15.0][MIG] base_kanban_stage_state
  base_kanban_stage_state/README.rst
  base_kanban_stage_state/__init__.py
  base_kanban_stage_state/__manifest__.py
  base_kanban_stage_state/i18n/base_kanban_stage_state.pot
  base_kanban_stage_state/i18n/ca.po
  base_kanban_stage_state/i18n/cs.po
  base_kanban_stage_state/i18n/da.po
  base_kanban_stage_state/i18n/de.po
  base_kanban_stage_state/i18n/es.po
  base_kanban_stage_state/i18n/es_ES.po
  base_kanban_stage_state/i18n/es_MX.po
  base_kanban_stage_state/i18n/es_VE.po
  base_kanban_stage_state/i18n/fi.po
  base_kanban_stage_state/i18n/fr.po
  base_kanban_stage_state/i18n/fr_CH.po
  base_kanban_stage_state/i18n/gl.po
  base_kanban_stage_state/i18n/hr.po
  base_kanban_stage_state/i18n/hr_HR.po
  base_kanban_stage_state/i18n/hu.po
  base_kanban_stage_state/i18n/it.po
  base_kanban_stage_state/i18n/nb.po
  base_kanban_stage_state/i18n/nb_NO.po
  base_kanban_stage_state/i18n/nl.po
  base_kanban_stage_state/i18n/pl.po
  base_kanban_stage_state/i18n/pt.po
  base_kanban_stage_state/i18n/pt_BR.po
  base_kanban_stage_state/i18n/pt_PT.po
  base_kanban_stage_state/i18n/ro.po
  base_kanban_stage_state/i18n/sl.po
  base_kanban_stage_state/i18n/sv.po
  base_kanban_stage_state/i18n/tr.po
  base_kanban_stage_state/i18n/tr_TR.po
  base_kanban_stage_state/i18n/zh_CN.po
  base_kanban_stage_state/models/__init__.py
  base_kanban_stage_state/models/base_kanban_stage.py
  base_kanban_stage_state/readme/CONTRIBUTORS.rst
  base_kanban_stage_state/readme/DESCRIPTION.rst
  base_kanban_stage_state/static/description/icon.png
  base_kanban_stage_state/static/description/index.html
  base_kanban_stage_state/tests/__init__.py
  base_kanban_stage_state/tests/test_base_kanban_stage.py
  base_kanban_stage_state/views/base_kanban_stage_state_view.xml
  setup/base_kanban_stage_state/odoo/addons/base_kanban_stage_state
  setup/base_kanban_stage_state/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2726 [16][FIX] attachment_queue : fix empty job description
  attachment_queue/models/attachment_queue.py
Labels: approved, ready to merge, bot is merging ⏳

#2489 [IMP] 14.0 base_generate_code allow to manually set code
  base_generate_code/__manifest__.py
  base_generate_code/models/code_format_mixin.py
Labels: approved, ready to merge, bot is merging ⏳

#2741 [15.0][IMP] server-tools : test performance improvement
  base_exception/tests/test_base_exception.py
  base_search_fuzzy/tests/test_query_generation.py
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
Labels: bot is merging ⏳

#2745 [15.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  base_model_restrict_update/i18n/base_model_restrict_update.pot
  base_model_restrict_update/models/ir_model_access.py
Labels: help wanted, needs review, bot is merging ⏳
