Repository OCA/server-tools, pull requests merged in 2023-11, with the labels that each got.

#2740 [FIX] base_fontawesome: fixed replace files to show icons in website
  base_fontawesome/__manifest__.py
  base_fontawesome/static/lib/fontawesome-5.15.4/css/all.css
  base_fontawesome/static/src/css/fontawesome.css
Labels: approved, ready to merge, bot is merging ⏳

#2564 [14.0][FIX] excel_import_export, make new xml_id not deletable on update process
  excel_import_export/models/xlsx_import.py
Labels: approved, ready to merge, bot is merging ⏳

#2590 [16.0][mig] html_text: Migration to 16.0
  html_text/README.rst
  html_text/__init__.py
  html_text/__manifest__.py
  html_text/i18n/ca.po
  html_text/i18n/de.po
  html_text/i18n/es.po
  html_text/i18n/es_AR.po
  html_text/i18n/es_ES.po
  html_text/i18n/hr.po
  html_text/i18n/html_text.pot
  html_text/i18n/it.po
  html_text/i18n/tr.po
  html_text/i18n/zh_CN.po
  html_text/models/__init__.py
  html_text/models/ir_fields_converter.py
  html_text/readme/CONTRIBUTORS.rst
  html_text/readme/DESCRIPTION.rst
  html_text/readme/ROADMAP.rst
  html_text/readme/USAGE.rst
  html_text/static/description/icon.png
  html_text/static/description/index.html
  html_text/tests/__init__.py
  html_text/tests/test_extractor.py
  requirements.txt
  setup/html_text/odoo/addons/html_text
  setup/html_text/setup.py
Labels: approved, bot is merging ⏳

#2275 [15.0][MIG] base_sequence_option
  base_sequence_option/README.rst
  base_sequence_option/__init__.py
  base_sequence_option/__manifest__.py
  base_sequence_option/i18n/base_sequence_option.pot
  base_sequence_option/models/__init__.py
  base_sequence_option/models/ir_sequence.py
  base_sequence_option/models/ir_sequence_option.py
  base_sequence_option/readme/CONTRIBUTORS.rst
  base_sequence_option/readme/DESCRIPTION.rst
  base_sequence_option/readme/USAGE.rst
  base_sequence_option/security/ir.model.access.csv
  base_sequence_option/security/sequence_option_security.xml
  base_sequence_option/static/description/icon.png
  base_sequence_option/static/description/index.html
  base_sequence_option/tests/__init__.py
  base_sequence_option/tests/base_sequence_tester.py
  base_sequence_option/tests/common.py
  base_sequence_option/tests/test_ir_sequence_option.py
  base_sequence_option/views/sequence_option_view.xml
  requirements.txt
  setup/base_sequence_option/odoo/addons/base_sequence_option
  setup/base_sequence_option/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2668 [ADD] With_fieldname parameter in jsonifier
  jsonifier/models/models.py
  jsonifier/readme/USAGE.rst
  jsonifier/tests/test_get_parser.py
Labels: approved, ready to merge, bot is merging ⏳

#2751 [16.0][MIG] base_sequence_option: Migration to 16.0
  base_sequence_option/README.rst
  base_sequence_option/__init__.py
  base_sequence_option/__manifest__.py
  base_sequence_option/i18n/base_sequence_option.pot
  base_sequence_option/models/__init__.py
  base_sequence_option/models/ir_sequence.py
  base_sequence_option/models/ir_sequence_option.py
  base_sequence_option/readme/CONTRIBUTORS.rst
  base_sequence_option/readme/DESCRIPTION.rst
  base_sequence_option/readme/USAGE.rst
  base_sequence_option/security/ir.model.access.csv
  base_sequence_option/security/sequence_option_security.xml
  base_sequence_option/static/description/icon.png
  base_sequence_option/static/description/index.html
  base_sequence_option/tests/__init__.py
  base_sequence_option/tests/base_sequence_tester.py
  base_sequence_option/tests/common.py
  base_sequence_option/tests/test_ir_sequence_option.py
  base_sequence_option/views/sequence_option_view.xml
  requirements.txt
  setup/base_sequence_option/odoo/addons/base_sequence_option
  setup/base_sequence_option/setup.py
Labels: approved, bot is merging ⏳

#2742 [16.0][IMP] excel_import_export: possibility to apply unidecode
  excel_import_export/models/xlsx_export.py
  excel_import_export/models/xlsx_template.py
  excel_import_export_unidecode/README.rst
  excel_import_export_unidecode/__init__.py
  excel_import_export_unidecode/__manifest__.py
  excel_import_export_unidecode/models/__init__.py
  excel_import_export_unidecode/models/common.py
  excel_import_export_unidecode/models/xlsx_export.py
  excel_import_export_unidecode/models/xlsx_template.py
  excel_import_export_unidecode/readme/CONTRIBUTORS.rst
  excel_import_export_unidecode/readme/DESCRIPTION.rst
  excel_import_export_unidecode/readme/INSTALL.rst
  excel_import_export_unidecode/readme/ROADMAP.rst
  excel_import_export_unidecode/readme/USAGE.rst
  excel_import_export_unidecode/static/description/common_wizard.png
  excel_import_export_unidecode/static/description/icon.png
  excel_import_export_unidecode/static/description/index.html
  excel_import_export_unidecode/static/description/xlsx_template.png
  excel_import_export_unidecode/views/xlsx_template_view.xml
  requirements.txt
  setup/excel_import_export_unidecode/odoo/addons/excel_import_export_unidecode
  setup/excel_import_export_unidecode/setup.py
Labels: approved, bot is merging ⏳

#2753 [14.0] [IMP] module_auto_update: confirm message before updating
  module_auto_update/README.rst
  module_auto_update/__init__.py
  module_auto_update/__manifest__.py
  module_auto_update/readme/CONTRIBUTORS.rst
  module_auto_update/security/ir.model.access.csv
  module_auto_update/static/description/index.html
  module_auto_update/views/ir_module_module.xml
  module_auto_update/wizard/__init__.py
  module_auto_update/wizard/module_auto_update.py
  module_auto_update/wizard/module_auto_update_views.xml
Labels: approved, bot is merging ⏳

#2765 [MIG] base_sequence_default: v16
  base_sequence_default/README.rst
  base_sequence_default/__init__.py
  base_sequence_default/__manifest__.py
  base_sequence_default/demo/ir_sequence_demo.xml
  base_sequence_default/i18n/base_sequence_default.pot
  base_sequence_default/models/__init__.py
  base_sequence_default/models/base.py
  base_sequence_default/readme/CONFIGURE.md
  base_sequence_default/readme/CONTRIBUTORS.md
  base_sequence_default/readme/DESCRIPTION.md
  base_sequence_default/readme/USAGE.md
  base_sequence_default/static/description/icon.png
  base_sequence_default/static/description/index.html
  base_sequence_default/tests/__init__.py
  base_sequence_default/tests/test_project_project.py
  setup/base_sequence_default/odoo/addons/base_sequence_default
  setup/base_sequence_default/setup.py
Labels: needs review, migration, bot is merging ⏳

#2734 [14.0][IMP] model_read_only
  model_read_only/README.rst
  model_read_only/__manifest__.py
  model_read_only/migrations/14.0.2.0.0/post-migration.py
  model_read_only/migrations/14.0.2.0.0/pre-migration.py
  model_read_only/models/models.py
  model_read_only/readme/USAGE.rst
  model_read_only/security/ir.model.access.csv
  model_read_only/static/description/index.html
  model_read_only/tests/test_models.py
  model_read_only/views/views.xml
Labels: approved, ready to merge, bot is merging ⏳
