Repository OCA/server-tools, pull requests merged in 2023-05, with the labels that each got.

#2577 [16.0] rpc_helper: migrate to v16
  rpc_helper/README.rst
  rpc_helper/__init__.py
  rpc_helper/__manifest__.py
  rpc_helper/decorator.py
  rpc_helper/hooks.py
  rpc_helper/i18n/es_AR.po
  rpc_helper/i18n/rpc_helper.pot
  rpc_helper/models/__init__.py
  rpc_helper/models/ir_model.py
  rpc_helper/patch.py
  rpc_helper/readme/CONFIGURE.rst
  rpc_helper/readme/CONTRIBUTORS.rst
  rpc_helper/readme/DESCRIPTION.rst
  rpc_helper/readme/USAGE.rst
  rpc_helper/rpc_test_example.py
  rpc_helper/static/description/icon.png
  rpc_helper/static/description/index.html
  rpc_helper/tests/__init__.py
  rpc_helper/tests/test_decorator.py
  rpc_helper/tests/test_xmlrpc.py
  rpc_helper/views/ir_model_views.xml
  setup/rpc_helper/odoo/addons/rpc_helper
  setup/rpc_helper/setup.py
Labels: bot is merging ⏳

#2612 [14.0][FIX] *: remove `lxml` from python depends
  html_image_url_extractor/__manifest__.py
  html_text/__manifest__.py
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#2324 [14.0] Add jsonifier_stored
  jsonifier_stored/README.rst
  jsonifier_stored/__init__.py
  jsonifier_stored/__manifest__.py
  jsonifier_stored/data/ir_cron.xml
  jsonifier_stored/data/queue_job.xml
  jsonifier_stored/hooks.py
  jsonifier_stored/models/__init__.py
  jsonifier_stored/models/jsonifier_stored_mixin.py
  jsonifier_stored/readme/CONTRIBUTORS.rst
  jsonifier_stored/readme/DESCRIPTION.rst
  jsonifier_stored/readme/ROADMAP.rst
  jsonifier_stored/readme/USAGE.rst
  jsonifier_stored/tests/__init__.py
  jsonifier_stored/tests/common.py
  jsonifier_stored/tests/fake_models.py
  jsonifier_stored/tests/fixtures/ir_exports_test.xml
  jsonifier_stored/tests/test_cron.py
  jsonifier_stored/tests/test_multi_lang.py
  jsonifier_stored/tests/test_single_lang.py
  setup/jsonifier_stored/odoo/addons/jsonifier_stored
  setup/jsonifier_stored/setup.py
Labels: bot is merging ⏳

#2621 [14.0] rpc_helper: upgrade to Beta
  rpc_helper/__manifest__.py
Labels: bot is merging ⏳

#2609 [16][MIG ] module_analysis
  module_analysis/README.rst
  module_analysis/__init__.py
  module_analysis/__manifest__.py
  module_analysis/data/ir_config_parameter.xml
  module_analysis/data/ir_cron.xml
  module_analysis/data/ir_module_type.xml
  module_analysis/data/ir_module_type_rule.xml
  module_analysis/i18n/it.po
  module_analysis/i18n/module_analysis.pot
  module_analysis/i18n/zh_CN.po
  module_analysis/models/__init__.py
  module_analysis/models/ir_module_author.py
  module_analysis/models/ir_module_module.py
  module_analysis/models/ir_module_type.py
  module_analysis/models/ir_module_type_rule.py
  module_analysis/readme/CONFIGURE.rst
  module_analysis/readme/CONTRIBUTORS.rst
  module_analysis/readme/DESCRIPTION.rst
  module_analysis/readme/INSTALL.rst
  module_analysis/readme/USAGE.rst
  module_analysis/security/ir.model.access.csv
  module_analysis/static/description/add_module_type_rules.png
  module_analysis/static/description/analysis_pie.png
  module_analysis/static/description/analysis_pivot.png
  module_analysis/static/description/config_parameters.png
  module_analysis/static/description/default_module_type_rules.png
  module_analysis/static/description/icon.png
  module_analysis/static/description/index.html
  module_analysis/static/description/installed_modules_by_types.png
  module_analysis/static/description/module_authors.png
  module_analysis/static/description/module_form.png
  module_analysis/static/description/module_types.png
  module_analysis/tests/__init__.py
  module_analysis/tests/test_module.py
  module_analysis/views/menu.xml
  module_analysis/views/view_ir_module_author.xml
  module_analysis/views/view_ir_module_module.xml
  module_analysis/views/view_ir_module_type.xml
  module_analysis/views/view_ir_module_type_rule.xml
  requirements.txt
  setup/module_analysis/odoo/addons/module_analysis
  setup/module_analysis/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2492 [14.0] autovacuum_message_attachment: Support inherited models
  autovacuum_message_attachment/models/ir_attachment.py
  autovacuum_message_attachment/models/mail_message.py
  autovacuum_message_attachment/models/vacuum_rule.py
  autovacuum_message_attachment/readme/CONTRIBUTORS.rst
  autovacuum_message_attachment/views/rule_vacuum.xml
Labels: approved, bot is merging ⏳

#2474 [13.0] Create module base_domain_inverse_function
  base_domain_inverse_function/README.rst
  base_domain_inverse_function/__init__.py
  base_domain_inverse_function/__manifest__.py
  base_domain_inverse_function/inverse_expression.py
  base_domain_inverse_function/readme/CONTRIBUTORS.rst
  base_domain_inverse_function/readme/DESCRIPTION.rst
  base_domain_inverse_function/readme/ROADMAP.rst
  base_domain_inverse_function/readme/USAGE.rst
  base_domain_inverse_function/tests/__init__.py
  base_domain_inverse_function/tests/test_inverse_function.py
  base_domain_inverse_function/tests/test_partner_domains.py
  setup/base_domain_inverse_function/odoo/addons/base_domain_inverse_function
  setup/base_domain_inverse_function/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2624 [FIX] upgrade_analysis : avoid KeyError "module"
  upgrade_analysis/odoo_patch/odoo/modules/registry.py
Labels: approved, bot is merging ⏳

#2625 [16.0][FIX] module_analysis : tests compatibility with pip install
  module_analysis/tests/test_module.py
Labels: approved, bot is merging ⏳

#2570 [15.0][FIX] module_analysis: Fix tests
  module_analysis/post_init_hook.py
  module_analysis/tests/test_module.py
Labels: bot is merging ⏳

#2125 [14.0][FIX+IMP] base_technical_user: Multi company context
  base_technical_user/models/models.py
  base_technical_user/tests/test_sudo_tech.py
Labels: approved, ready to merge, bot is merging ⏳

#2560 [16.0][MIG][REF] attachment_queue
  attachment_queue/README.rst
  attachment_queue/__init__.py
  attachment_queue/__manifest__.py
  attachment_queue/data/mail_template.xml
  attachment_queue/data/queue_job_channel.xml
  attachment_queue/demo/attachment_queue.xml
  attachment_queue/i18n/attachment_queue.pot
  attachment_queue/models/__init__.py
  attachment_queue/models/attachment_queue.py
  attachment_queue/readme/CONTRIBUTORS.rst
  attachment_queue/readme/DESCRIPTION.rst
  attachment_queue/readme/USAGE.rst
  attachment_queue/security/ir.model.access.csv
  attachment_queue/static/description/form.png
  attachment_queue/static/description/icon.png
  attachment_queue/static/description/index.html
  attachment_queue/static/description/tree.png
  attachment_queue/tests/__init__.py
  attachment_queue/tests/test_attachment_queue.py
  attachment_queue/tests/test_models.py
  attachment_queue/views/attachment_queue_view.xml
  attachment_queue/wizards/__init__.py
  attachment_queue/wizards/attachement_queue_reschedule.py
  attachment_queue/wizards/attachement_queue_reschedule.xml
  setup/attachment_queue/odoo/addons/attachment_queue
  setup/attachment_queue/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2380 [15.0] [MIG] base_changeset
  base_changeset/README.rst
  base_changeset/__init__.py
  base_changeset/__manifest__.py
  base_changeset/demo/changeset_field_rule.xml
  base_changeset/i18n/base_changeset.pot
  base_changeset/i18n/ca.po
  base_changeset/i18n/es.po
  base_changeset/i18n/it.po
  base_changeset/models/__init__.py
  base_changeset/models/base.py
  base_changeset/models/changeset_field_rule.py
  base_changeset/models/record_changeset.py
  base_changeset/models/record_changeset_change.py
  base_changeset/readme/CONFIGURE.rst
  base_changeset/readme/CONTRIBUTORS.rst
  base_changeset/readme/DESCRIPTION.rst
  base_changeset/readme/ROADMAP.rst
  base_changeset/readme/USAGE.rst
  base_changeset/security/groups.xml
  base_changeset/security/ir.model.access.csv
  base_changeset/security/rules.xml
  base_changeset/static/description/icon.png
  base_changeset/static/description/index.html
  base_changeset/static/src/img/badge.png
  base_changeset/static/src/img/badge_click.png
  base_changeset/static/src/img/changeset.png
  base_changeset/static/src/img/rules.png
  base_changeset/static/src/js/backend.js
  base_changeset/static/src/scss/backend.scss
  base_changeset/static/src/xml/backend.xml
  base_changeset/tests/__init__.py
  base_changeset/tests/common.py
  base_changeset/tests/test_changeset_field_rule.py
  base_changeset/tests/test_changeset_field_type.py
  base_changeset/tests/test_changeset_flow.py
  base_changeset/tests/test_changeset_origin.py
  base_changeset/tests/test_changeset_security.py
  base_changeset/views/changeset_field_rule_views.xml
  base_changeset/views/menu.xml
  base_changeset/views/record_changeset_change_views.xml
  base_changeset/views/record_changeset_views.xml
  setup/base_changeset/odoo/addons/base_changeset
  setup/base_changeset/setup.py
Labels: approved, bot is merging ⏳
