Repository OCA/server-tools, pull requests merged in 2023-07, with the labels that each got.

#2656 [14.0] [MIG] `module_analysis`
  module_analysis/README.rst
  module_analysis/__init__.py
  module_analysis/__manifest__.py
  module_analysis/data/ir_config_parameter.xml
  module_analysis/data/ir_cron.xml
  module_analysis/data/ir_module_type.xml
  module_analysis/data/ir_module_type_rule.xml
  module_analysis/i18n/it.po
  module_analysis/i18n/module_analysis.pot
  module_analysis/i18n/zh_CN.po
  module_analysis/models/__init__.py
  module_analysis/models/base_module_update.py
  module_analysis/models/ir_module_author.py
  module_analysis/models/ir_module_module.py
  module_analysis/models/ir_module_type.py
  module_analysis/models/ir_module_type_rule.py
  module_analysis/post_init_hook.py
  module_analysis/readme/CONFIGURE.rst
  module_analysis/readme/CONTRIBUTORS.rst
  module_analysis/readme/DESCRIPTION.rst
  module_analysis/readme/INSTALL.rst
  module_analysis/readme/USAGE.rst
  module_analysis/security/ir.model.access.csv
  module_analysis/static/description/add_module_type_rules.png
  module_analysis/static/description/analysis_pie.png
  module_analysis/static/description/analysis_pivot.png
  module_analysis/static/description/base_module_update.png
  module_analysis/static/description/config_parameters.png
  module_analysis/static/description/default_module_type_rules.png
  module_analysis/static/description/icon.png
  module_analysis/static/description/index.html
  module_analysis/static/description/installed_modules_by_types.png
  module_analysis/static/description/module_authors.png
  module_analysis/static/description/module_form.png
  module_analysis/static/description/module_types.png
  module_analysis/tests/__init__.py
  module_analysis/tests/module/__init__.py
  module_analysis/tests/module/__manifest__.py
  module_analysis/tests/module/models/__init__.py
  module_analysis/tests/module/models/ir_module_module.py
  module_analysis/tests/module/models/res_partner.py
  module_analysis/tests/module/static/src/css/styles.css
  module_analysis/tests/module/static/src/js/web_client.js
  module_analysis/tests/module/static/src/scss/styles.scss
  module_analysis/tests/module/views/ir_module_module.xml
  module_analysis/tests/module/views/res_partner.xml
  module_analysis/tests/test_module.py
  module_analysis/views/menu.xml
  module_analysis/views/view_base_module_update.xml
  module_analysis/views/view_ir_module_author.xml
  module_analysis/views/view_ir_module_module.xml
  module_analysis/views/view_ir_module_type.xml
  module_analysis/views/view_ir_module_type_rule.xml
  requirements.txt
  setup/module_analysis/odoo/addons/module_analysis
  setup/module_analysis/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2616 base_sequence_option - Beta development status
  base_sequence_option/__manifest__.py
Labels: approved, ready to merge, bot is merging ⏳

#2567 [16.0][IMP] base_exception: Improved wizard view
  base_exception/wizard/base_exception_confirm_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2669 [15.0][FIX] base_changeset: permission errors on models and fields
  base_changeset/models/base.py
  base_changeset/models/changeset_field_rule.py
  base_changeset/models/record_changeset_change.py
  base_changeset/tests/test_changeset_flow.py
Labels: approved, bot is merging ⏳

#2674 [14.0][FIX] base_time_parameter: migrations subdirectory renamed to 14.0.3.1.0
  base_time_parameter/migrations/14.0.3.1.0/pre-migration.py
Labels: bot is merging ⏳

#2675 [14.0] model_read_only
  model_read_only/README.rst
  model_read_only/__init__.py
  model_read_only/__manifest__.py
  model_read_only/models/__init__.py
  model_read_only/models/models.py
  model_read_only/readme/CONTRIBUTORS.rst
  model_read_only/readme/DESCRIPTION.rst
  model_read_only/readme/USAGE.rst
  model_read_only/tests/__init__.py
  model_read_only/tests/test_models.py
  model_read_only/views/views.xml
  setup/model_read_only/odoo/addons/model_read_only
  setup/model_read_only/setup.py
Labels: approved, bot is merging ⏳

#2679 [15.0][MIG] attachment_unindex_content
  attachment_unindex_content/README.rst
  attachment_unindex_content/__init__.py
  attachment_unindex_content/__manifest__.py
  attachment_unindex_content/hooks.py
  attachment_unindex_content/i18n/attachment_unindex_content.pot
  attachment_unindex_content/i18n/ca.po
  attachment_unindex_content/i18n/es_AR.po
  attachment_unindex_content/models/__init__.py
  attachment_unindex_content/models/ir_attachment.py
  attachment_unindex_content/readme/CONTRIBUTORS.rst
  attachment_unindex_content/readme/DESCRIPTION.rst
  attachment_unindex_content/static/description/icon.png
  attachment_unindex_content/static/description/index.html
  setup/attachment_unindex_content/odoo/addons/attachment_unindex_content
  setup/attachment_unindex_content/setup.py
Labels: migration, bot is merging ⏳

#2533 [16.0][MIG] base_sparse_field_list_support
  base_sparse_field_list_support/README.rst
  base_sparse_field_list_support/__init__.py
  base_sparse_field_list_support/__manifest__.py
  base_sparse_field_list_support/i18n/base_sparse_field_list_support.pot
  base_sparse_field_list_support/models/__init__.py
  base_sparse_field_list_support/models/fields.py
  base_sparse_field_list_support/readme/CONTRIBUTORS.rst
  base_sparse_field_list_support/readme/DESCRIPTION.rst
  base_sparse_field_list_support/static/description/icon.png
  base_sparse_field_list_support/static/description/index.html
  setup/base_sparse_field_list_support/odoo/addons/base_sparse_field_list_support
  setup/base_sparse_field_list_support/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2677 [13.0][ADD]base_translation_field_label
  base_translation_field_label/__init__.py
  base_translation_field_label/__manifest__.py
  base_translation_field_label/models/__init__.py
  base_translation_field_label/models/ir_translation.py
  base_translation_field_label/readme/CONFIGURE.rst
  base_translation_field_label/readme/CONTRIBUTORS.rst
  base_translation_field_label/readme/DESCRIPTION.rst
  base_translation_field_label/tests/__init__.py
  base_translation_field_label/tests/test_base_transaltion_field_label.py
  base_translation_field_label/views/ir_translation_views.xml
  setup/base_translation_field_label/odoo/addons/base_translation_field_label
  setup/base_translation_field_label/setup.py
Labels: approved, ready to merge, bot is merging ⏳
