Repository OCA/server-tools, pull requests merged in 2023-09, with the labels that each got.

#2700 [FIX] sentry: respect sentry_logging_level
  sentry/const.py
  sentry/tests/test_client.py
Labels: bot is merging ⏳

#2697 [16.0][FIX] session_db: missing argument max_lifetime in PGSessionStore.vacuum()
  session_db/pg_session_store.py
Labels: bot is merging ⏳

#2670 [16.0] base_exception: Improves performances
  base_exception/__manifest__.py
  base_exception/models/__init__.py
  base_exception/models/base_exception.py
  base_exception/models/base_exception_method.py
  base_exception/models/exception_rule.py
  base_exception/readme/CONTRIBUTORS.rst
  base_exception/tests/purchase_test.py
Labels: approved, ready to merge, bot is merging ⏳

#2704 [14.0][IMP] base_custom_info: only save if data has been modified
  base_custom_info/static/src/js/relational_fields.js
Labels: approved, bot is merging ⏳

#2705 [IMP] base_custom_info: only save if data has been modified
  base_custom_info/static/src/js/relational_fields.js
Labels: bot is merging ⏳

#2706 [15.0][FIX] base_view_inheritance_extension: Crash domain for elements with out previous domain defined
  base_view_inheritance_extension/models/ir_ui_view.py
Labels: approved, bot is merging ⏳

#2585 tracking_manager: fix access right issue if sudo have been used
  tracking_manager/models/models.py
Labels: needs review, approved, bot is merging ⏳

#2710 [16.0] [FIX] auditlog consistency with Many2one fields
  auditlog/models/rule.py
  auditlog/tests/test_auditlog.py
Labels: approved, bot is merging ⏳

#2711 [15.0] [FIX] auditlog consistency with Many2one fields
  auditlog/models/rule.py
  auditlog/tests/test_auditlog.py
Labels: approved, bot is merging ⏳

#2371 [15.0][MIG] base_sparse_field_list_support
  base_sparse_field_list_support/README.rst
  base_sparse_field_list_support/__init__.py
  base_sparse_field_list_support/__manifest__.py
  base_sparse_field_list_support/i18n/base_sparse_field_list_support.pot
  base_sparse_field_list_support/models/__init__.py
  base_sparse_field_list_support/models/fields.py
  base_sparse_field_list_support/readme/CONTRIBUTORS.rst
  base_sparse_field_list_support/readme/DESCRIPTION.rst
  base_sparse_field_list_support/static/description/icon.png
  base_sparse_field_list_support/static/description/index.html
  setup/base_sparse_field_list_support/odoo/addons/base_sparse_field_list_support
  setup/base_sparse_field_list_support/setup.py
Labels: approved, ready to merge, bot is merging ⏳
