Repository OCA/server-tools, pull requests merged in 2023-01, with the labels that each got.

#2478 [16.0][MIG] base_cron_exclusion
  base_cron_exclusion/README.rst
  base_cron_exclusion/__init__.py
  base_cron_exclusion/__manifest__.py
  base_cron_exclusion/i18n/base_cron_exclusion.pot
  base_cron_exclusion/i18n/cs_CZ.po
  base_cron_exclusion/i18n/es.po
  base_cron_exclusion/i18n/es_AR.po
  base_cron_exclusion/i18n/fr.po
  base_cron_exclusion/i18n/zh_CN.po
  base_cron_exclusion/models/__init__.py
  base_cron_exclusion/models/ir_cron.py
  base_cron_exclusion/readme/CONTRIBUTORS.rst
  base_cron_exclusion/readme/DESCRIPTION.rst
  base_cron_exclusion/readme/USAGE.rst
  base_cron_exclusion/static/description/icon.png
  base_cron_exclusion/static/description/index.html
  base_cron_exclusion/views/ir_cron_view.xml
  setup/base_cron_exclusion/odoo/addons/base_cron_exclusion
  setup/base_cron_exclusion/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2510 [16.0][MIG] base_technical_user
  base_technical_user/README.rst
  base_technical_user/__init__.py
  base_technical_user/__manifest__.py
  base_technical_user/i18n/ar.po
  base_technical_user/i18n/base_technical_user.pot
  base_technical_user/i18n/de.po
  base_technical_user/i18n/es.po
  base_technical_user/i18n/fr.po
  base_technical_user/i18n/hr.po
  base_technical_user/i18n/it.po
  base_technical_user/i18n/nl_NL.po
  base_technical_user/i18n/pt.po
  base_technical_user/i18n/zh_CN.po
  base_technical_user/models/__init__.py
  base_technical_user/models/models.py
  base_technical_user/models/res_company.py
  base_technical_user/readme/CONTRIBUTORS.rst
  base_technical_user/readme/DESCRIPTION.rst
  base_technical_user/readme/USAGE.rst
  base_technical_user/static/description/icon.png
  base_technical_user/static/description/index.html
  base_technical_user/tests/__init__.py
  base_technical_user/tests/test_sudo_tech.py
  base_technical_user/views/res_company_view.xml
  setup/base_technical_user/odoo/addons/base_technical_user
  setup/base_technical_user/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2249 [14.0] [MIG] mail_cleanup: Migrate to version 14.0
  mail_cleanup/README.rst
  mail_cleanup/__init__.py
  mail_cleanup/__manifest__.py
  mail_cleanup/i18n/ca.po
  mail_cleanup/i18n/de.po
  mail_cleanup/i18n/es.po
  mail_cleanup/i18n/fr.po
  mail_cleanup/i18n/hr.po
  mail_cleanup/i18n/it.po
  mail_cleanup/i18n/mail_cleanup.pot
  mail_cleanup/i18n/pt_BR.po
  mail_cleanup/i18n/sl.po
  mail_cleanup/i18n/tr.po
  mail_cleanup/i18n/zh_CN.po
  mail_cleanup/models/__init__.py
  mail_cleanup/models/fetchmail_server.py
  mail_cleanup/readme/CONFIGURE.rst
  mail_cleanup/readme/CONTRIBUTORS.rst
  mail_cleanup/readme/CREDITS.rst
  mail_cleanup/readme/DESCRIPTION.rst
  mail_cleanup/static/description/icon.png
  mail_cleanup/static/description/index.html
  mail_cleanup/views/mail_view.xml
  setup/mail_cleanup/odoo/addons/mail_cleanup
  setup/mail_cleanup/setup.py
Labels: approved, bot is merging ⏳

#2520 [13.0][FIX] nsca client: external dependencies
  .github/workflows/test.yml
  nsca_client/__manifest__.py
Labels: bot is merging ⏳

#2524 [15.0][UPD] dotfiles
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  module_auto_update/tests/sample_module/i18n/en.po
Labels: bot is merging ⏳

#2523 [14.0][UPD] dotfiles
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  database_cleanup/i18n/en.po
  module_auto_update/tests/sample_module/i18n/en.po
Labels: bot is merging ⏳

#2526 [14.0][FIX] auditlog: Allow passing a chunk size for autovacuum
  auditlog/README.rst
  auditlog/models/autovacuum.py
  auditlog/readme/USAGE.rst
  auditlog/static/description/index.html
Labels: approved, bot is merging ⏳

#2180 [13.0][FIX] sentry: enable use of "sentry_odoo_dir" config parameter
  sentry/__init__.py
  sentry/tests/test_client.py
Labels: approved, ready to merge, bot is merging ⏳

#2516 [16.0][MIG] sentry: Migration to 16.0
  requirements.txt
  sentry/README.rst
  sentry/__init__.py
  sentry/__manifest__.py
  sentry/const.py
  sentry/generalutils.py
  sentry/hooks.py
  sentry/i18n/ca.po
  sentry/i18n/sentry.pot
  sentry/i18n/zh_CN.po
  sentry/logutils.py
  sentry/processor.py
  sentry/readme/CONFIGURE.rst
  sentry/readme/CONTRIBUTORS.rst
  sentry/readme/CREDITS.rst
  sentry/readme/DESCRIPTION.rst
  sentry/readme/INSTALL.rst
  sentry/readme/ROADMAP.rst
  sentry/readme/USAGE.rst
  sentry/static/description/icon.png
  sentry/static/description/index.html
  sentry/tests/__init__.py
  sentry/tests/test_client.py
  sentry/tests/test_logutils.py
  setup/sentry/odoo/addons/sentry
  setup/sentry/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2441 [16.0] session_db
  session_db/README.rst
  session_db/__init__.py
  session_db/__manifest__.py
  session_db/pg_session_store.py
  session_db/readme/DESCRIPTION.rst
  session_db/readme/ROADMAP.rst
  session_db/readme/USAGE.rst
  setup/session_db/odoo/addons/session_db
  setup/session_db/setup.py
Labels: approved, bot is merging ⏳

#2528 [16.0][FIX] auditlog: Allow passing a chunk size for autovacuum
  auditlog/README.rst
  auditlog/models/autovacuum.py
  auditlog/readme/USAGE.rst
  auditlog/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#2532 [15.0][FIX] Pin cryptography to keep compatibility with Odoo's pyopenssl==19.0.0
  auto_backup/__manifest__.py
  requirements.txt
Labels: approved, bot is merging ⏳

#2531 [16.0] session_db: improve resiliency to database errors
  session_db/pg_session_store.py
Labels: bot is merging ⏳

#2527 [15.0][FIX] auditlog: Allow passing a chunk size for autovacuum
  auditlog/README.rst
  auditlog/models/autovacuum.py
  auditlog/readme/USAGE.rst
  auditlog/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳
