Repository OCA/server-tools, pull requests merged in 2024-07, with the labels that each got.

#2940 [14.0][FIX] base_name_search_improved: deal with query objects
  base_name_search_improved/models/ir_model.py
Labels: approved, bot is merging ⏳

#2959 [17.0][ADD] server_action_logging
  server_action_logging/README.rst
  server_action_logging/__init__.py
  server_action_logging/__manifest__.py
  server_action_logging/i18n/fr.po
  server_action_logging/i18n/pt_BR.po
  server_action_logging/i18n/server_action_logging.pot
  server_action_logging/models/__init__.py
  server_action_logging/models/ir_actions_server.py
  server_action_logging/pyproject.toml
  server_action_logging/readme/CONTRIBUTORS.md
  server_action_logging/readme/DESCRIPTION.md
  server_action_logging/readme/USAGE.md
  server_action_logging/static/description/icon.png
  server_action_logging/static/description/index.html
  server_action_logging/tests/__init__.py
  server_action_logging/tests/test_server_action_logging.py
  server_action_logging/views/ir_actions_server.xml
  setup/server_action_logging/odoo/addons/server_action_logging
  setup/server_action_logging/setup.py
Labels: bot is merging ⏳

#2979 sync project from template
  .copier-answers.yml
  .eslintrc.yml
  .gitignore
Labels: bot is merging ⏳

#2980 remove setup/server_action_logging
  setup/server_action_logging/odoo/addons/server_action_logging
  setup/server_action_logging/setup.py
Labels: bot is merging ⏳

#2985 [14.0][FW][FIX] database_cleanup: Bug introduced by #2098
  database_cleanup/models/purge_tables.py
Labels: bot is merging ⏳

#2987 [16.0][FW][FIX] database_cleanup: Bug introduced by #2098
  database_cleanup/models/purge_tables.py
Labels: bot is merging ⏳

#2986 [15.0][FW][FIX] database_cleanup: Bug introduced by #2098
  database_cleanup/models/purge_tables.py
Labels: bot is merging ⏳

#2993 [14.0][backport] database_cleanup: Prevent deletion of columns added in the init method of the model.
  database_cleanup/models/purge_columns.py
  database_cleanup/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#2994 [15.0][FIX] database_cleanup: Prevent deletion of columns added in the init method of the model
  database_cleanup/README.rst
  database_cleanup/models/purge_columns.py
  database_cleanup/readme/CONTRIBUTORS.rst
  database_cleanup/static/description/index.html
Labels: bot is merging ⏳

#2995 [IMP] session_db: remove ROADMAP
  session_db/readme/ROADMAP.rst
Labels: bot is merging ⏳

#3002 tracking_manager: Fix tools.formatm2m
  tracking_manager/tools.py
Labels: approved, bot is merging ⏳

#2999 [16.0][IMP] fetchmail_attach_from_folder: outlook as server_type
  fetchmail_attach_from_folder/views/fetchmail_server.xml
Labels: approved, ready to merge, bot is merging ⏳

#3000 [16.0][IMP] fetchmail_attach_from_folder: ir.actions.server
  fetchmail_attach_from_folder/models/fetchmail_server_folder.py
  fetchmail_attach_from_folder/tests/test_match_algorithms.py
  fetchmail_attach_from_folder/views/fetchmail_server.xml
Labels: approved, ready to merge, bot is merging ⏳

#3001 [16.0][IMP] fetchmail_attach_from_folder: Read e-mails are excluded
  fetchmail_attach_from_folder/models/fetchmail_server_folder.py
  fetchmail_attach_from_folder/views/fetchmail_server.xml
  fetchmail_attach_from_folder/wizard/attach_mail_manually.py
Labels: approved, ready to merge, bot is merging ⏳
