Repository OCA/server-tools, pull requests merged in 2024-08, with the labels that each got.

#2992 [16.0][FIX] excel_import_export: remove sudo() when importing record
  excel_import_export/models/xlsx_import.py
Labels: approved, ready to merge, bot is merging ⏳

#3018 [16.0][IMP] tracking_manager: Test compatibility
  tracking_manager/tests/models.py
  tracking_manager/tests/test_tracking_manager.py
Labels: approved, bot is merging ⏳

#3020 [17.0][IMP] tracking_manager: Test compatibility
  tracking_manager/tests/models.py
  tracking_manager/tests/test_tracking_manager.py
Labels: bot is merging ⏳

#3021 [16.0][FIX] tracking_manager: prevent error on models without mail.thread
  tracking_manager/models/models.py
Labels: approved, bot is merging ⏳

#3023 [17][FW][FIX] tracking_manager: prevent error on models without mail.thread
  tracking_manager/models/models.py
Labels: bot is merging ⏳
