Repository OCA/server-tools, pull requests merged in 2024-11, with the labels that each got.

#3108 [18.0][MIG] upgrade_analysis: Migration to v18
  requirements.txt
  upgrade_analysis/README.rst
  upgrade_analysis/__init__.py
  upgrade_analysis/__manifest__.py
  upgrade_analysis/blacklist.py
  upgrade_analysis/compare.py
  upgrade_analysis/i18n/es_AR.po
  upgrade_analysis/i18n/fr.po
  upgrade_analysis/i18n/it.po
  upgrade_analysis/i18n/upgrade_analysis.pot
  upgrade_analysis/i18n/zh_CN.po
  upgrade_analysis/models/__init__.py
  upgrade_analysis/models/ir_module_module.py
  upgrade_analysis/models/upgrade_analysis.py
  upgrade_analysis/models/upgrade_attribute.py
  upgrade_analysis/models/upgrade_comparison_config.py
  upgrade_analysis/models/upgrade_record.py
  upgrade_analysis/odoo_patch/__init__.py
  upgrade_analysis/odoo_patch/addons/__init__.py
  upgrade_analysis/odoo_patch/addons/mrp/__init__.py
  upgrade_analysis/odoo_patch/addons/stock/__init__.py
  upgrade_analysis/odoo_patch/odoo/__init__.py
  upgrade_analysis/odoo_patch/odoo/addons/__init__.py
  upgrade_analysis/odoo_patch/odoo/addons/base/__init__.py
  upgrade_analysis/odoo_patch/odoo/addons/base/models/__init__.py
  upgrade_analysis/odoo_patch/odoo/addons/base/models/ir_model.py
  upgrade_analysis/odoo_patch/odoo/models.py
  upgrade_analysis/odoo_patch/odoo/modules/__init__.py
  upgrade_analysis/odoo_patch/odoo/modules/registry.py
  upgrade_analysis/odoo_patch/odoo/tools/__init__.py
  upgrade_analysis/odoo_patch/odoo/tools/convert.py
  upgrade_analysis/odoo_patch/odoo_patch.py
  upgrade_analysis/pyproject.toml
  upgrade_analysis/readme/CONTRIBUTORS.md
  upgrade_analysis/readme/DESCRIPTION.md
  upgrade_analysis/readme/ROADMAP.md
  upgrade_analysis/readme/USAGE.md
  upgrade_analysis/security/ir.model.access.csv
  upgrade_analysis/static/description/icon.png
  upgrade_analysis/static/description/index.html
  upgrade_analysis/static/src/module_coverage_template.rst.mako
  upgrade_analysis/tests/__init__.py
  upgrade_analysis/tests/test_module.py
  upgrade_analysis/upgrade_log.py
  upgrade_analysis/views/menu.xml
  upgrade_analysis/views/view_upgrade_analysis.xml
  upgrade_analysis/views/view_upgrade_comparison_config.xml
  upgrade_analysis/views/view_upgrade_record.xml
  upgrade_analysis/wizards/__init__.py
  upgrade_analysis/wizards/upgrade_generate_record_wizard.py
  upgrade_analysis/wizards/upgrade_install_wizard.py
  upgrade_analysis/wizards/view_upgrade_generate_record_wizard.xml
  upgrade_analysis/wizards/view_upgrade_install_wizard.xml
Labels: approved, bot is merging ⏳

#3059 [18.0][MIG] base_cron_exclusion: Migration to 18.0
  base_cron_exclusion/README.rst
  base_cron_exclusion/__init__.py
  base_cron_exclusion/__manifest__.py
  base_cron_exclusion/i18n/base_cron_exclusion.pot
  base_cron_exclusion/i18n/cs_CZ.po
  base_cron_exclusion/i18n/es.po
  base_cron_exclusion/i18n/es_AR.po
  base_cron_exclusion/i18n/fr.po
  base_cron_exclusion/i18n/it.po
  base_cron_exclusion/i18n/zh_CN.po
  base_cron_exclusion/models/__init__.py
  base_cron_exclusion/models/ir_cron.py
  base_cron_exclusion/pyproject.toml
  base_cron_exclusion/readme/CONTRIBUTORS.md
  base_cron_exclusion/readme/CREDITS.md
  base_cron_exclusion/readme/DESCRIPTION.md
  base_cron_exclusion/readme/USAGE.md
  base_cron_exclusion/static/description/icon.png
  base_cron_exclusion/static/description/index.html
  base_cron_exclusion/tests/__init__.py
  base_cron_exclusion/tests/test_ir_cron.py
  base_cron_exclusion/views/ir_cron_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#3096 [18.0][MIG] base_time_window: Migration to 18.0
  .oca/oca-port/blacklist/base_time_window.json
  base_time_window/README.rst
  base_time_window/__init__.py
  base_time_window/__manifest__.py
  base_time_window/data/time_weekday.xml
  base_time_window/i18n/base_time_window.pot
  base_time_window/i18n/es.po
  base_time_window/i18n/es_AR.po
  base_time_window/i18n/it.po
  base_time_window/models/__init__.py
  base_time_window/models/time_weekday.py
  base_time_window/models/time_window_mixin.py
  base_time_window/pyproject.toml
  base_time_window/readme/CONTRIBUTORS.md
  base_time_window/readme/CREDITS.md
  base_time_window/readme/DESCRIPTION.md
  base_time_window/readme/ROADMAP.md
  base_time_window/readme/USAGE.md
  base_time_window/security/ir.model.access.xml
  base_time_window/static/description/icon.png
  base_time_window/static/description/index.html
  base_time_window/tests/__init__.py
  base_time_window/tests/test_models.py
  base_time_window/tests/test_time_weekday.py
  base_time_window/tests/test_time_window_mixin.py
  test-requirements.txt
  test_base_time_window/README.rst
  test_base_time_window/__init__.py
  test_base_time_window/__manifest__.py
  test_base_time_window/i18n/ca.po
  test_base_time_window/i18n/es.po
  test_base_time_window/i18n/test_base_time_window.pot
  test_base_time_window/models/__init__.py
  test_base_time_window/models/partner_time_window.py
  test_base_time_window/models/res_partner.py
  test_base_time_window/pyproject.toml
  test_base_time_window/readme/CONTRIBUTORS.md
  test_base_time_window/readme/CREDITS.md
  test_base_time_window/readme/DESCRIPTION.md
  test_base_time_window/security/ir.model.access.xml
  test_base_time_window/static/description/icon.png
  test_base_time_window/static/description/index.html
  test_base_time_window/tests/__init__.py
  test_base_time_window/tests/test_base_time_window.py
Labels: approved, migration, bot is merging ⏳

#3112 [16.0][FIX] tracking_manager: Fix test related to ir.actions.act_window
  tracking_manager/tests/test_tracking_manager.py
Labels: approved, bot is merging ⏳

#3113 [17.0][FIX] tracking_manager: Fix test related to ir.actions.act_window
  tracking_manager/tests/test_tracking_manager.py
Labels: bot is merging ⏳

#3095 [15.0][IMP] excel_import_export: allow selection of all related templates for export action
  excel_import_export/models/xlsx_template.py
Labels: bot is merging ⏳

#3110 [FIX] module_analysis: don't import twice ir.cron
  module_analysis/__manifest__.py
Labels: approved, bot is merging ⏳

#3114 [16.0][IMP] excel_import_export: excel_import_export: allow selection of all related templates for export action
  excel_import_export/models/xlsx_template.py
Labels: approved, bot is merging ⏳

#2972 [16.0][MIG] sequence_python
  sequence_python/README.rst
  sequence_python/__init__.py
  sequence_python/__manifest__.py
  sequence_python/i18n/ca.po
  sequence_python/i18n/es_AR.po
  sequence_python/i18n/sequence_python.pot
  sequence_python/models/__init__.py
  sequence_python/models/ir_sequence.py
  sequence_python/readme/CONTRIBUTORS.rst
  sequence_python/readme/DESCRIPTION.rst
  sequence_python/readme/USAGE.rst
  sequence_python/static/description/icon.png
  sequence_python/static/description/index.html
  sequence_python/tests/__init__.py
  sequence_python/tests/test_ir_sequence.py
  sequence_python/views/ir_sequence.xml
  setup/sequence_python/odoo/addons/sequence_python
  setup/sequence_python/setup.py
Labels: bot is merging ⏳

#3007 [16.0][MIG] base_import_default_enable_tracking: Migration to 16.0
  base_import_default_enable_tracking/README.rst
  base_import_default_enable_tracking/__init__.py
  base_import_default_enable_tracking/__manifest__.py
  base_import_default_enable_tracking/i18n/base_import_default_enable_tracking.pot
  base_import_default_enable_tracking/i18n/es.po
  base_import_default_enable_tracking/i18n/hr.po
  base_import_default_enable_tracking/i18n/it.po
  base_import_default_enable_tracking/readme/DESCRIPTION.rst
  base_import_default_enable_tracking/static/description/icon.png
  base_import_default_enable_tracking/static/description/index.html
  base_import_default_enable_tracking/static/src/xml/base_import.xml
  setup/base_import_default_enable_tracking/odoo/addons/base_import_default_enable_tracking
  setup/base_import_default_enable_tracking/setup.py
Labels: bot is merging ⏳

#3117 Fix patch message on module_change_auto_install
  module_change_auto_install/patch.py
Labels: bot is merging ⏳

#3099 [18.0][MIG] dbfilter_from_header: Migration to 18.0
  dbfilter_from_header/README.rst
  dbfilter_from_header/__init__.py
  dbfilter_from_header/__manifest__.py
  dbfilter_from_header/i18n/dbfilter_from_header.pot
  dbfilter_from_header/i18n/es_AR.po
  dbfilter_from_header/i18n/it.po
  dbfilter_from_header/i18n/zh_CN.po
  dbfilter_from_header/override.py
  dbfilter_from_header/pyproject.toml
  dbfilter_from_header/readme/CONFIGURE.md
  dbfilter_from_header/readme/CONTRIBUTORS.md
  dbfilter_from_header/readme/DESCRIPTION.md
  dbfilter_from_header/readme/INSTALL.md
  dbfilter_from_header/readme/USAGE.md
  dbfilter_from_header/static/description/icon.png
  dbfilter_from_header/static/description/index.html
Labels: approved, bot is merging ⏳

#3050 [18.0][MIG] session_db
  session_db/README.rst
  session_db/__init__.py
  session_db/__manifest__.py
  session_db/i18n/it.po
  session_db/i18n/session_db.pot
  session_db/pg_session_store.py
  session_db/pyproject.toml
  session_db/readme/DESCRIPTION.md
  session_db/readme/USAGE.md
  session_db/static/description/icon.png
  session_db/static/description/index.html
  session_db/tests/__init__.py
  session_db/tests/test_pg_session_store.py
Labels: approved, ready to merge, bot is merging ⏳

#3034 [15.0][FIX] excel_import_export: require attach when res_id false
  excel_import_export/wizard/import_xlsx_wizard.py
  excel_import_export/wizard/import_xlsx_wizard.xml
Labels: approved, ready to merge, bot is merging ⏳

#3014 [14.0] jsonifier: fix field validation
  jsonifier/models/models.py
  jsonifier/tests/test_get_parser.py
Labels: bot is merging ⏳

#3077 [18.0][MIG] base_partition: Migration to 18.0
  base_partition/README.rst
  base_partition/__init__.py
  base_partition/__manifest__.py
  base_partition/i18n/base_partition.pot
  base_partition/i18n/es.po
  base_partition/i18n/fr_BE.pot
  base_partition/i18n/it.po
  base_partition/i18n/zh_CN.po
  base_partition/models/__init__.py
  base_partition/models/models.py
  base_partition/pyproject.toml
  base_partition/readme/CONTRIBUTORS.md
  base_partition/readme/DESCRIPTION.md
  base_partition/static/description/icon.png
  base_partition/static/description/index.html
  base_partition/tests/__init__.py
  base_partition/tests/test_partition.py
Labels: approved, ready to merge, bot is merging ⏳

#3120 [18.0][MIG] base_view_inheritance_extension: Migration to 18.0
  .oca/oca-port/blacklist/base_view_inheritance_extension.json
  base_view_inheritance_extension/README.rst
  base_view_inheritance_extension/__init__.py
  base_view_inheritance_extension/__manifest__.py
  base_view_inheritance_extension/demo/ir_ui_view.xml
  base_view_inheritance_extension/i18n/base_view_inheritance_extension.pot
  base_view_inheritance_extension/i18n/ca.po
  base_view_inheritance_extension/i18n/de.po
  base_view_inheritance_extension/i18n/es.po
  base_view_inheritance_extension/i18n/es_AR.po
  base_view_inheritance_extension/i18n/hr.po
  base_view_inheritance_extension/i18n/it.po
  base_view_inheritance_extension/i18n/sl.po
  base_view_inheritance_extension/i18n/tr.po
  base_view_inheritance_extension/models/__init__.py
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/pyproject.toml
  base_view_inheritance_extension/readme/CONTRIBUTORS.md
  base_view_inheritance_extension/readme/DESCRIPTION.md
  base_view_inheritance_extension/readme/ROADMAP.md
  base_view_inheritance_extension/readme/USAGE.md
  base_view_inheritance_extension/static/description/icon.png
  base_view_inheritance_extension/static/description/index.html
  base_view_inheritance_extension/tests/__init__.py
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#3130 [12.0][BKP] rpc_helper
  rpc_helper/README.rst
  rpc_helper/__init__.py
  rpc_helper/__manifest__.py
  rpc_helper/decorator.py
  rpc_helper/hooks.py
  rpc_helper/i18n/es.po
  rpc_helper/i18n/es_AR.po
  rpc_helper/i18n/rpc_helper.pot
  rpc_helper/models/__init__.py
  rpc_helper/models/ir_model.py
  rpc_helper/patch.py
  rpc_helper/readme/CONFIGURE.rst
  rpc_helper/readme/CONTRIBUTORS.rst
  rpc_helper/readme/DESCRIPTION.rst
  rpc_helper/readme/USAGE.rst
  rpc_helper/rpc_test_example.py
  rpc_helper/static/description/icon.png
  rpc_helper/static/description/index.html
  rpc_helper/tests/__init__.py
  rpc_helper/tests/test_decorator.py
  rpc_helper/tests/test_xmlrpc.py
  rpc_helper/views/ir_model_views.xml
  setup/rpc_helper/odoo/addons/rpc_helper
  setup/rpc_helper/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3097 [18.0][MIG] attachment_unindex_content
  attachment_unindex_content/README.rst
  attachment_unindex_content/__init__.py
  attachment_unindex_content/__manifest__.py
  attachment_unindex_content/hooks.py
  attachment_unindex_content/i18n/attachment_unindex_content.pot
  attachment_unindex_content/i18n/ca.po
  attachment_unindex_content/i18n/es.po
  attachment_unindex_content/i18n/es_AR.po
  attachment_unindex_content/i18n/it.po
  attachment_unindex_content/models/__init__.py
  attachment_unindex_content/models/ir_attachment.py
  attachment_unindex_content/pyproject.toml
  attachment_unindex_content/readme/CONTRIBUTORS.md
  attachment_unindex_content/readme/CREDITS.md
  attachment_unindex_content/readme/DESCRIPTION.md
  attachment_unindex_content/static/description/icon.png
  attachment_unindex_content/static/description/index.html
Labels: approved, bot is merging ⏳
