Repository OCA/server-tools, pull requests merged in 2024-12, with the labels that each got.

#2947 [17.0][MIG] base_sparse_field_list_support
  base_sparse_field_list_support/README.rst
  base_sparse_field_list_support/__init__.py
  base_sparse_field_list_support/__manifest__.py
  base_sparse_field_list_support/i18n/base_sparse_field_list_support.pot
  base_sparse_field_list_support/i18n/it.po
  base_sparse_field_list_support/models/__init__.py
  base_sparse_field_list_support/models/fields.py
  base_sparse_field_list_support/pyproject.toml
  base_sparse_field_list_support/readme/CONTRIBUTORS.md
  base_sparse_field_list_support/readme/DESCRIPTION.md
  base_sparse_field_list_support/static/description/icon.png
  base_sparse_field_list_support/static/description/index.html
Labels: approved, bot is merging ⏳

#3135 [17.0][MIG] rpc_helper: Migration to 17.0
  rpc_helper/README.rst
  rpc_helper/__init__.py
  rpc_helper/__manifest__.py
  rpc_helper/decorator.py
  rpc_helper/hooks.py
  rpc_helper/i18n/es.po
  rpc_helper/i18n/es_AR.po
  rpc_helper/i18n/it.po
  rpc_helper/i18n/rpc_helper.pot
  rpc_helper/models/__init__.py
  rpc_helper/models/ir_model.py
  rpc_helper/patch.py
  rpc_helper/pyproject.toml
  rpc_helper/readme/CONFIGURE.md
  rpc_helper/readme/CONTRIBUTORS.md
  rpc_helper/readme/DESCRIPTION.md
  rpc_helper/readme/USAGE.md
  rpc_helper/rpc_test_example.py
  rpc_helper/static/description/icon.png
  rpc_helper/static/description/index.html
  rpc_helper/tests/__init__.py
  rpc_helper/tests/test_decorator.py
  rpc_helper/tests/test_xmlrpc.py
  rpc_helper/views/ir_model_views.xml
Labels: approved, bot is merging ⏳

#3125 [18.0][MIG] rpc_helper: Migration to 18.0
  rpc_helper/README.rst
  rpc_helper/__init__.py
  rpc_helper/__manifest__.py
  rpc_helper/decorator.py
  rpc_helper/hooks.py
  rpc_helper/i18n/es.po
  rpc_helper/i18n/es_AR.po
  rpc_helper/i18n/it.po
  rpc_helper/i18n/rpc_helper.pot
  rpc_helper/models/__init__.py
  rpc_helper/models/ir_model.py
  rpc_helper/patch.py
  rpc_helper/pyproject.toml
  rpc_helper/readme/CONFIGURE.md
  rpc_helper/readme/CONTRIBUTORS.md
  rpc_helper/readme/CREDITS.md
  rpc_helper/readme/DESCRIPTION.md
  rpc_helper/readme/USAGE.md
  rpc_helper/rpc_test_example.py
  rpc_helper/static/description/icon.png
  rpc_helper/static/description/index.html
  rpc_helper/tests/__init__.py
  rpc_helper/tests/test_decorator.py
  rpc_helper/tests/test_xmlrpc.py
  rpc_helper/views/ir_model_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#3146 [16.0][FIX] auditlog: patch away all write overrides in res.groups for test
  auditlog/tests/test_multi_company.py
Labels: approved, bot is merging ⏳

#3128 [16.0][FIX] letsencrypt: re-enable tests
  letsencrypt/README.rst
  letsencrypt/__manifest__.py
  letsencrypt/static/description/index.html
  letsencrypt/tests/__init__.py
  letsencrypt/tests/test_letsencrypt.py
Labels: approved, ready to merge, bot is merging ⏳

#3147 [17.0][FIX] auditlog: patch away all write overrides in res.groups for test (forward port)
  auditlog/tests/test_multi_company.py
Labels: bot is merging ⏳

#3137 [17.0] [FIX] auditlog: Dismiss logging when not needed.
  auditlog/models/rule.py
  auditlog/tests/test_auditlog.py
Labels: approved, ready to merge, bot is merging ⏳

#3149 [17.0][FIX] database_cleanup: complete excluded columns
  database_cleanup/models/purge_columns.py
Labels: bot is merging ⏳

#3091 [18.0][MIG] base_m2m_custom_field: Migration to 18.0
  base_m2m_custom_field/README.rst
  base_m2m_custom_field/__init__.py
  base_m2m_custom_field/__manifest__.py
  base_m2m_custom_field/fields.py
  base_m2m_custom_field/i18n/base_m2m_custom_field.pot
  base_m2m_custom_field/pyproject.toml
  base_m2m_custom_field/readme/CONTRIBUTORS.md
  base_m2m_custom_field/readme/DESCRIPTION.md
  base_m2m_custom_field/readme/USAGE.md
  base_m2m_custom_field/static/description/icon.png
  base_m2m_custom_field/static/description/index.html
Labels: approved, bot is merging ⏳

#2922 [16.0] [MIG] nsca_client: Migration to 16.0
  nsca_client/README.rst
  nsca_client/__init__.py
  nsca_client/__manifest__.py
  nsca_client/demo/demo_data.xml
  nsca_client/i18n/es.po
  nsca_client/i18n/fr.po
  nsca_client/i18n/nsca_client.pot
  nsca_client/models/__init__.py
  nsca_client/models/nsca_check.py
  nsca_client/models/nsca_server.py
  nsca_client/readme/CONFIGURE.rst
  nsca_client/readme/CONTRIBUTORS.rst
  nsca_client/readme/DESCRIPTION.rst
  nsca_client/readme/INSTALL.rst
  nsca_client/security/ir.model.access.csv
  nsca_client/static/description/check.png
  nsca_client/static/description/icon.png
  nsca_client/static/description/index.html
  nsca_client/static/description/server.png
  nsca_client/tests/__init__.py
  nsca_client/tests/test_nsca.py
  nsca_client/views/nsca_check.xml
  nsca_client/views/nsca_menu.xml
  nsca_client/views/nsca_server.xml
  setup/nsca_client/odoo/addons/nsca_client
  setup/nsca_client/setup.py
Labels: approved, bot is merging ⏳

#3015 [FIX] recompute tracking when automatic_custom_tracking is set to False
  tracking_manager/models/ir_model.py
  tracking_manager/tests/test_tracking_manager.py
Labels: approved, ready to merge, bot is merging ⏳

#3127 [16.0] [BACKPORT] odoo_test_xmlrunner + fixes
  odoo_test_xmlrunner/README.rst
  odoo_test_xmlrunner/__init__.py
  odoo_test_xmlrunner/__manifest__.py
  odoo_test_xmlrunner/odoo_tests/__init__.py
  odoo_test_xmlrunner/odoo_tests/loader.py
  odoo_test_xmlrunner/pyproject.toml
  odoo_test_xmlrunner/readme/CONFIGURATION.md
  odoo_test_xmlrunner/readme/CREDITS.md
  odoo_test_xmlrunner/readme/DESCRIPTION.md
  odoo_test_xmlrunner/readme/INSTALL.md
  odoo_test_xmlrunner/readme/USAGE.md
  odoo_test_xmlrunner/requirements.txt
  odoo_test_xmlrunner/static/description/index.html
  requirements.txt
  setup/odoo_test_xmlrunner/odoo/addons/odoo_test_xmlrunner
  setup/odoo_test_xmlrunner/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2982 [17.0][MIG] fetchmail_notify_error_to_sender, fetchmail_notify_error_to_sender_test: Migration to 17.0
  fetchmail_notify_error_to_sender/README.rst
  fetchmail_notify_error_to_sender/__init__.py
  fetchmail_notify_error_to_sender/__manifest__.py
  fetchmail_notify_error_to_sender/data/email_template_data.xml
  fetchmail_notify_error_to_sender/i18n/es.po
  fetchmail_notify_error_to_sender/i18n/es_AR.po
  fetchmail_notify_error_to_sender/i18n/fetchmail_notify_error_to_sender.pot
  fetchmail_notify_error_to_sender/i18n/fr.po
  fetchmail_notify_error_to_sender/i18n/it.po
  fetchmail_notify_error_to_sender/i18n/pt_BR.po
  fetchmail_notify_error_to_sender/i18n/tr.po
  fetchmail_notify_error_to_sender/i18n/zh_CN.po
  fetchmail_notify_error_to_sender/models/__init__.py
  fetchmail_notify_error_to_sender/models/fetchmail_server.py
  fetchmail_notify_error_to_sender/models/mail_thread.py
  fetchmail_notify_error_to_sender/pyproject.toml
  fetchmail_notify_error_to_sender/readme/CONFIGURE.md
  fetchmail_notify_error_to_sender/readme/CONTRIBUTORS.md
  fetchmail_notify_error_to_sender/readme/DESCRIPTION.md
  fetchmail_notify_error_to_sender/static/description/icon.png
  fetchmail_notify_error_to_sender/static/description/index.html
  fetchmail_notify_error_to_sender/views/fetchmail_view.xml
  fetchmail_notify_error_to_sender_test/README.rst
  fetchmail_notify_error_to_sender_test/__init__.py
  fetchmail_notify_error_to_sender_test/__manifest__.py
  fetchmail_notify_error_to_sender_test/i18n/ca.po
  fetchmail_notify_error_to_sender_test/i18n/fetchmail_notify_error_to_sender_test.pot
  fetchmail_notify_error_to_sender_test/pyproject.toml
  fetchmail_notify_error_to_sender_test/readme/CONTRIBUTORS.md
  fetchmail_notify_error_to_sender_test/readme/DESCRIPTION.md
  fetchmail_notify_error_to_sender_test/static/description/icon.png
  fetchmail_notify_error_to_sender_test/static/description/index.html
  fetchmail_notify_error_to_sender_test/tests/__init__.py
  fetchmail_notify_error_to_sender_test/tests/test_fetchmail_notify_error_to_sender.py
Labels: approved, ready to merge, bot is merging ⏳

#3153 [FIX] auditlog: adapt exclude fields test to #3137
  auditlog/tests/test_auditlog.py
Labels: approved, bot is merging ⏳

#3144 [17.0][FIX] upgrade_analysis: forward ports (+ fixes)
  upgrade_analysis/README.rst
  upgrade_analysis/compare.py
  upgrade_analysis/models/upgrade_analysis.py
  upgrade_analysis/models/upgrade_comparison_config.py
  upgrade_analysis/static/description/index.html
  upgrade_analysis/tests/test_module.py
  upgrade_analysis/upgrade_log.py
  upgrade_analysis/wizards/upgrade_install_wizard.py
Labels: approved, bot is merging ⏳

#3142 [15.0][FIX] upgrade_analysis: new modules cannot be merged/renamed in same version
  upgrade_analysis/models/upgrade_analysis.py
Labels: approved, bot is merging ⏳
