Repository OCA/server-tools, pull requests merged in 2024-05, with the labels that each got.

#2931 [17.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
  base_exception/__manifest__.py
  base_exception/models/base_exception.py
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
  database_cleanup/models/purge_data.py
  module_change_auto_install/patch.py
Labels: help wanted, needs review, bot is merging ⏳

#2916 [17.0][MIG] tracking_manager
  tracking_manager/README.rst
  tracking_manager/__init__.py
  tracking_manager/__manifest__.py
  tracking_manager/i18n/es.po
  tracking_manager/i18n/fr.po
  tracking_manager/i18n/it.po
  tracking_manager/i18n/tracking_manager.pot
  tracking_manager/models/__init__.py
  tracking_manager/models/ir_model.py
  tracking_manager/models/ir_model_fields.py
  tracking_manager/models/mail_thread.py
  tracking_manager/models/mail_tracking_value.py
  tracking_manager/models/models.py
  tracking_manager/pyproject.toml
  tracking_manager/readme/CONTRIBUTORS.md
  tracking_manager/readme/DESCRIPTION.md
  tracking_manager/readme/USAGE.md
  tracking_manager/static/description/fields.png
  tracking_manager/static/description/icon.png
  tracking_manager/static/description/index.html
  tracking_manager/static/description/model_view.png
  tracking_manager/tests/__init__.py
  tracking_manager/tests/models.py
  tracking_manager/tests/test_tracking_manager.py
  tracking_manager/tools.py
  tracking_manager/views/ir_model.xml
  tracking_manager/views/ir_model_fields.xml
  tracking_manager/views/message_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#2763 [17.0][MIG] module_auto_update
  .copier-answers.yml
  .github/workflows/test.yml
  module_auto_update/README.rst
  module_auto_update/__init__.py
  module_auto_update/__manifest__.py
  module_auto_update/addon_hash.py
  module_auto_update/hooks.py
  module_auto_update/i18n/ca.po
  module_auto_update/i18n/cs_CZ.po
  module_auto_update/i18n/de.po
  module_auto_update/i18n/es.po
  module_auto_update/i18n/es_AR.po
  module_auto_update/i18n/es_MX.po
  module_auto_update/i18n/fr.po
  module_auto_update/i18n/hr.po
  module_auto_update/i18n/it.po
  module_auto_update/i18n/module_auto_update.pot
  module_auto_update/i18n/nl_NL.po
  module_auto_update/i18n/pt_BR.po
  module_auto_update/i18n/sl.po
  module_auto_update/i18n/tr.po
  module_auto_update/i18n/zh_CN.po
  module_auto_update/models/__init__.py
  module_auto_update/models/module.py
  module_auto_update/pyproject.toml
  module_auto_update/readme/CONFIGURE.md
  module_auto_update/readme/CONTRIBUTORS.md
  module_auto_update/readme/DESCRIPTION.md
  module_auto_update/readme/USAGE.md
  module_auto_update/static/description/icon.png
  module_auto_update/static/description/index.html
  module_auto_update/tests/__init__.py
  module_auto_update/tests/sample_module/README.rst
  module_auto_update/tests/sample_module/data/f1.xml
  module_auto_update/tests/sample_module/data/f2.xml
  module_auto_update/tests/sample_module/i18n/en_US.po
  module_auto_update/tests/sample_module/i18n/fr.po
  module_auto_update/tests/sample_module/i18n/fr_BE.po
  module_auto_update/tests/sample_module/i18n/test.pot
  module_auto_update/tests/sample_module/i18n_extra/en.po
  module_auto_update/tests/sample_module/i18n_extra/fr.po
  module_auto_update/tests/sample_module/i18n_extra/nl_NL.po
  module_auto_update/tests/sample_module/models/stuff.py
  module_auto_update/tests/sample_module/models/stuff.pyc
  module_auto_update/tests/sample_module/models/stuff.pyo
  module_auto_update/tests/sample_module/static/src/some.js
  module_auto_update/tests/test_addon_hash.py
  module_auto_update/tests/test_module.py
  module_auto_update/views/ir_module_module.xml
Labels: approved, bot is merging ⏳

#2923 [16] attachment synchronize : Improve remote file import management
  attachment_synchronize/demo/attachment_synchronize_task_demo.xml
  attachment_synchronize/models/attachment_synchronize_task.py
  attachment_synchronize/tests/common.py
  attachment_synchronize/tests/test_import.py
Labels: approved, ready to merge, bot is merging ⏳

#2914 [17.0][MIG] iap_alternative_provider: Migration to 17.0
  iap_alternative_provider/README.rst
  iap_alternative_provider/__init__.py
  iap_alternative_provider/__manifest__.py
  iap_alternative_provider/i18n/ca.po
  iap_alternative_provider/i18n/es.po
  iap_alternative_provider/i18n/iap_alternative_provider.pot
  iap_alternative_provider/i18n/it.po
  iap_alternative_provider/models/__init__.py
  iap_alternative_provider/models/iap_account.py
  iap_alternative_provider/pyproject.toml
  iap_alternative_provider/readme/CONTRIBUTORS.md
  iap_alternative_provider/readme/DESCRIPTION.md
  iap_alternative_provider/static/description/icon.png
  iap_alternative_provider/static/description/index.html
  iap_alternative_provider/tests/__init__.py
  iap_alternative_provider/tests/test_iap_account.py
  iap_alternative_provider/views/iap_account_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#2941 [14.0] [IMP] base_view_inheritance_extension: Add new options domain_add and text_add
  base_view_inheritance_extension/README.rst
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/readme/CONTRIBUTORS.rst
  base_view_inheritance_extension/readme/USAGE.rst
  base_view_inheritance_extension/static/description/index.html
Labels: approved, bot is merging ⏳

#2818 [17.0][MIG] sentry
  requirements.txt
  sentry/README.rst
  sentry/__init__.py
  sentry/__manifest__.py
  sentry/const.py
  sentry/generalutils.py
  sentry/hooks.py
  sentry/i18n/ca.po
  sentry/i18n/it.po
  sentry/i18n/sentry.pot
  sentry/i18n/zh_CN.po
  sentry/logutils.py
  sentry/processor.py
  sentry/pyproject.toml
  sentry/readme/CONFIGURE.md
  sentry/readme/CONTRIBUTORS.md
  sentry/readme/CREDITS.md
  sentry/readme/DESCRIPTION.md
  sentry/readme/INSTALL.md
  sentry/readme/ROADMAP.md
  sentry/readme/USAGE.md
  sentry/static/description/icon.png
  sentry/static/description/index.html
  sentry/tests/__init__.py
  sentry/tests/test_client.py
  sentry/tests/test_generalutils.py
  sentry/tests/test_logutils.py
  sentry/tests/test_processor.py
Labels: approved, ready to merge, bot is merging ⏳

#2938 [14.0] tracking_manager: non trackable field should be not tracked
  tracking_manager/__manifest__.py
  tracking_manager/migrations/14.0.1.1.0/pre-fix-none-trackable-field.py
  tracking_manager/models/ir_model.py
  tracking_manager/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#2942 [14.0] [FIX] base_view_inheritance_extension: parse old value
  base_view_inheritance_extension/models/ir_ui_view.py
Labels: bot is merging ⏳

#2886 [14.0][ADD] base_view_full_arch
  .prettierignore
  base_view_full_arch/README.rst
  base_view_full_arch/__init__.py
  base_view_full_arch/__manifest__.py
  base_view_full_arch/demo/ir_ui_view.xml
  base_view_full_arch/models/__init__.py
  base_view_full_arch/models/ir_ui_view.py
  base_view_full_arch/readme/CONTRIBUTORS.rst
  base_view_full_arch/readme/DESCRIPTION.rst
  base_view_full_arch/readme/USAGE.rst
  base_view_full_arch/static/description/index.html
  base_view_full_arch/tests/__init__.py
  base_view_full_arch/tests/data/test_00_format_doc.xml
  base_view_full_arch/tests/data/test_01_root_view_full_arch.xml
  base_view_full_arch/tests/data/test_02_ancestor_view_full_arch.xml
  base_view_full_arch/tests/data/test_04_archive_inheriting_view.xml
  base_view_full_arch/tests/data/test_05_update_views_arch_propagate_top_down_ancestor_is_v1.xml
  base_view_full_arch/tests/data/test_05_update_views_arch_propagate_top_down_ancestor_is_v3.xml
  base_view_full_arch/tests/data/test_06_update_views_arch_propagate_bottom_up_ancestor_is_v1.xml
  base_view_full_arch/tests/data/test_06_update_views_arch_propagate_bottom_up_ancestor_is_v3.xml
  base_view_full_arch/tests/test_full_arch.py
  base_view_full_arch/views/ir_ui_view.xml
  setup/base_view_full_arch/odoo/addons/base_view_full_arch
  setup/base_view_full_arch/setup.py
Labels: bot is merging ⏳

#2182 [13.0][ADD] base_search_multi
  base_search_multi/README.rst
  base_search_multi/__init__.py
  base_search_multi/__manifest__.py
  base_search_multi/models/__init__.py
  base_search_multi/models/models.py
  base_search_multi/readme/CONTRIBUTORS.rst
  base_search_multi/readme/DESCRIPTION.rst
  base_search_multi/readme/USAGE.rst
  base_search_multi/static/description/index.html
  base_search_multi/tests/__init__.py
  base_search_multi/tests/test_search_multi.py
  setup/base_search_multi/odoo/addons/base_search_multi
  setup/base_search_multi/setup.py
Labels: bot is merging ⏳

#2944 [16.0] [FIX] base_view_inheritance_extension: parse old value
  base_view_inheritance_extension/models/ir_ui_view.py
Labels: approved, bot is merging ⏳

#2943 [15.0] [FIX] base_view_inheritance_extension: parse old value
  base_view_inheritance_extension/models/ir_ui_view.py
Labels: approved, bot is merging ⏳

#2826 [17.0][MIG] upgrade_analysis
  requirements.txt
  upgrade_analysis/README.rst
  upgrade_analysis/__init__.py
  upgrade_analysis/__manifest__.py
  upgrade_analysis/blacklist.py
  upgrade_analysis/compare.py
  upgrade_analysis/i18n/es_AR.po
  upgrade_analysis/i18n/fr.po
  upgrade_analysis/i18n/upgrade_analysis.pot
  upgrade_analysis/models/__init__.py
  upgrade_analysis/models/ir_module_module.py
  upgrade_analysis/models/upgrade_analysis.py
  upgrade_analysis/models/upgrade_attribute.py
  upgrade_analysis/models/upgrade_comparison_config.py
  upgrade_analysis/models/upgrade_record.py
  upgrade_analysis/odoo_patch/__init__.py
  upgrade_analysis/odoo_patch/addons/__init__.py
  upgrade_analysis/odoo_patch/addons/mrp/__init__.py
  upgrade_analysis/odoo_patch/addons/point_of_sale/__init__.py
  upgrade_analysis/odoo_patch/addons/stock/__init__.py
  upgrade_analysis/odoo_patch/odoo/__init__.py
  upgrade_analysis/odoo_patch/odoo/addons/__init__.py
  upgrade_analysis/odoo_patch/odoo/addons/base/__init__.py
  upgrade_analysis/odoo_patch/odoo/addons/base/models/__init__.py
  upgrade_analysis/odoo_patch/odoo/addons/base/models/ir_model.py
  upgrade_analysis/odoo_patch/odoo/models.py
  upgrade_analysis/odoo_patch/odoo/modules/__init__.py
  upgrade_analysis/odoo_patch/odoo/modules/registry.py
  upgrade_analysis/odoo_patch/odoo/tools/__init__.py
  upgrade_analysis/odoo_patch/odoo/tools/convert.py
  upgrade_analysis/odoo_patch/odoo_patch.py
  upgrade_analysis/pyproject.toml
  upgrade_analysis/readme/CONTRIBUTORS.md
  upgrade_analysis/readme/DESCRIPTION.md
  upgrade_analysis/readme/ROADMAP.md
  upgrade_analysis/readme/USAGE.md
  upgrade_analysis/security/ir.model.access.csv
  upgrade_analysis/static/description/icon.png
  upgrade_analysis/static/description/index.html
  upgrade_analysis/static/src/module_coverage_template.rst.mako
  upgrade_analysis/tests/__init__.py
  upgrade_analysis/tests/test_module.py
  upgrade_analysis/upgrade_log.py
  upgrade_analysis/views/menu.xml
  upgrade_analysis/views/view_upgrade_analysis.xml
  upgrade_analysis/views/view_upgrade_comparison_config.xml
  upgrade_analysis/views/view_upgrade_record.xml
  upgrade_analysis/wizards/__init__.py
  upgrade_analysis/wizards/upgrade_generate_record_wizard.py
  upgrade_analysis/wizards/upgrade_install_wizard.py
  upgrade_analysis/wizards/view_upgrade_generate_record_wizard.xml
  upgrade_analysis/wizards/view_upgrade_install_wizard.xml
Labels: approved, bot is merging ⏳

#2946 [16.0][ADD] base_force_record_noupdate
  base_force_record_noupdate/README.rst
  base_force_record_noupdate/__init__.py
  base_force_record_noupdate/__manifest__.py
  base_force_record_noupdate/models/__init__.py
  base_force_record_noupdate/models/ir_model.py
  base_force_record_noupdate/models/ir_model_data.py
  base_force_record_noupdate/readme/CONTRIBUTORS.rst
  base_force_record_noupdate/readme/DESCRIPTION.rst
  base_force_record_noupdate/readme/USAGE.rst
  base_force_record_noupdate/static/description/icon.png
  base_force_record_noupdate/static/description/index.html
  base_force_record_noupdate/tests/__init__.py
  base_force_record_noupdate/tests/test_base_force_record_noupdate.py
  base_force_record_noupdate/views/ir_model.xml
  setup/base_force_record_noupdate/odoo/addons/base_force_record_noupdate
  setup/base_force_record_noupdate/setup.py
Labels: approved, bot is merging ⏳

#2937 [17.0][IMP] database_cleanup: purge fields (forward-port)
  database_cleanup/__manifest__.py
  database_cleanup/models/__init__.py
  database_cleanup/models/purge_fields.py
  database_cleanup/readme/CONTRIBUTORS.md
  database_cleanup/security/ir.model.access.csv
  database_cleanup/tests/__init__.py
  database_cleanup/tests/test_purge_fields.py
  database_cleanup/views/menu.xml
  database_cleanup/views/purge_fields.xml
Labels: bot is merging ⏳

#2936 [16.0][IMP] database_cleanup: purge fields (forward-port)
  database_cleanup/README.rst
  database_cleanup/__manifest__.py
  database_cleanup/models/__init__.py
  database_cleanup/models/purge_fields.py
  database_cleanup/readme/CONTRIBUTORS.rst
  database_cleanup/security/ir.model.access.csv
  database_cleanup/tests/__init__.py
  database_cleanup/tests/test_purge_fields.py
  database_cleanup/views/menu.xml
  database_cleanup/views/purge_fields.xml
Labels: bot is merging ⏳

#2948 [14.0][IMP] database_cleanup : delete also obsolete SQL views
  database_cleanup/models/purge_tables.py
  database_cleanup/views/purge_tables.xml
Labels: bot is merging ⏳

#2949 [15.0][IMP] database_cleanup : delete also obsolete SQL views
  database_cleanup/models/purge_tables.py
  database_cleanup/views/purge_tables.xml
Labels: bot is merging ⏳

#2951 [16.0][IMP] database_cleanup : delete also obsolete SQL views
  database_cleanup/models/purge_tables.py
  database_cleanup/views/purge_tables.xml
Labels: bot is merging ⏳

#2955 [17.0][IMP] database_cleanup : delete also obsolete SQL views
  database_cleanup/models/purge_tables.py
  database_cleanup/views/purge_tables.xml
Labels: bot is merging ⏳

#2663 [16.0][MIG] base_changeset
  base_changeset/README.rst
  base_changeset/__init__.py
  base_changeset/__manifest__.py
  base_changeset/demo/changeset_field_rule.xml
  base_changeset/i18n/base_changeset.pot
  base_changeset/i18n/ca.po
  base_changeset/i18n/es.po
  base_changeset/i18n/it.po
  base_changeset/models/__init__.py
  base_changeset/models/base.py
  base_changeset/models/changeset_field_rule.py
  base_changeset/models/record_changeset.py
  base_changeset/models/record_changeset_change.py
  base_changeset/readme/CONFIGURE.rst
  base_changeset/readme/CONTRIBUTORS.rst
  base_changeset/readme/DESCRIPTION.rst
  base_changeset/readme/ROADMAP.rst
  base_changeset/readme/USAGE.rst
  base_changeset/security/groups.xml
  base_changeset/security/ir.model.access.csv
  base_changeset/security/rules.xml
  base_changeset/static/description/icon.png
  base_changeset/static/description/index.html
  base_changeset/static/src/components/changeset_popover.esm.js
  base_changeset/static/src/components/changeset_popover.scss
  base_changeset/static/src/components/changeset_popover.xml
  base_changeset/static/src/components/form_label.xml
  base_changeset/static/src/components/record.esm.js
  base_changeset/static/src/img/badge.png
  base_changeset/static/src/img/badge_click.png
  base_changeset/static/src/img/changeset.png
  base_changeset/static/src/img/rules.png
  base_changeset/tests/__init__.py
  base_changeset/tests/common.py
  base_changeset/tests/test_changeset_field_rule.py
  base_changeset/tests/test_changeset_field_type.py
  base_changeset/tests/test_changeset_flow.py
  base_changeset/tests/test_changeset_origin.py
  base_changeset/tests/test_changeset_security.py
  base_changeset/views/changeset_field_rule_views.xml
  base_changeset/views/menu.xml
  base_changeset/views/record_changeset_change_views.xml
  base_changeset/views/record_changeset_views.xml
  setup/base_changeset/odoo/addons/base_changeset
  setup/base_changeset/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2811 [16.0][IMP] module_change_auto_install: also allow using environment variables
  module_change_auto_install/patch.py
  module_change_auto_install/readme/CONFIGURE.rst
  module_change_auto_install/readme/CONTRIBUTORS.rst
  module_change_auto_install/readme/INSTALL.rst
Labels: approved, ready to merge, bot is merging ⏳
