Repository OCA/server-tools, pull requests merged in 2024-04, with the labels that each got.

#2840 [15.0] [MIG] session db: Migration to 15.0
  session_db/README.rst
  session_db/__init__.py
  session_db/__manifest__.py
  session_db/i18n/session_db.pot
  session_db/pg_session_store.py
  session_db/readme/DESCRIPTION.rst
  session_db/readme/ROADMAP.rst
  session_db/readme/USAGE.rst
  session_db/static/description/icon.png
  session_db/static/description/index.html
  session_db/tests/__init__.py
  session_db/tests/test_pg_session_store.py
  setup/session_db/odoo/addons/session_db
  setup/session_db/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2849 [15.0][IMP] base_view_inheritance_extension: attrs_domain_add
  base_view_inheritance_extension/README.rst
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/readme/CONTRIBUTORS.rst
  base_view_inheritance_extension/readme/USAGE.rst
  base_view_inheritance_extension/static/description/index.html
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
Labels: bot is merging ⏳

#2289 [14.0] Add module cron_daylight_saving_time_resistant
  cron_daylight_saving_time_resistant/__init__.py
  cron_daylight_saving_time_resistant/__manifest__.py
  cron_daylight_saving_time_resistant/models/__init__.py
  cron_daylight_saving_time_resistant/models/ir_cron.py
  cron_daylight_saving_time_resistant/readme/CONFIGURE.rst
  cron_daylight_saving_time_resistant/readme/CONTRIBUTORS.rst
  cron_daylight_saving_time_resistant/readme/DESCRIPTION.rst
  cron_daylight_saving_time_resistant/tests/__init__.py
  cron_daylight_saving_time_resistant/tests/test_dst.py
  cron_daylight_saving_time_resistant/views/ir_cron_views.xml
  setup/cron_daylight_saving_time_resistant/odoo/addons/cron_daylight_saving_time_resistant
  setup/cron_daylight_saving_time_resistant/setup.py
Labels: approved, bot is merging ⏳

#2899 [16.0][FIX] cron_daylight_saving_time_resistant: Keep test savepoint
  cron_daylight_saving_time_resistant/models/ir_cron.py
  cron_daylight_saving_time_resistant/tests/test_dst.py
Labels: approved, bot is merging ⏳

#2802 [15.0][ADD] monitoring: Generic monitoring module with API
  monitoring/README.rst
  monitoring/__init__.py
  monitoring/__manifest__.py
  monitoring/controllers/__init__.py
  monitoring/controllers/main.py
  monitoring/data/ir_cron.xml
  monitoring/demo/demo_data.xml
  monitoring/models/__init__.py
  monitoring/models/monitoring.py
  monitoring/models/monitoring_script.py
  monitoring/readme/CONTRIBUTORS.rst
  monitoring/readme/DESCRIPTION.rst
  monitoring/readme/USAGE.rst
  monitoring/security/ir.model.access.csv
  monitoring/static/description/index.html
  monitoring/tests/__init__.py
  monitoring/tests/test_monitoring.py
  monitoring/views/menuitems.xml
  monitoring/views/monitoring_script_views.xml
  monitoring/views/monitoring_views.xml
  setup/monitoring/odoo/addons/monitoring
  setup/monitoring/setup.py
Labels: bot is merging ⏳

#2897 [16.0][IMP] remove python libs included in odoo requirements
  html_text/README.rst
  html_text/__manifest__.py
  html_text/static/description/index.html
  requirements.txt
Labels: bot is merging ⏳

#2813 [16.0][IMP] tracking_manager: allow tracking readonly fields
  tracking_manager/migrations/16.0.1.0.3/post-migration.py
  tracking_manager/models/ir_model.py
Labels: approved, ready to merge, bot is merging ⏳

#2901 [16][FIX] autovacuum_message_attachment : fix inheriting_model feature
  autovacuum_message_attachment/models/ir_attachment.py
Labels: approved, bot is merging ⏳

#2887 [16.0][FIX] sentry: respect sentry_logging_level (forward-port)
  sentry/const.py
  sentry/tests/test_client.py
Labels: approved, ready to merge, bot is merging ⏳

#2902 [FIX] auto_backup: TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
  auto_backup/models/db_backup.py
  auto_backup/tests/test_db_backup.py
Labels: bot is merging ⏳

#2905 [15.0][IMP] database_cleanup: purge fields (forward-port)
  database_cleanup/README.rst
  database_cleanup/__manifest__.py
  database_cleanup/models/__init__.py
  database_cleanup/models/purge_fields.py
  database_cleanup/readme/CONTRIBUTORS.rst
  database_cleanup/security/ir.model.access.csv
  database_cleanup/static/description/index.html
  database_cleanup/tests/__init__.py
  database_cleanup/tests/test_purge_fields.py
  database_cleanup/views/menu.xml
  database_cleanup/views/purge_fields.xml
Labels: approved, bot is merging ⏳

#2906 [12.0][ADD] database_cleanup purge_fields
  database_cleanup/README.rst
  database_cleanup/__manifest__.py
  database_cleanup/models/__init__.py
  database_cleanup/models/purge_fields.py
  database_cleanup/tests/__init__.py
  database_cleanup/tests/test_purge_fields.py
  database_cleanup/views/menu.xml
  database_cleanup/views/purge_fields.xml
Labels: bot is merging ⏳

#2882 [17.0][MIG] base_cron_exclusion
  base_cron_exclusion/README.rst
  base_cron_exclusion/__init__.py
  base_cron_exclusion/__manifest__.py
  base_cron_exclusion/i18n/base_cron_exclusion.pot
  base_cron_exclusion/i18n/cs_CZ.po
  base_cron_exclusion/i18n/es.po
  base_cron_exclusion/i18n/es_AR.po
  base_cron_exclusion/i18n/fr.po
  base_cron_exclusion/i18n/it.po
  base_cron_exclusion/i18n/zh_CN.po
  base_cron_exclusion/models/__init__.py
  base_cron_exclusion/models/ir_cron.py
  base_cron_exclusion/pyproject.toml
  base_cron_exclusion/readme/CONTRIBUTORS.md
  base_cron_exclusion/readme/DESCRIPTION.md
  base_cron_exclusion/readme/USAGE.md
  base_cron_exclusion/static/description/icon.png
  base_cron_exclusion/static/description/index.html
  base_cron_exclusion/views/ir_cron_view.xml
Labels: approved, bot is merging ⏳

#2913 [IMP] base_exception: Add a hook method / Don't build void exceptions
  base_exception/models/base_exception_method.py
Labels: approved, bot is merging ⏳

#2870 [17.0][MIG] base_partition: Migration to 17.0
  base_partition/README.rst
  base_partition/__init__.py
  base_partition/__manifest__.py
  base_partition/i18n/base_partition.pot
  base_partition/i18n/es.po
  base_partition/i18n/fr_BE.pot
  base_partition/i18n/it.po
  base_partition/models/__init__.py
  base_partition/models/models.py
  base_partition/pyproject.toml
  base_partition/readme/CONTRIBUTORS.md
  base_partition/readme/DESCRIPTION.md
  base_partition/static/description/icon.png
  base_partition/static/description/index.html
  base_partition/tests/__init__.py
  base_partition/tests/test_partition.py
Labels: approved, bot is merging ⏳

#2829 [MIG] bus_alt_connection: Migration to 16.0
  bus_alt_connection/README.rst
  bus_alt_connection/__init__.py
  bus_alt_connection/__manifest__.py
  bus_alt_connection/i18n/bus_alt_connection.pot
  bus_alt_connection/models/__init__.py
  bus_alt_connection/models/bus.py
  bus_alt_connection/readme/CONFIGURE.rst
  bus_alt_connection/readme/CONTRIBUTORS.rst
  bus_alt_connection/readme/DESCRIPTION.rst
  bus_alt_connection/readme/INSTALL.rst
  bus_alt_connection/static/description/icon.png
  bus_alt_connection/static/description/index.html
  setup/bus_alt_connection/odoo/addons/bus_alt_connection
  setup/bus_alt_connection/setup.py
Labels: approved, bot is merging ⏳

#2911 [16.0][IMP] Update configure for readme
  base_name_search_improved/README.rst
  base_name_search_improved/images/image1.png
  base_name_search_improved/readme/CONFIGURE.rst
  base_name_search_improved/readme/DESCRIPTION.rst
  base_name_search_improved/static/description/index.html
Labels: bot is merging ⏳

#2918 [16.0][MIG] datetime_formatter: Migration to version 16.0
  datetime_formatter/README.rst
  datetime_formatter/__init__.py
  datetime_formatter/__manifest__.py
  datetime_formatter/i18n/ar.po
  datetime_formatter/i18n/ca.po
  datetime_formatter/i18n/datetime_formatter.pot
  datetime_formatter/i18n/de.po
  datetime_formatter/i18n/es.po
  datetime_formatter/i18n/es_AR.po
  datetime_formatter/i18n/fr.po
  datetime_formatter/i18n/hr.po
  datetime_formatter/i18n/it.po
  datetime_formatter/i18n/nl_NL.po
  datetime_formatter/i18n/pt.po
  datetime_formatter/i18n/sl.po
  datetime_formatter/i18n/tr.po
  datetime_formatter/i18n/zh_CN.po
  datetime_formatter/models/__init__.py
  datetime_formatter/models/res_lang.py
  datetime_formatter/readme/CONTRIBUTORS.rst
  datetime_formatter/readme/DESCRIPTION.rst
  datetime_formatter/readme/USAGE.rst
  datetime_formatter/static/description/icon.png
  datetime_formatter/static/description/index.html
  datetime_formatter/tests/__init__.py
  datetime_formatter/tests/test_best_matcher.py
  datetime_formatter/tests/test_formatter.py
  setup/datetime_formatter/odoo/addons/datetime_formatter
  setup/datetime_formatter/setup.py
Labels: approved, bot is merging ⏳
