Repository OCA/server-tools, pull requests merged in 2024-02, with the labels that each got.

#2758 [17.0][MIG] dbfilter_from_header
  dbfilter_from_header/README.rst
  dbfilter_from_header/__init__.py
  dbfilter_from_header/__manifest__.py
  dbfilter_from_header/i18n/dbfilter_from_header.pot
  dbfilter_from_header/i18n/es_AR.po
  dbfilter_from_header/i18n/zh_CN.po
  dbfilter_from_header/override.py
  dbfilter_from_header/pyproject.toml
  dbfilter_from_header/readme/CONFIGURE.md
  dbfilter_from_header/readme/CONTRIBUTORS.md
  dbfilter_from_header/readme/DESCRIPTION.md
  dbfilter_from_header/readme/INSTALL.md
  dbfilter_from_header/readme/USAGE.md
  dbfilter_from_header/static/description/icon.png
  dbfilter_from_header/static/description/index.html
Labels: approved, bot is merging ⏳

#2806 [MIG][17.0] onchange_helper: Migration to 17.0
  onchange_helper/README.rst
  onchange_helper/__init__.py
  onchange_helper/__manifest__.py
  onchange_helper/i18n/cs_CZ.po
  onchange_helper/i18n/de.po
  onchange_helper/i18n/es.po
  onchange_helper/i18n/es_AR.po
  onchange_helper/i18n/fr.po
  onchange_helper/i18n/hr.po
  onchange_helper/i18n/it.po
  onchange_helper/i18n/onchange_helper.pot
  onchange_helper/i18n/sl.po
  onchange_helper/i18n/zh_CN.po
  onchange_helper/models/__init__.py
  onchange_helper/models/base.py
  onchange_helper/pyproject.toml
  onchange_helper/readme/CONTRIBUTORS.md
  onchange_helper/readme/DESCRIPTION.md
  onchange_helper/readme/ROADMAP.md
  onchange_helper/readme/USAGE.md
  onchange_helper/static/description/icon.png
  onchange_helper/static/description/index.html
  onchange_helper/tests/__init__.py
  onchange_helper/tests/test_onchange_helper.py
Labels: merged 🎉

#2814 [160][FIX] auditlog: prevent removal of x2many values from inaccessible companies
  auditlog/models/rule.py
  auditlog/tests/__init__.py
  auditlog/tests/test_multi_company.py
Labels: approved, ready to merge, bot is merging ⏳

#2817 [16.0][FIX] base_sequence_option: change name to editable
  base_sequence_option/models/ir_sequence_option.py
Labels: approved, ready to merge, bot is merging ⏳

#2795 [17.0][MIG] base_view_inheritance_extension
  base_view_inheritance_extension/README.rst
  base_view_inheritance_extension/__init__.py
  base_view_inheritance_extension/__manifest__.py
  base_view_inheritance_extension/demo/ir_ui_view.xml
  base_view_inheritance_extension/i18n/base_view_inheritance_extension.pot
  base_view_inheritance_extension/i18n/ca.po
  base_view_inheritance_extension/i18n/de.po
  base_view_inheritance_extension/i18n/es.po
  base_view_inheritance_extension/i18n/es_AR.po
  base_view_inheritance_extension/i18n/hr.po
  base_view_inheritance_extension/i18n/it.po
  base_view_inheritance_extension/i18n/sl.po
  base_view_inheritance_extension/i18n/tr.po
  base_view_inheritance_extension/models/__init__.py
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/pyproject.toml
  base_view_inheritance_extension/readme/CONTRIBUTORS.md
  base_view_inheritance_extension/readme/DESCRIPTION.md
  base_view_inheritance_extension/readme/ROADMAP.md
  base_view_inheritance_extension/readme/USAGE.md
  base_view_inheritance_extension/static/description/icon.png
  base_view_inheritance_extension/static/description/index.html
  base_view_inheritance_extension/tests/__init__.py
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#2797 [17.0][MIG] scheduler_error_mailer: Migration to 17.0
  scheduler_error_mailer/README.rst
  scheduler_error_mailer/__init__.py
  scheduler_error_mailer/__manifest__.py
  scheduler_error_mailer/data/ir_cron_email_tpl.xml
  scheduler_error_mailer/demo/ir_cron_demo.xml
  scheduler_error_mailer/hooks.py
  scheduler_error_mailer/i18n/de.po
  scheduler_error_mailer/i18n/es.po
  scheduler_error_mailer/i18n/es_AR.po
  scheduler_error_mailer/i18n/fr.po
  scheduler_error_mailer/i18n/hr.po
  scheduler_error_mailer/i18n/pt.po
  scheduler_error_mailer/i18n/pt_BR.po
  scheduler_error_mailer/i18n/scheduler_error_mailer.pot
  scheduler_error_mailer/i18n/sl.po
  scheduler_error_mailer/i18n/zh_CN.po
  scheduler_error_mailer/images/scheduler_error_mailer.jpg
  scheduler_error_mailer/models/__init__.py
  scheduler_error_mailer/models/ir_cron.py
  scheduler_error_mailer/pyproject.toml
  scheduler_error_mailer/readme/CONFIGURE.md
  scheduler_error_mailer/readme/CONTRIBUTORS.md
  scheduler_error_mailer/readme/DESCRIPTION.md
  scheduler_error_mailer/static/description/icon.png
  scheduler_error_mailer/static/description/index.html
  scheduler_error_mailer/tests/__init__.py
  scheduler_error_mailer/tests/test_scheduler_error_mailer.py
  scheduler_error_mailer/views/ir_cron.xml
Labels: approved, ready to merge, bot is merging ⏳

#2766 [16][MIG] autovacuum_message_attachment
  autovacuum_message_attachment/README.rst
  autovacuum_message_attachment/__init__.py
  autovacuum_message_attachment/__manifest__.py
  autovacuum_message_attachment/data/data.xml
  autovacuum_message_attachment/i18n/autovacuum_mail_message.pot
  autovacuum_message_attachment/i18n/autovacuum_message_attachment.pot
  autovacuum_message_attachment/i18n/ca.po
  autovacuum_message_attachment/i18n/es_AR.po
  autovacuum_message_attachment/i18n/fr.po
  autovacuum_message_attachment/models/__init__.py
  autovacuum_message_attachment/models/autovacuum_mixin.py
  autovacuum_message_attachment/models/base.py
  autovacuum_message_attachment/models/ir_attachment.py
  autovacuum_message_attachment/models/mail_message.py
  autovacuum_message_attachment/models/vacuum_rule.py
  autovacuum_message_attachment/readme/CONFIGURE.rst
  autovacuum_message_attachment/readme/CONTRIBUTORS.rst
  autovacuum_message_attachment/readme/DESCRIPTION.rst
  autovacuum_message_attachment/readme/ROADMAP.rst
  autovacuum_message_attachment/security/ir.model.access.csv
  autovacuum_message_attachment/static/description/icon.png
  autovacuum_message_attachment/static/description/index.html
  autovacuum_message_attachment/tests/__init__.py
  autovacuum_message_attachment/tests/test_vacuum_rule.py
  autovacuum_message_attachment/views/rule_vacuum.xml
  setup/autovacuum_message_attachment/odoo/addons/autovacuum_message_attachment
  setup/autovacuum_message_attachment/setup.py
Labels: approved, bot is merging ⏳

#2762 [16.0][FIX] jsonifier: Call callable for unknown field
  jsonifier/models/models.py
  jsonifier/tests/test_get_parser.py
  module_auto_update/tests/sample_module/models/stuff.pyc
Labels: bot is merging ⏳

#2825 [16.0][IMP] upgrade_analysis: fix reinstall of sale_quotation_builder
  upgrade_analysis/odoo_patch/addons/__init__.py
  upgrade_analysis/odoo_patch/addons/sale_quotation_builder/__init__.py
Labels: bot is merging ⏳

#2353 [14.0][FIX] dbs value has to be kept in case of special dbfilter config
  dbfilter_from_header/override.py
Labels: approved, bot is merging ⏳

#2703 [16.0][MIG] url_attachment_search_fuzzy: Migration to 16.0
  setup/url_attachment_search_fuzzy/odoo/addons/url_attachment_search_fuzzy
  setup/url_attachment_search_fuzzy/setup.py
  url_attachment_search_fuzzy/README.rst
  url_attachment_search_fuzzy/__init__.py
  url_attachment_search_fuzzy/__manifest__.py
  url_attachment_search_fuzzy/data/url_attachment_index.xml
  url_attachment_search_fuzzy/readme/CONFIGURE.rst
  url_attachment_search_fuzzy/readme/CONTRIBUTORS.rst
  url_attachment_search_fuzzy/readme/DESCRIPTION.rst
  url_attachment_search_fuzzy/readme/INSTALL.rst
  url_attachment_search_fuzzy/static/description/icon.png
  url_attachment_search_fuzzy/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#2823 FIX attach_queue: state_message in form view
  attachment_queue/views/attachment_queue_view.xml
Labels: approved, bot is merging ⏳

#2828 [16.0][FIX] dbs value has to be kept in case of special proxy config
  dbfilter_from_header/override.py
Labels: approved, bot is merging ⏳

#2824 [16.0][IMP] base_view_inheritance_extension: attrs_domain_add
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/readme/CONTRIBUTORS.rst
  base_view_inheritance_extension/readme/USAGE.rst
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
Labels: approved, ready to merge, bot is merging ⏳

#2733 [12.0][FIX] sentry: Patch odoo.service.server wsgi app
  sentry/hooks.py
Labels: approved, bot is merging ⏳

#2836 [15.0][FIX] Missing fontawesome icons in some browsers
  base_fontawesome/static/src/css/fontawesome.css
Labels: approved, bot is merging ⏳

#2633 [12.0][IMP] excel_import_export: Export multiple files as files.zip
  excel_import_export/models/common.py
  excel_import_export/models/xlsx_export.py
  excel_import_export/models/xlsx_import.py
  excel_import_export/wizard/export_xlsx_wizard.py
  excel_import_export/wizard/export_xlsx_wizard.xml
  excel_import_export_demo/import_export_sale_order/actions.xml
  excel_import_export_demo/tests/test_xlsx_import_export.py
Labels: approved, bot is merging ⏳

#2287 [12.0] IMP base_model_restrict_update: readonly users can create wizards
  base_model_restrict_update/models/ir_model.py
  base_model_restrict_update/models/ir_model_access.py
  base_model_restrict_update/readme/CONFIGURE.rst
  base_model_restrict_update/tests/test_base_model_restrict_update.py
  base_model_restrict_update/views/ir_model_views.xml
Labels: approved, bot is merging ⏳

#2455 [MIG] cron_inactivity_period: Migration to 12.0
  cron_inactivity_period/__init__.py
  cron_inactivity_period/__manifest__.py
  cron_inactivity_period/demo/res_groups.xml
  cron_inactivity_period/i18n/cron_inactivity_period.pot
  cron_inactivity_period/i18n/fr.po
  cron_inactivity_period/models/__init__.py
  cron_inactivity_period/models/ir_cron.py
  cron_inactivity_period/models/ir_cron_inactivity_period.py
  cron_inactivity_period/readme/CONFIGURE.rst
  cron_inactivity_period/readme/CONTRIBUTORS.rst
  cron_inactivity_period/readme/DESCRIPTION.rst
  cron_inactivity_period/readme/ROADMAP.rst
  cron_inactivity_period/security/ir.model.access.csv
  cron_inactivity_period/static/description/icon.png
  cron_inactivity_period/static/description/ir_cron_form.png
  cron_inactivity_period/tests/__init__.py
  cron_inactivity_period/tests/test_module.py
  cron_inactivity_period/views/ir_cron.xml
  setup/cron_inactivity_period/odoo/addons/cron_inactivity_period
  setup/cron_inactivity_period/setup.py
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#2237 [FIX][12.0] base_changeset: fix write return type
  base_changeset/models/base.py
Labels: bot is merging ⏳

#2204 [12.0][MIG] Profiler from 11.0
  profiler/README.rst
  profiler/__init__.py
  profiler/__manifest__.py
  profiler/hooks.py
  profiler/i18n/profiler.pot
  profiler/models/__init__.py
  profiler/models/profiler_profile.py
  profiler/readme/CONTRIBUTORS.rst
  profiler/readme/DESCRIPTION.rst
  profiler/readme/INSTALL.rst
  profiler/readme/USAGE.rst
  profiler/security/ir.model.access.csv
  profiler/static/description/icon.png
  profiler/static/src/js/tour.js
  profiler/tests/__init__.py
  profiler/tests/test_profiling.py
  profiler/tests/test_profiling_ui.py
  profiler/views/assets.xml
  profiler/views/profiler_profile_view.xml
  setup/profiler/odoo/addons/profiler
  setup/profiler/setup.py
Labels: bot is merging ⏳

#1657 [12.0] IMP dbfilter_from_header allowing to use hostname (%h) or the first subdomain (%d)…
  dbfilter_from_header/override.py
  dbfilter_from_header/readme/CONFIGURE.rst
  dbfilter_from_header/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#2295 [12.0] database_cleanup: refactor tests file
  database_cleanup/tests/test_database_cleanup.py
Labels: needs review, bot is merging ⏳

#2841 [FIX] dbfilter_from_header issue when header does not exist
  dbfilter_from_header/override.py
Labels: bot is merging ⏳

#2843 [12.0][UPD] module_auto_update: enable test that got disabled
  module_auto_update/tests/test_addon_hash.py
Labels: bot is merging ⏳

#2847 [16.0][UPD] module_auto_update: enable test that got disabled
  module_auto_update/tests/test_addon_hash.py
Labels: bot is merging ⏳

#2845 [14.0][UPD] module_auto_update: enable test that got disabled
  module_auto_update/tests/test_addon_hash.py
Labels: bot is merging ⏳

#2839 FIX excel_imp_ex_demo: prevent native menu behavior to be inhibited
  excel_import_export_demo/report_action/partner_list/report_partner_list.xml
Labels: approved, bot is merging ⏳

#2844 [13.0][UPD] module_auto_update: enable test that got disabled
  module_auto_update/tests/test_addon_hash.py
Labels: bot is merging ⏳

#2480 [15.0][MIG] sequence_python
  sequence_python/README.rst
  sequence_python/__init__.py
  sequence_python/__manifest__.py
  sequence_python/i18n/ca.po
  sequence_python/i18n/es_AR.po
  sequence_python/i18n/sequence_python.pot
  sequence_python/models/__init__.py
  sequence_python/models/ir_sequence.py
  sequence_python/readme/CONTRIBUTORS.rst
  sequence_python/readme/DESCRIPTION.rst
  sequence_python/readme/USAGE.rst
  sequence_python/static/description/icon.png
  sequence_python/static/description/index.html
  sequence_python/tests/__init__.py
  sequence_python/tests/test_ir_sequence.py
  sequence_python/views/ir_sequence.xml
  setup/sequence_python/odoo/addons/sequence_python
  setup/sequence_python/setup.py
Labels: migration, bot is merging ⏳

#2690 [ADD][14.0] new module: base_order_by_related
  base_order_by_related/README.rst
  base_order_by_related/__init__.py
  base_order_by_related/__manifest__.py
  base_order_by_related/models/__init__.py
  base_order_by_related/models/models.py
  base_order_by_related/readme/CONTRIBUTORS.rst
  base_order_by_related/readme/DESCRIPTION.rst
  base_order_by_related/readme/USAGE.rst
  base_order_by_related/tests/__init__.py
  base_order_by_related/tests/fake_models.py
  base_order_by_related/tests/test_order_by_related.py
  setup/base_order_by_related/odoo/addons/base_order_by_related
  setup/base_order_by_related/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#2837 [11.0][UPD] dotfiles, fix tests
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .oca_hooks.cfg
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  attachment_base_synchronize/__manifest__.py
  auditlog/__manifest__.py
  auto_backup/__manifest__.py
  base_exception/__manifest__.py
  base_fontawesome/__manifest__.py
  base_remote/__manifest__.py
  base_search_fuzzy/__manifest__.py
  base_technical_user/__manifest__.py
  base_view_inheritance_extension/__manifest__.py
  company_country/__manifest__.py
  company_country/tests/test_company_country.py
  database_cleanup/__manifest__.py
  datetime_formatter/__manifest__.py
  dbfilter_from_header/__manifest__.py
  dead_mans_switch_client/__manifest__.py
  dead_mans_switch_client/models/__init__.py
  dead_mans_switch_client/tests/__init__.py
  letsencrypt/__manifest__.py
  letsencrypt/tests/test_letsencrypt.py
  mail_template_attachment_i18n/__manifest__.py
  module_auto_update/tests/sample_module/i18n/en.po
  module_auto_update/tests/sample_module/i18n/en_US.po
  module_auto_update/tests/sample_module/i18n/fr.po
  module_auto_update/tests/sample_module/i18n/fr_BE.po
  module_auto_update/tests/sample_module/i18n/test.pot
  module_auto_update/tests/sample_module/i18n_extra/en.po
  module_auto_update/tests/sample_module/i18n_extra/fr.po
  module_auto_update/tests/sample_module/i18n_extra/nl_NL.po
  module_auto_update/tests/sample_module/models/stuff.py
  module_auto_update/tests/test_addon_hash.py
  nsca_client/__manifest__.py
  profiler/__manifest__.py
  requirements.txt
  scheduler_error_mailer/__manifest__.py
  sentry/__manifest__.py
  sql_request_abstract/__manifest__.py
  test_mail_template_attachment_i18n/__manifest__.py
  users_ldap_groups/models/res_users.py
  users_ldap_groups/readme/CONTRIBUTORS.rst
  users_ldap_groups/readme/DESCRIPTION.rst
  users_ldap_groups/readme/USAGE.rst
Labels: approved, bot is merging ⏳

#2834 [16.0][FIX] audit_log: fix regression (Add/Remove User Group)
  auditlog/models/rule.py
  auditlog/tests/test_auditlog.py
Labels: approved, ready to merge, bot is merging ⏳

#2850 [FIX][12.0] cron_inactivity_period: prevent tests failing at just before midnight
  cron_inactivity_period/tests/test_module.py
Labels: bot is merging ⏳

#2852 [FIX][16.0] database_cleanup - Prevent deletion of columns added in the init method of the model.
  database_cleanup/README.rst
  database_cleanup/models/purge_columns.py
  database_cleanup/readme/CONTRIBUTORS.rst
  database_cleanup/static/description/index.html
Labels: bot is merging ⏳

#2846 [15.0][UPD] module_auto_update: enable test that got disabled
  module_auto_update/tests/test_addon_hash.py
Labels: bot is merging ⏳

#2596 [14.0][PORT] session_db 2593 from 13.0
  session_db/pg_session_store.py
  session_db/tests/__init__.py
  session_db/tests/test_pg_session_store.py
Labels: bot is merging ⏳

#2858 [12.0][IMP] module_analysis: Remove automatic analyse at installation and update
  module_analysis/__init__.py
  module_analysis/__manifest__.py
  module_analysis/data/ir_cron.xml
  module_analysis/models/__init__.py
  module_analysis/models/base_module_update.py
  module_analysis/models/ir_module_module.py
  module_analysis/post_init_hook.py
  module_analysis/readme/CONFIGURE.rst
  module_analysis/tests/test_module.py
  module_analysis/views/view_base_module_update.xml
Labels: bot is merging ⏳

#2861 [14.0][MIG] profiler
  profiler/README.rst
  profiler/__init__.py
  profiler/__manifest__.py
  profiler/hooks.py
  profiler/i18n/profiler.pot
  profiler/models/__init__.py
  profiler/models/profiler_profile.py
  profiler/readme/CONTRIBUTORS.rst
  profiler/readme/DESCRIPTION.rst
  profiler/readme/INSTALL.rst
  profiler/readme/USAGE.rst
  profiler/security/ir.model.access.csv
  profiler/static/description/icon.png
  profiler/static/description/index.html
  profiler/tests/__init__.py
  profiler/tests/test_profiling.py
  profiler/views/profiler_profile_view.xml
  setup/profiler/odoo/addons/profiler
  setup/profiler/setup.py
Labels: bot is merging ⏳

#2859 [12.0][DEL] profiler: tour test
  profiler/__manifest__.py
  profiler/static/src/js/tour.js
  profiler/tests/__init__.py
  profiler/tests/test_profiling.py
  profiler/tests/test_profiling_ui.py
  profiler/views/assets.xml
Labels: bot is merging ⏳

#2862 [13.0][IMP] module_analysis: Remove automatic analyse at installation and update
  module_analysis/__init__.py
  module_analysis/__manifest__.py
  module_analysis/data/ir_cron.xml
  module_analysis/models/__init__.py
  module_analysis/models/base_module_update.py
  module_analysis/models/ir_module_module.py
  module_analysis/post_init_hook.py
  module_analysis/readme/CONFIGURE.rst
  module_analysis/tests/test_module.py
  module_analysis/views/view_base_module_update.xml
Labels: needs review, approved, bot is merging ⏳
