Repository OCA/server-tools, pull requests merged in 2024-09, with the labels that each got.

#2644 16.0[MIG] base_conditional_image: Migration to 16.0
  base_conditional_image/README.rst
  base_conditional_image/__init__.py
  base_conditional_image/__manifest__.py
  base_conditional_image/i18n/base_conditional_image.pot
  base_conditional_image/i18n/es_AR.po
  base_conditional_image/models/__init__.py
  base_conditional_image/models/conditional_image.py
  base_conditional_image/models/conditional_image_consumer_mixin.py
  base_conditional_image/readme/CONTRIBUTORS.rst
  base_conditional_image/readme/CREDITS.rst
  base_conditional_image/readme/DESCRIPTION.rst
  base_conditional_image/readme/INSTALL.rst
  base_conditional_image/readme/USAGE.rst
  base_conditional_image/security/ir.model.access.csv
  base_conditional_image/static/description/icon.png
  base_conditional_image/static/description/index.html
  base_conditional_image/views/image_view.xml
  setup/base_conditional_image/odoo/addons/base_conditional_image
  setup/base_conditional_image/setup.py
Labels: bot is merging ⏳

#3025 [16.0][FIX] tracking_manager: Avoid sending tracking o2m emails if you are subscribed to notes
  tracking_manager/models/models.py
Labels: approved, bot is merging ⏳

#3027 [17.0][FIX] tracking_manager: Avoid sending tracking o2m emails if you are subscribed to notes
  tracking_manager/models/models.py
Labels: approved, bot is merging ⏳

#3026 [16] attachment synchronize Use cat_file instead of opening and reading
  attachment_synchronize/models/attachment_synchronize_task.py
Labels: approved, ready to merge, bot is merging ⏳

#2888 [14.0] backport fix setting logging level event sent
  sentry/const.py
  sentry/tests/test_client.py
Labels: approved, bot is merging ⏳

#3031 Migrate module_analysis to v17
  module_analysis/README.rst
  module_analysis/__init__.py
  module_analysis/__manifest__.py
  module_analysis/data/ir_config_parameter.xml
  module_analysis/data/ir_cron.xml
  module_analysis/data/ir_module_type.xml
  module_analysis/data/ir_module_type_rule.xml
  module_analysis/i18n/es.po
  module_analysis/i18n/it.po
  module_analysis/i18n/module_analysis.pot
  module_analysis/i18n/zh_CN.po
  module_analysis/models/__init__.py
  module_analysis/models/ir_module_author.py
  module_analysis/models/ir_module_module.py
  module_analysis/models/ir_module_type.py
  module_analysis/models/ir_module_type_rule.py
  module_analysis/pyproject.toml
  module_analysis/readme/CONFIGURE.md
  module_analysis/readme/CONTRIBUTORS.md
  module_analysis/readme/DESCRIPTION.md
  module_analysis/readme/INSTALL.md
  module_analysis/readme/USAGE.md
  module_analysis/security/ir.model.access.csv
  module_analysis/static/description/add_module_type_rules.png
  module_analysis/static/description/analysis_pie.png
  module_analysis/static/description/analysis_pivot.png
  module_analysis/static/description/config_parameters.png
  module_analysis/static/description/default_module_type_rules.png
  module_analysis/static/description/icon.png
  module_analysis/static/description/index.html
  module_analysis/static/description/installed_modules_by_types.png
  module_analysis/static/description/module_authors.png
  module_analysis/static/description/module_form.png
  module_analysis/static/description/module_types.png
  module_analysis/tests/__init__.py
  module_analysis/tests/test_module.py
  module_analysis/views/menu.xml
  module_analysis/views/view_ir_module_author.xml
  module_analysis/views/view_ir_module_module.xml
  module_analysis/views/view_ir_module_type.xml
  module_analysis/views/view_ir_module_type_rule.xml
  requirements.txt
Labels: approved, bot is merging ⏳

#2996 [12.0][FIX] sentry: Sentry sdk removed text_type from _compat utils
  requirements.txt
  setup/sentry/setup.py
Labels: bot is merging ⏳

#2988 [17.0][FW][FIX] database_cleanup: Bug introduced by #2098
  database_cleanup/models/purge_tables.py
Labels: approved, bot is merging ⏳

#2754 [17.0][MIG] session_db
  session_db/README.rst
  session_db/__init__.py
  session_db/__manifest__.py
  session_db/i18n/session_db.pot
  session_db/pg_session_store.py
  session_db/pyproject.toml
  session_db/readme/DESCRIPTION.md
  session_db/readme/USAGE.md
  session_db/static/description/icon.png
  session_db/static/description/index.html
  session_db/tests/__init__.py
  session_db/tests/test_pg_session_store.py
Labels: approved, bot is merging ⏳

#3038 [16][FIX] attachment_queue : fix default channel name
  attachment_queue/models/attachment_queue.py
Labels: approved, bot is merging ⏳

#3035 [16.0][IMP] excel_import_export: improve error showing
  excel_import_export/models/xlsx_import.py
Labels: approved, bot is merging ⏳
