Repository OCA/server-tools, pull requests merged in 2024-10, with the labels that each got.

#3048 [16.0][FIX] tracking_manager: Avoid error if no record is linked (example: child_ids of res.partner)
  tracking_manager/models/models.py
Labels: approved, bot is merging ⏳

#3049 [17.0][FIX] tracking_manager: Avoid error if no record is linked (example: child_ids of res.partner)
  tracking_manager/models/models.py
Labels: approved, bot is merging ⏳

#3051 [16.0][FIX] tracking_manager: Avoid error when accessing the value of a field that we do not have access
  tracking_manager/models/models.py
  tracking_manager/tests/test_tracking_manager.py
Labels: approved, bot is merging ⏳

#3056 [16.0][FIX] tracking_manager: Test compatibility
  tracking_manager/tests/test_tracking_manager.py
Labels: bot is merging ⏳

#3060 [17.0][FIX] tracking_manager: Avoid error when accessing the value of a field that we do not have access
  tracking_manager/models/models.py
  tracking_manager/tests/test_tracking_manager.py
Labels: approved, bot is merging ⏳

#2977 [16.0][FIX] base_name_search_improved: don't patch abstract models
  base_name_search_improved/models/ir_model.py
Labels: approved, ready to merge, bot is merging ⏳

#3053 [18.0][MIG] jsonifier: Migration to 18.0
  jsonifier/README.rst
  jsonifier/__init__.py
  jsonifier/__manifest__.py
  jsonifier/demo/export_demo.xml
  jsonifier/demo/ir.exports.line.csv
  jsonifier/demo/resolver_demo.xml
  jsonifier/exceptions.py
  jsonifier/i18n/ca.po
  jsonifier/i18n/es.po
  jsonifier/i18n/it.po
  jsonifier/i18n/jsonifier.pot
  jsonifier/i18n/zh_CN.po
  jsonifier/models/__init__.py
  jsonifier/models/ir_exports.py
  jsonifier/models/ir_exports_line.py
  jsonifier/models/ir_exports_resolver.py
  jsonifier/models/models.py
  jsonifier/models/utils.py
  jsonifier/pyproject.toml
  jsonifier/readme/CONTRIBUTORS.md
  jsonifier/readme/CREDITS.md
  jsonifier/readme/DESCRIPTION.md
  jsonifier/readme/USAGE.md
  jsonifier/security/ir.model.access.csv
  jsonifier/static/description/icon.png
  jsonifier/static/description/index.html
  jsonifier/tests/__init__.py
  jsonifier/tests/test_get_parser.py
  jsonifier/tests/test_helpers.py
  jsonifier/tests/test_ir_exports_line.py
  jsonifier/views/ir_exports_resolver_view.xml
  jsonifier/views/ir_exports_view.xml
Labels: bot is merging ⏳

#3052 [18.0][MIG] onchange_helper: Migration to 18.0
  onchange_helper/README.rst
  onchange_helper/__init__.py
  onchange_helper/__manifest__.py
  onchange_helper/i18n/cs_CZ.po
  onchange_helper/i18n/de.po
  onchange_helper/i18n/es.po
  onchange_helper/i18n/es_AR.po
  onchange_helper/i18n/fr.po
  onchange_helper/i18n/hr.po
  onchange_helper/i18n/it.po
  onchange_helper/i18n/onchange_helper.pot
  onchange_helper/i18n/sl.po
  onchange_helper/i18n/zh_CN.po
  onchange_helper/models/__init__.py
  onchange_helper/models/base.py
  onchange_helper/pyproject.toml
  onchange_helper/readme/CONTRIBUTORS.md
  onchange_helper/readme/CREDITS.md
  onchange_helper/readme/DESCRIPTION.md
  onchange_helper/readme/ROADMAP.md
  onchange_helper/readme/USAGE.md
  onchange_helper/static/description/icon.png
  onchange_helper/static/description/index.html
  onchange_helper/tests/__init__.py
  onchange_helper/tests/test_onchange_helper.py
Labels: bot is merging ⏳

#3062 [17.0][FIX] tracking_manager: m2m data was tracked as None->None
  tracking_manager/models/__init__.py
  tracking_manager/models/mail_tracking_value.py
  tracking_manager/tests/test_tracking_manager.py
Labels: approved, bot is merging ⏳

#3081 [14.0][FIX] module_analysis: interpret exclude_directories as relative to module's folder
  module_analysis/models/ir_module_module.py
Labels: bot is merging ⏳

#3082 [15.0][FIX] module_analysis: interpret exclude_directories as relative to module's folder
  module_analysis/models/ir_module_module.py
Labels: bot is merging ⏳

#3080 [13.0][FIX] module_analysis: interpret exclude_directories as relative to module's folder
  module_analysis/models/ir_module_module.py
Labels: bot is merging ⏳

#3079 [12.0][FIX] module_analysis: interpret exclude_directories as relative to module's folder
  module_analysis/models/ir_module_module.py
Labels: bot is merging ⏳

#3089 [16.0][FIX] auto_backup: Don't complain on existing folder
  auto_backup/models/db_backup.py
  auto_backup/tests/test_db_backup.py
Labels: bot is merging ⏳

#2739 [16.0][FIX] upgrade_analysis: blacklist + no reinstall + UI tweaks
  letsencrypt/tests/__init__.py
  upgrade_analysis/blacklist.py
  upgrade_analysis/tests/test_module.py
  upgrade_analysis/views/view_upgrade_analysis.xml
  upgrade_analysis/views/view_upgrade_record.xml
  upgrade_analysis/wizards/upgrade_install_wizard.py
  upgrade_analysis/wizards/view_upgrade_generate_record_wizard.xml
  upgrade_analysis/wizards/view_upgrade_install_wizard.xml
Labels: approved, bot is merging ⏳

#3088 [17.0][FIX] auditlog: registry propagation
  auditlog/models/rule.py
Labels: approved, bot is merging ⏳

#3036 [16][IMP] attachment_queue automatic retry
  attachment_queue/models/attachment_queue.py
  attachment_synchronize/models/attachment_queue.py
Labels: approved, bot is merging ⏳

#3033 [17.0][MIG] base_m2m_custom_field: Migration to 17.0
  base_m2m_custom_field/README.rst
  base_m2m_custom_field/__init__.py
  base_m2m_custom_field/__manifest__.py
  base_m2m_custom_field/fields.py
  base_m2m_custom_field/i18n/base_m2m_custom_field.pot
  base_m2m_custom_field/pyproject.toml
  base_m2m_custom_field/readme/CONTRIBUTORS.md
  base_m2m_custom_field/readme/DESCRIPTION.md
  base_m2m_custom_field/readme/USAGE.md
  base_m2m_custom_field/static/description/icon.png
  base_m2m_custom_field/static/description/index.html
Labels: approved, bot is merging ⏳

#3090 [17.0][FIX] upgrade_analysis: fix constraint logging
  .pre-commit-config.yaml
  upgrade_analysis/odoo_patch/odoo/addons/base/models/ir_model.py
  upgrade_analysis/tests/test_module.py
Labels: approved, bot is merging ⏳

#3055 [18.0][MIG] module_change_auto_install: Migration to 18.0
  module_change_auto_install/README.rst
  module_change_auto_install/__init__.py
  module_change_auto_install/__manifest__.py
  module_change_auto_install/i18n/ca.po
  module_change_auto_install/i18n/fr.po
  module_change_auto_install/i18n/it.po
  module_change_auto_install/i18n/module_change_auto_install.pot
  module_change_auto_install/patch.py
  module_change_auto_install/pyproject.toml
  module_change_auto_install/readme/CONFIGURE.md
  module_change_auto_install/readme/CONTRIBUTORS.md
  module_change_auto_install/readme/DESCRIPTION.md
  module_change_auto_install/readme/DEVELOP.md
  module_change_auto_install/readme/INSTALL.md
  module_change_auto_install/static/description/icon.png
  module_change_auto_install/static/description/index.html
  module_change_auto_install/tests/__init__.py
  module_change_auto_install/tests/test_module.py
Labels: approved, ready to merge, bot is merging ⏳
