Repository OCA/server-tools, pull requests merged in 2024-01, with the labels that each got.

#2796 FIX module_change_auto_install: typo
  module_change_auto_install/patch.py
Labels: bot is merging ⏳

#2789 [16.0][MIG] tracking_manager
  .github/workflows/test.yml
  setup/tracking_manager/odoo/addons/tracking_manager
  setup/tracking_manager/setup.py
  tracking_manager/README.rst
  tracking_manager/__init__.py
  tracking_manager/__manifest__.py
  tracking_manager/i18n/fr.po
  tracking_manager/i18n/tracking_manager.pot
  tracking_manager/models/__init__.py
  tracking_manager/models/ir_model.py
  tracking_manager/models/mail_thread.py
  tracking_manager/models/mail_tracking_value.py
  tracking_manager/models/models.py
  tracking_manager/readme/CONTRIBUTORS.rst
  tracking_manager/readme/DESCRIPTION.rst
  tracking_manager/readme/USAGE.rst
  tracking_manager/static/description/fields.png
  tracking_manager/static/description/icon.png
  tracking_manager/static/description/index.html
  tracking_manager/static/description/model_view.png
  tracking_manager/tests/__init__.py
  tracking_manager/tests/models.py
  tracking_manager/tests/test_tracking_manager.py
  tracking_manager/tools.py
  tracking_manager/views/ir_model.xml
  tracking_manager/views/ir_model_fields.xml
  tracking_manager/views/message_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#2805 [MIG][17.0] base_technical_user: Migration to 17.0
  base_technical_user/README.rst
  base_technical_user/__init__.py
  base_technical_user/__manifest__.py
  base_technical_user/i18n/ar.po
  base_technical_user/i18n/base_technical_user.pot
  base_technical_user/i18n/de.po
  base_technical_user/i18n/es.po
  base_technical_user/i18n/fr.po
  base_technical_user/i18n/hr.po
  base_technical_user/i18n/it.po
  base_technical_user/i18n/nl_NL.po
  base_technical_user/i18n/pt.po
  base_technical_user/i18n/zh_CN.po
  base_technical_user/models/__init__.py
  base_technical_user/models/models.py
  base_technical_user/models/res_company.py
  base_technical_user/pyproject.toml
  base_technical_user/readme/CONTRIBUTORS.md
  base_technical_user/readme/DESCRIPTION.md
  base_technical_user/readme/USAGE.md
  base_technical_user/static/description/icon.png
  base_technical_user/static/description/index.html
  base_technical_user/tests/__init__.py
  base_technical_user/tests/test_sudo_tech.py
  base_technical_user/views/res_company_view.xml
Labels: bot is merging ⏳

#2803 [UPD] Upgrade to FontAwesome 6.5.1
  base_fontawesome/README.rst
  base_fontawesome/__manifest__.py
  base_fontawesome/readme/DESCRIPTION.rst
  base_fontawesome/static/description/index.html
  base_fontawesome/static/lib/fontawesome-5.15.4/css/all.css
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-brands-400.eot
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-brands-400.svg
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-brands-400.ttf
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-brands-400.woff
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-brands-400.woff2
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-regular-400.eot
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-regular-400.svg
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-regular-400.ttf
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-regular-400.woff
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-regular-400.woff2
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-solid-900.eot
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-solid-900.svg
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-solid-900.ttf
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-solid-900.woff
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-solid-900.woff2
  base_fontawesome/static/lib/fontawesome-6.5.1/css/all.css
  base_fontawesome/static/lib/fontawesome-6.5.1/css/v4-shims.css
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-brands-400.ttf
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-brands-400.woff2
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-regular-400.ttf
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-regular-400.woff2
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-solid-900.ttf
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-solid-900.woff2
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-v4compatibility.ttf
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-v4compatibility.woff2
  base_fontawesome/static/src/css/fontawesome.css
  base_fontawesome/templates/assets.xml
Labels: bot is merging ⏳

#2787 [15.0] [UPD] Upgrade to FontAwesome 6.5.1
  base_fontawesome/README.rst
  base_fontawesome/__manifest__.py
  base_fontawesome/readme/DESCRIPTION.rst
  base_fontawesome/static/description/index.html
  base_fontawesome/static/lib/fontawesome-5.15.4/css/all.css
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-brands-400.eot
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-brands-400.svg
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-brands-400.ttf
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-brands-400.woff
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-brands-400.woff2
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-regular-400.eot
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-regular-400.svg
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-regular-400.ttf
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-regular-400.woff
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-regular-400.woff2
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-solid-900.eot
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-solid-900.svg
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-solid-900.ttf
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-solid-900.woff
  base_fontawesome/static/lib/fontawesome-5.15.4/webfonts/fa-solid-900.woff2
  base_fontawesome/static/lib/fontawesome-6.5.1/css/all.css
  base_fontawesome/static/lib/fontawesome-6.5.1/css/v4-shims.css
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-brands-400.ttf
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-brands-400.woff2
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-regular-400.ttf
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-regular-400.woff2
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-solid-900.ttf
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-solid-900.woff2
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-v4compatibility.ttf
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-v4compatibility.woff2
  base_fontawesome/static/src/css/fontawesome.css
  base_fontawesome/templates/assets.xml
Labels: approved, bot is merging ⏳

#2801 [17.0][MIG] jsonifier: Migration to 17.0
  jsonifier/README.rst
  jsonifier/__init__.py
  jsonifier/__manifest__.py
  jsonifier/demo/export_demo.xml
  jsonifier/demo/ir.exports.line.csv
  jsonifier/demo/resolver_demo.xml
  jsonifier/i18n/ca.po
  jsonifier/i18n/es.po
  jsonifier/i18n/jsonifier.pot
  jsonifier/i18n/zh_CN.po
  jsonifier/models/__init__.py
  jsonifier/models/ir_exports.py
  jsonifier/models/ir_exports_line.py
  jsonifier/models/ir_exports_resolver.py
  jsonifier/models/models.py
  jsonifier/models/utils.py
  jsonifier/pyproject.toml
  jsonifier/readme/CONTRIBUTORS.md
  jsonifier/readme/DESCRIPTION.md
  jsonifier/security/ir.model.access.csv
  jsonifier/static/description/icon.png
  jsonifier/static/description/index.html
  jsonifier/tests/__init__.py
  jsonifier/tests/test_get_parser.py
  jsonifier/tests/test_helpers.py
  jsonifier/tests/test_ir_exports_line.py
  jsonifier/views/ir_exports_resolver_view.xml
  jsonifier/views/ir_exports_view.xml
Labels: bot is merging ⏳

#2812 [16.0] [FIX] database_cleanup: override create in batch
  database_cleanup/models/purge_wizard.py
Labels: approved, ready to merge, bot is merging ⏳

#2578 [16.0][MIG] cron_daylight_saving_time_resistant
  cron_daylight_saving_time_resistant/README.rst
  cron_daylight_saving_time_resistant/__init__.py
  cron_daylight_saving_time_resistant/__manifest__.py
  cron_daylight_saving_time_resistant/models/__init__.py
  cron_daylight_saving_time_resistant/models/ir_cron.py
  cron_daylight_saving_time_resistant/readme/CONFIGURE.rst
  cron_daylight_saving_time_resistant/readme/CONTRIBUTORS.rst
  cron_daylight_saving_time_resistant/readme/DESCRIPTION.rst
  cron_daylight_saving_time_resistant/static/description/index.html
  cron_daylight_saving_time_resistant/tests/__init__.py
  cron_daylight_saving_time_resistant/tests/test_dst.py
  cron_daylight_saving_time_resistant/views/ir_cron_views.xml
  setup/cron_daylight_saving_time_resistant/odoo/addons/cron_daylight_saving_time_resistant
  setup/cron_daylight_saving_time_resistant/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2632 [16.0][MIG] attachment_synchronize
  attachment_synchronize/README.rst
  attachment_synchronize/__init__.py
  attachment_synchronize/__manifest__.py
  attachment_synchronize/data/cron.xml
  attachment_synchronize/demo/attachment_synchronize_task_demo.xml
  attachment_synchronize/i18n/attachment_synchronize.pot
  attachment_synchronize/models/__init__.py
  attachment_synchronize/models/attachment_queue.py
  attachment_synchronize/models/attachment_synchronize_task.py
  attachment_synchronize/models/storage_backend.py
  attachment_synchronize/readme/CONTRIBUTORS.rst
  attachment_synchronize/readme/DESCRIPTION.rst
  attachment_synchronize/readme/USAGE.rst
  attachment_synchronize/security/ir.model.access.csv
  attachment_synchronize/static/description/export_task.png
  attachment_synchronize/static/description/icon.png
  attachment_synchronize/static/description/import_task.png
  attachment_synchronize/static/description/index.html
  attachment_synchronize/tests/__init__.py
  attachment_synchronize/tests/common.py
  attachment_synchronize/tests/test_export.py
  attachment_synchronize/tests/test_import.py
  attachment_synchronize/views/attachment_queue_views.xml
  attachment_synchronize/views/attachment_synchronize_task_views.xml
  attachment_synchronize/views/storage_backend_views.xml
  setup/attachment_synchronize/odoo/addons/attachment_synchronize
  setup/attachment_synchronize/setup.py
Labels: approved, ready to merge, bot is merging ⏳
