Repository OCA/server-tools, pull requests merged in 2025-02, with the labels that each got.

#3181 [18.0][FIX] sentry: add compatibility with sentry-sdk from debian bullseye …
  sentry/const.py
Labels: bot is merging ⏳

#3185 [FIX] session_db: Fix creation of postgres_uri in tests
  session_db/tests/test_pg_session_store.py
Labels: bot is merging ⏳

#3187 [17.0][PORT] 3185 from 16.0
  session_db/tests/test_pg_session_store.py
Labels: bot is merging ⏳

#3190 [18.0][FIX] rpc_helper: mute warning logs to keep checklog-odoo happy
  rpc_helper/tests/test_xmlrpc.py
Labels: approved, bot is merging ⏳

#3188 [18.0][PORT] 3185 from 16.0
  session_db/tests/test_pg_session_store.py
Labels: bot is merging ⏳

#3175 [17.0][IMP] tracking_manager: add field type html support
  tracking_manager/models/__init__.py
  tracking_manager/models/mail_tracking_value.py
  tracking_manager/tests/__init__.py
  tracking_manager/tests/test_mail_tracking_value.py
Labels: approved, ready to merge, bot is merging ⏳

#3195 [FIX] base_remote: RunTime error is raised on tests
  base_remote/models/base.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#3198 [FIX] base_remote: Fix tests
  base_remote/tests/test_remote.py
Labels: bot is merging ⏳

#3200 [IMP] base_import_odoo: Remove mock dependancy
  base_import_odoo/tests/test_base_import_odoo.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#3186 [18.0][MIG] Migration of module_auto_update
  module_auto_update/README.rst
  module_auto_update/__init__.py
  module_auto_update/__manifest__.py
  module_auto_update/addon_hash.py
  module_auto_update/hooks.py
  module_auto_update/i18n/ca.po
  module_auto_update/i18n/cs_CZ.po
  module_auto_update/i18n/de.po
  module_auto_update/i18n/es.po
  module_auto_update/i18n/es_AR.po
  module_auto_update/i18n/es_MX.po
  module_auto_update/i18n/fr.po
  module_auto_update/i18n/hr.po
  module_auto_update/i18n/it.po
  module_auto_update/i18n/module_auto_update.pot
  module_auto_update/i18n/nl_NL.po
  module_auto_update/i18n/pt_BR.po
  module_auto_update/i18n/sl.po
  module_auto_update/i18n/tr.po
  module_auto_update/i18n/zh_CN.po
  module_auto_update/models/__init__.py
  module_auto_update/models/module.py
  module_auto_update/pyproject.toml
  module_auto_update/readme/CONFIGURE.md
  module_auto_update/readme/CONTRIBUTORS.md
  module_auto_update/readme/DESCRIPTION.md
  module_auto_update/readme/USAGE.md
  module_auto_update/static/description/icon.png
  module_auto_update/static/description/index.html
  module_auto_update/tests/__init__.py
  module_auto_update/tests/sample_module/README.rst
  module_auto_update/tests/sample_module/data/f1.xml
  module_auto_update/tests/sample_module/data/f2.xml
  module_auto_update/tests/sample_module/i18n/en_US.po
  module_auto_update/tests/sample_module/i18n/fr.po
  module_auto_update/tests/sample_module/i18n/fr_BE.po
  module_auto_update/tests/sample_module/i18n/test.pot
  module_auto_update/tests/sample_module/i18n_extra/en.po
  module_auto_update/tests/sample_module/i18n_extra/fr.po
  module_auto_update/tests/sample_module/i18n_extra/nl_NL.po
  module_auto_update/tests/sample_module/models/stuff.py
  module_auto_update/tests/sample_module/models/stuff.pyc
  module_auto_update/tests/sample_module/models/stuff.pyo
  module_auto_update/tests/sample_module/static/src/some.js
  module_auto_update/tests/test_addon_hash.py
  module_auto_update/tests/test_module.py
  module_auto_update/views/ir_module_module.xml
Labels: approved, ready to merge, bot is merging ⏳

#3203 [14.0][BKP] jsonifier: Call callable for unknown field
  .oca/oca-port/blacklist/jsonifier.json
  jsonifier/models/models.py
  jsonifier/tests/test_get_parser.py
Labels: bot is merging ⏳

#3205 [16.0][FW] jsonifier: multiple ports from 14.0
  .oca/oca-port/blacklist/jsonifier.json
  jsonifier/exceptions.py
  jsonifier/models/ir_exports.py
  jsonifier/models/ir_exports_resolver.py
  jsonifier/models/models.py
  jsonifier/readme/USAGE.rst
  jsonifier/tests/test_get_parser.py
Labels: bot is merging ⏳

#3204 [17.0][MIG] html_text
  html_text/README.rst
  html_text/__init__.py
  html_text/__manifest__.py
  html_text/i18n/ca.po
  html_text/i18n/de.po
  html_text/i18n/es.po
  html_text/i18n/es_AR.po
  html_text/i18n/es_ES.po
  html_text/i18n/hr.po
  html_text/i18n/html_text.pot
  html_text/i18n/it.po
  html_text/i18n/tr.po
  html_text/i18n/zh_CN.po
  html_text/models/__init__.py
  html_text/models/ir_fields_converter.py
  html_text/pyproject.toml
  html_text/readme/CONTRIBUTORS.md
  html_text/readme/DESCRIPTION.md
  html_text/readme/ROADMAP.md
  html_text/readme/USAGE.md
  html_text/static/description/icon.png
  html_text/static/description/index.html
  html_text/tests/__init__.py
  html_text/tests/test_extractor.py
Labels: approved, bot is merging ⏳

#3206 [18.0][FWD] jsonifier: misc imp/fix from 16.0 and 14.0
  .oca/oca-port/blacklist/jsonifier.json
  jsonifier/models/ir_exports.py
  jsonifier/models/models.py
  jsonifier/tests/test_get_parser.py
Labels: bot is merging ⏳
