Repository OCA/server-tools, pull requests merged in 2025-01, with the labels that each got.

#3148 [18.0][FIX] upgrade_analysis: forward ports
  upgrade_analysis/README.rst
  upgrade_analysis/compare.py
  upgrade_analysis/models/upgrade_analysis.py
  upgrade_analysis/models/upgrade_comparison_config.py
  upgrade_analysis/static/description/index.html
  upgrade_analysis/tests/test_module.py
  upgrade_analysis/upgrade_log.py
  upgrade_analysis/wizards/upgrade_install_wizard.py
Labels: approved, bot is merging ⏳

#3143 [16.0][FIX] upgrade_analysis: forward ports
  upgrade_analysis/README.rst
  upgrade_analysis/models/upgrade_analysis.py
  upgrade_analysis/models/upgrade_comparison_config.py
  upgrade_analysis/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳

#2819 [16.0][IMP] base_time_window: Add helper function to get next Date matching weekday
  base_time_window/models/time_weekday.py
  base_time_window/tests/__init__.py
  base_time_window/tests/test_weekday.py
Labels: needs review, bot is merging ⏳

#3159 [FIX] odoo_test_xmlrunner: set auto_install to False.
  odoo_test_xmlrunner/README.rst
  odoo_test_xmlrunner/__manifest__.py
Labels: bot is merging ⏳

#3167 [18.0][FIX] base_cron_exclusion: remove numbercall condition from ir_cron select clause
  base_cron_exclusion/models/ir_cron.py
Labels: bot is merging ⏳

#3166 [IMP] base_exception: Add a hook method / Don't build void exceptions
  base_exception/models/base_exception_method.py
Labels: approved, bot is merging ⏳

#3168 [FIX] base_multi_image: Attribute Error
  base_multi_image/models/image.py
Labels: approved, bot is merging ⏳

#3171 [18.0] upgrade_analysis: add missing xml file to manifest
  upgrade_analysis/__manifest__.py
Labels: approved, bot is merging ⏳

#3172 [18.0][ADD] upgrade_analysis: be more helpful for v18 property conversion
  upgrade_analysis/compare.py
Labels: approved, bot is merging ⏳

#3140 [16.0][UPD][FIX] tracking_manager: specific O2M fields notify
  tracking_manager/models/models.py
Labels: approved, bot is merging ⏳

#3158 [18.0][MIG] autovacuum_message_attachment: Migration to 18.0
  autovacuum_message_attachment/README.rst
  autovacuum_message_attachment/__init__.py
  autovacuum_message_attachment/__manifest__.py
  autovacuum_message_attachment/data/data.xml
  autovacuum_message_attachment/i18n/autovacuum_mail_message.pot
  autovacuum_message_attachment/i18n/autovacuum_message_attachment.pot
  autovacuum_message_attachment/i18n/ca.po
  autovacuum_message_attachment/i18n/es.po
  autovacuum_message_attachment/i18n/es_AR.po
  autovacuum_message_attachment/i18n/fr.po
  autovacuum_message_attachment/i18n/it.po
  autovacuum_message_attachment/models/__init__.py
  autovacuum_message_attachment/models/autovacuum_mixin.py
  autovacuum_message_attachment/models/base.py
  autovacuum_message_attachment/models/ir_attachment.py
  autovacuum_message_attachment/models/mail_message.py
  autovacuum_message_attachment/models/vacuum_rule.py
  autovacuum_message_attachment/pyproject.toml
  autovacuum_message_attachment/readme/CONFIGURE.md
  autovacuum_message_attachment/readme/CONTRIBUTORS.md
  autovacuum_message_attachment/readme/DESCRIPTION.md
  autovacuum_message_attachment/readme/ROADMAP.md
  autovacuum_message_attachment/security/ir.model.access.csv
  autovacuum_message_attachment/static/description/icon.png
  autovacuum_message_attachment/static/description/index.html
  autovacuum_message_attachment/tests/__init__.py
  autovacuum_message_attachment/tests/test_vacuum_rule.py
  autovacuum_message_attachment/views/rule_vacuum.xml
Labels: approved, ready to merge, bot is merging ⏳

#3178 [FIX] sentry: add compatibility with sentry-sdk from debian bullseye repository
  sentry/const.py
Labels: bot is merging ⏳

#3179 [FW][FIX] sentry: add compatibility with sentry-sdk from debian bullseye repository
  sentry/const.py
Labels: bot is merging ⏳

#3174 [18.0][MIG] sentry: sentry_sdk version update
  requirements.txt
  sentry/README.rst
  sentry/__init__.py
  sentry/__manifest__.py
  sentry/const.py
  sentry/generalutils.py
  sentry/hooks.py
  sentry/i18n/ca.po
  sentry/i18n/it.po
  sentry/i18n/sentry.pot
  sentry/i18n/zh_CN.po
  sentry/logutils.py
  sentry/processor.py
  sentry/pyproject.toml
  sentry/readme/CONFIGURE.md
  sentry/readme/CONTRIBUTORS.md
  sentry/readme/CREDITS.md
  sentry/readme/DESCRIPTION.md
  sentry/readme/INSTALL.md
  sentry/readme/ROADMAP.md
  sentry/readme/USAGE.md
  sentry/static/description/icon.png
  sentry/static/description/index.html
  sentry/tests/__init__.py
  sentry/tests/test_client.py
  sentry/tests/test_generalutils.py
  sentry/tests/test_logutils.py
  sentry/tests/test_processor.py
Labels: bot is merging ⏳
