Repository OCA/server-tools, pull requests merged in 2025-05, with the labels that each got.

#3017 [16.0][FIX] fetch...folder: use message uid's not sequence
  fetchmail_attach_from_folder/models/fetchmail_server_folder.py
  fetchmail_attach_from_folder/tests/test_match_algorithms.py
Labels: approved, ready to merge, bot is merging ⏳

#2974 [17.0][MIG] base_fontawesome: Migration to 17.0
  base_fontawesome/README.rst
  base_fontawesome/__init__.py
  base_fontawesome/__manifest__.py
  base_fontawesome/i18n/base_fontawesome.pot
  base_fontawesome/i18n/es_AR.po
  base_fontawesome/i18n/es_ES.po
  base_fontawesome/i18n/it.po
  base_fontawesome/i18n/zh_CN.po
  base_fontawesome/pyproject.toml
  base_fontawesome/readme/CONTRIBUTORS.md
  base_fontawesome/readme/DESCRIPTION.md
  base_fontawesome/readme/USAGE.md
  base_fontawesome/static/description/icon.png
  base_fontawesome/static/description/index.html
  base_fontawesome/static/lib/fontawesome-6.5.1/css/all.css
  base_fontawesome/static/lib/fontawesome-6.5.1/css/v4-shims.css
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-brands-400.ttf
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-brands-400.woff2
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-regular-400.ttf
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-regular-400.woff2
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-solid-900.ttf
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-solid-900.woff2
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-v4compatibility.ttf
  base_fontawesome/static/lib/fontawesome-6.5.1/webfonts/fa-v4compatibility.woff2
  base_fontawesome/static/src/css/fontawesome.css
Labels: bot is merging ⏳

#3191 [17.0][MIG] attachment_queue: Migration to 17.0
  attachment_queue/README.rst
  attachment_queue/__init__.py
  attachment_queue/__manifest__.py
  attachment_queue/data/mail_template.xml
  attachment_queue/data/queue_job_channel.xml
  attachment_queue/demo/attachment_queue.xml
  attachment_queue/i18n/attachment_queue.pot
  attachment_queue/i18n/es.po
  attachment_queue/i18n/it.po
  attachment_queue/models/__init__.py
  attachment_queue/models/attachment_queue.py
  attachment_queue/pyproject.toml
  attachment_queue/readme/CONTRIBUTORS.md
  attachment_queue/readme/DESCRIPTION.md
  attachment_queue/readme/USAGE.md
  attachment_queue/security/ir.model.access.csv
  attachment_queue/static/description/form.png
  attachment_queue/static/description/icon.png
  attachment_queue/static/description/index.html
  attachment_queue/static/description/tree.png
  attachment_queue/tests/__init__.py
  attachment_queue/tests/test_attachment_queue.py
  attachment_queue/tests/test_models.py
  attachment_queue/views/attachment_queue_view.xml
  attachment_queue/wizards/__init__.py
  attachment_queue/wizards/attachement_queue_reschedule.py
  attachment_queue/wizards/attachement_queue_reschedule.xml
Labels: approved, bot is merging ⏳

#3287 [FIX] module_change_auto_install : prevent to crash if a module is not present in the addons path.
  module_change_auto_install/patch.py
Labels: bot is merging ⏳

#3284 short note about the astor lib
  base_view_inheritance_extension/readme/INSTALL.rst
Labels: bot is merging ⏳

#2953 [14.0][MIG] base_force_record_noupdate: Backport to 14.0
  base_force_record_noupdate/README.rst
  base_force_record_noupdate/__init__.py
  base_force_record_noupdate/__manifest__.py
  base_force_record_noupdate/i18n/base_force_record_noupdate.pot
  base_force_record_noupdate/models/__init__.py
  base_force_record_noupdate/models/ir_model.py
  base_force_record_noupdate/models/ir_model_data.py
  base_force_record_noupdate/readme/CONTRIBUTORS.rst
  base_force_record_noupdate/readme/DESCRIPTION.rst
  base_force_record_noupdate/readme/USAGE.rst
  base_force_record_noupdate/static/description/icon.png
  base_force_record_noupdate/static/description/index.html
  base_force_record_noupdate/tests/__init__.py
  base_force_record_noupdate/tests/test_base_force_record_noupdate.py
  base_force_record_noupdate/views/ir_model.xml
  setup/base_force_record_noupdate/odoo/addons/base_force_record_noupdate
  setup/base_force_record_noupdate/setup.py
Labels: bot is merging ⏳

#3270 [16.0][ADD] postgres_vacuum
  postgres_vacuum/README.rst
  postgres_vacuum/__init__.py
  postgres_vacuum/__manifest__.py
  postgres_vacuum/data/ir_cron.xml
  postgres_vacuum/models/__init__.py
  postgres_vacuum/models/ir_cron.py
  postgres_vacuum/readme/CONFIGURE.md
  postgres_vacuum/readme/CONTRIBUTORS.md
  postgres_vacuum/readme/DESCRIPTION.md
  postgres_vacuum/readme/ROADMAP.md
  postgres_vacuum/readme/USAGE.md
  postgres_vacuum/static/description/icon.png
  postgres_vacuum/static/description/index.html
  postgres_vacuum/tests/__init__.py
  postgres_vacuum/tests/test_postgres_vacuum.py
  setup/postgres_vacuum/odoo/addons/postgres_vacuum
  setup/postgres_vacuum/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3289 [18.0][FIX] upgrade_analysis: avoid breaking coverage file
  upgrade_analysis/models/upgrade_analysis.py
Labels: approved, bot is merging ⏳

#3290 [18.0][FIX] upgrade_analysis: avoid caring about non stored fields
  upgrade_analysis/compare.py
Labels: approved, bot is merging ⏳

#3296 [18.0][FIX] upgrade_analysis: non-stored has to be shown
  upgrade_analysis/compare.py
Labels: bot is merging ⏳
