Repository OCA/server-tools, pull requests merged in 2025-03, with the labels that each got.

#3216 [17.0][FIX] upgrade_analysis: fill upgrade_path
  upgrade_analysis/models/upgrade_analysis.py
Labels: approved, bot is merging ⏳

#3219 [18.0][FIX] upgrade_analysis: fill upgrade_path
  upgrade_analysis/models/upgrade_analysis.py
Labels: bot is merging ⏳

#3218 [16.0][FIX] upgrade_analysis: avoid call privatized 'mapped' function.
  upgrade_analysis/models/upgrade_analysis.py
Labels: approved, bot is merging ⏳

#3071 [17.0][MIG] fetchmail_attach_from_folder: Migration to 17.0
  fetchmail_attach_from_folder/README.rst
  fetchmail_attach_from_folder/__init__.py
  fetchmail_attach_from_folder/__manifest__.py
  fetchmail_attach_from_folder/i18n/de.po
  fetchmail_attach_from_folder/i18n/es.po
  fetchmail_attach_from_folder/i18n/fetchmail_attach_from_folder.pot
  fetchmail_attach_from_folder/i18n/fr.po
  fetchmail_attach_from_folder/i18n/fr_CA.po
  fetchmail_attach_from_folder/i18n/it.po
  fetchmail_attach_from_folder/i18n/pt_BR.po
  fetchmail_attach_from_folder/i18n/ru.po
  fetchmail_attach_from_folder/i18n/sl.po
  fetchmail_attach_from_folder/match_algorithm/__init__.py
  fetchmail_attach_from_folder/match_algorithm/email_domain.py
  fetchmail_attach_from_folder/match_algorithm/email_exact.py
  fetchmail_attach_from_folder/models/__init__.py
  fetchmail_attach_from_folder/models/fetchmail_server.py
  fetchmail_attach_from_folder/models/fetchmail_server_folder.py
  fetchmail_attach_from_folder/pyproject.toml
  fetchmail_attach_from_folder/readme/CONFIGURE.md
  fetchmail_attach_from_folder/readme/CONTRIBUTORS.md
  fetchmail_attach_from_folder/readme/DESCRIPTION.md
  fetchmail_attach_from_folder/readme/USAGE.md
  fetchmail_attach_from_folder/security/ir.model.access.csv
  fetchmail_attach_from_folder/static/description/icon.png
  fetchmail_attach_from_folder/static/description/index.html
  fetchmail_attach_from_folder/tests/__init__.py
  fetchmail_attach_from_folder/tests/test_match_algorithms.py
  fetchmail_attach_from_folder/views/fetchmail_server.xml
  fetchmail_attach_from_folder/wizard/__init__.py
  fetchmail_attach_from_folder/wizard/attach_mail_manually.py
  fetchmail_attach_from_folder/wizard/attach_mail_manually.xml
Labels: approved, bot is merging ⏳

#3225 [mig] base_sparse_field_list_support: migrate to v18
  base_sparse_field_list_support/README.rst
  base_sparse_field_list_support/__init__.py
  base_sparse_field_list_support/__manifest__.py
  base_sparse_field_list_support/i18n/base_sparse_field_list_support.pot
  base_sparse_field_list_support/i18n/it.po
  base_sparse_field_list_support/models/__init__.py
  base_sparse_field_list_support/models/fields.py
  base_sparse_field_list_support/pyproject.toml
  base_sparse_field_list_support/readme/CONTRIBUTORS.md
  base_sparse_field_list_support/readme/DESCRIPTION.md
  base_sparse_field_list_support/static/description/icon.png
  base_sparse_field_list_support/static/description/index.html
Labels: approved, bot is merging ⏳

#3133 [18.0][MIG] base_name_search_improved: Migration to 18.0
  base_name_search_improved/README.rst
  base_name_search_improved/__init__.py
  base_name_search_improved/__manifest__.py
  base_name_search_improved/hooks.py
  base_name_search_improved/i18n/base_name_search_improved.pot
  base_name_search_improved/i18n/ca.po
  base_name_search_improved/i18n/de.po
  base_name_search_improved/i18n/es.po
  base_name_search_improved/i18n/es_ES.po
  base_name_search_improved/i18n/eu.po
  base_name_search_improved/i18n/fi.po
  base_name_search_improved/i18n/fr.po
  base_name_search_improved/i18n/hr.po
  base_name_search_improved/i18n/hr_HR.po
  base_name_search_improved/i18n/it.po
  base_name_search_improved/i18n/nb_NO.po
  base_name_search_improved/i18n/nl.po
  base_name_search_improved/i18n/pt_BR.po
  base_name_search_improved/i18n/sl.po
  base_name_search_improved/i18n/tr.po
  base_name_search_improved/i18n/tr_TR.po
  base_name_search_improved/i18n/zh_CN.po
  base_name_search_improved/images/image0.png
  base_name_search_improved/images/image1.png
  base_name_search_improved/images/image2.png
  base_name_search_improved/images/image3.png
  base_name_search_improved/models/__init__.py
  base_name_search_improved/models/ir_model.py
  base_name_search_improved/pyproject.toml
  base_name_search_improved/readme/CONFIGURE.md
  base_name_search_improved/readme/CONTRIBUTORS.md
  base_name_search_improved/readme/CREDITS.md
  base_name_search_improved/readme/DESCRIPTION.md
  base_name_search_improved/readme/ROADMAP.md
  base_name_search_improved/readme/USAGE.md
  base_name_search_improved/static/description/icon.png
  base_name_search_improved/static/description/index.html
  base_name_search_improved/tests/__init__.py
  base_name_search_improved/tests/test_name_search.py
  base_name_search_improved/views/ir_model_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2967 [16.0] module_analysis: pin pygount dependency
  module_analysis/__manifest__.py
  requirements.txt
Labels: approved, bot is merging ⏳

#3231 [FIX] sentry: temporarily exclude sentry_sdk>=2.23.1
  requirements.txt
  sentry/__manifest__.py
Labels: approved, bot is merging ⏳

#3212 [18.0][FIX] autovacuum_message_attachment: replace old tree node by list node
  autovacuum_message_attachment/views/rule_vacuum.xml
Labels: approved, ready to merge, bot is merging ⏳

#3237 [FIX][17.0] module_analysis: readme
  module_analysis/README.rst
  module_analysis/__manifest__.py
  module_analysis/readme/CONFIGURE.md
  module_analysis/readme/DESCRIPTION.md
  module_analysis/readme/USAGE.md
  module_analysis/static/description/index.html
  requirements.txt
Labels: bot is merging ⏳

#3234 [18.0][FIX]base_view_inheritance_extension: fix deprecation warning
  base_view_inheritance_extension/models/ir_ui_view.py
Labels: approved, bot is merging ⏳

#3242 [18.0] base_technical_user: add development_status
  base_technical_user/__manifest__.py
Labels: bot is merging ⏳

#3244 [18.0][FIX] upgrade_analysis: avoid call privatized 'mapped' function. (forward port)
  upgrade_analysis/models/upgrade_analysis.py
Labels: bot is merging ⏳

#3236 [17.0][ADD] tracking_manager_domain: add domain condition for tracking_manager fields
  tracking_manager_domain/README.rst
  tracking_manager_domain/__init__.py
  tracking_manager_domain/__manifest__.py
  tracking_manager_domain/models/__init__.py
  tracking_manager_domain/models/ir_model_fields.py
  tracking_manager_domain/models/models.py
  tracking_manager_domain/pyproject.toml
  tracking_manager_domain/readme/CONTRIBUTORS.md
  tracking_manager_domain/readme/USAGE.md
  tracking_manager_domain/static/description/fields.drawio.png
  tracking_manager_domain/static/description/icon.png
  tracking_manager_domain/static/description/index.html
  tracking_manager_domain/tests/__init__.py
  tracking_manager_domain/tests/test_models.py
  tracking_manager_domain/views/ir_model_fields.xml
Labels: approved, ready to merge, bot is merging ⏳
