Repository OCA/server-tools, pull requests merged in 2025-06, with the labels that each got.

#3301 [14.0][FIX]model_read_only: superuser exempt from the restriction
  model_read_only/models/models.py
  model_read_only/tests/test_models.py
Labels: approved, ready to merge, bot is merging ⏳

#3189 [IMP] views_migration_17: support alternative output directory for transformed views instead of in-place write
  views_migration_17/README.rst
  views_migration_17/patch_xml_import.py
  views_migration_17/readme/USAGE.rst
Labels: approved, bot is merging ⏳

#3267 [18.0][FIX] tracking_manager: Solved the invalid recordset issue
  tracking_manager/models/models.py
Labels: approved, merged 🎉

#3299 [18.0][IMP] upgrade_analysis: consider 'translate' value attribute
  upgrade_analysis/compare.py
  upgrade_analysis/models/upgrade_record.py
  upgrade_analysis/upgrade_log.py
Labels: approved, bot is merging ⏳

#3311 [17.0][IMP] tracking_manager: Properties compatibility
  tracking_manager/README.rst
  tracking_manager/models/mail_tracking_value.py
  tracking_manager/models/models.py
  tracking_manager/tests/test_mail_tracking_value.py
  tracking_manager_domain/models/models.py
Labels: approved, bot is merging ⏳

#3314 [16.0][FIX] base_exception: confirmation wizard button typo
  base_exception/wizard/base_exception_confirm_view.xml
Labels: bot is merging ⏳

#3315 [18.0][IMP] upgrade_analysis: tell user which selection keys were added/removed
  upgrade_analysis/compare.py
  upgrade_analysis/tests/test_module.py
Labels: approved, bot is merging ⏳

#3316 [18.0][IMP] tracking_manager: Properties compatibility
  tracking_manager/README.rst
  tracking_manager/models/mail_tracking_value.py
  tracking_manager/models/models.py
  tracking_manager/tests/test_mail_tracking_value.py
Labels: approved, bot is merging ⏳

#3321 [17.0][FW][FIX] auditlog rue: Control the write function in the models when executed by an onchange function
  auditlog/models/rule.py
Labels: approved, bot is merging ⏳

#2924 [16.0][FIX] auditlog rue: Control the write function in the models when executed by an onchange function
  auditlog/models/rule.py
Labels: approved, ready to merge, bot is merging ⏳

#3084 [18.0][MIG] scheduler_error_mailer
  scheduler_error_mailer/README.rst
  scheduler_error_mailer/__init__.py
  scheduler_error_mailer/__manifest__.py
  scheduler_error_mailer/data/ir_cron_email_tpl.xml
  scheduler_error_mailer/demo/ir_cron_demo.xml
  scheduler_error_mailer/hooks.py
  scheduler_error_mailer/i18n/de.po
  scheduler_error_mailer/i18n/es.po
  scheduler_error_mailer/i18n/es_AR.po
  scheduler_error_mailer/i18n/fr.po
  scheduler_error_mailer/i18n/hr.po
  scheduler_error_mailer/i18n/it.po
  scheduler_error_mailer/i18n/pt.po
  scheduler_error_mailer/i18n/pt_BR.po
  scheduler_error_mailer/i18n/scheduler_error_mailer.pot
  scheduler_error_mailer/i18n/sl.po
  scheduler_error_mailer/i18n/zh_CN.po
  scheduler_error_mailer/images/scheduler_error_mailer.jpg
  scheduler_error_mailer/migrations/18.0.1.0.0/post-migration.py
  scheduler_error_mailer/models/__init__.py
  scheduler_error_mailer/models/ir_cron.py
  scheduler_error_mailer/pyproject.toml
  scheduler_error_mailer/readme/CONFIGURE.md
  scheduler_error_mailer/readme/CONTRIBUTORS.md
  scheduler_error_mailer/readme/DESCRIPTION.md
  scheduler_error_mailer/static/description/icon.png
  scheduler_error_mailer/static/description/index.html
  scheduler_error_mailer/tests/__init__.py
  scheduler_error_mailer/tests/test_scheduler_error_mailer.py
  scheduler_error_mailer/views/ir_cron.xml
Labels: approved, ready to merge, bot is merging ⏳
