Repository OCA/server-tools, pull requests merged in 2025-09, with the labels that each got.

#3333 [18.0][mail_cleanup]FIX : respect method signature
  mail_cleanup/models/fetchmail_server.py
Labels: approved, bot is merging ⏳

#3362 [15.0][IMP] tracking_manager: Check records not empty
  tracking_manager/tools.py
Labels: approved, bot is merging ⏳

#3358 [16.0][FIX] auditlog: safeguard name_get for deleted records
  auditlog/README.rst
  auditlog/__manifest__.py
  auditlog/models/rule.py
  auditlog/static/description/index.html
  auditlog/tests/test_auditlog.py
Labels: approved, ready to merge, bot is merging ⏳

#3366 [15.0][FIX] module_analysis: pin pygount
  module_analysis/__manifest__.py
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#3317 [17.0][FIX] base_view_inheritance_extension: multiple DepreciationWarning
  base_view_inheritance_extension/__manifest__.py
  base_view_inheritance_extension/models/ir_ui_view.py
  requirements.txt
Labels: approved, bot is merging ⏳

#3338 [18.0] auditlog: Log exports
  auditlog/README.rst
  auditlog/models/log.py
  auditlog/models/rule.py
  auditlog/readme/CONTRIBUTORS.md
  auditlog/static/description/index.html
  auditlog/tests/test_auditlog.py
  auditlog/views/auditlog_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#3210 [18.0] [MIG] base_sequence_option
  base_sequence_option/README.rst
  base_sequence_option/__init__.py
  base_sequence_option/__manifest__.py
  base_sequence_option/i18n/base_sequence_option.pot
  base_sequence_option/i18n/es.po
  base_sequence_option/i18n/it.po
  base_sequence_option/models/__init__.py
  base_sequence_option/models/ir_sequence.py
  base_sequence_option/models/ir_sequence_option.py
  base_sequence_option/pyproject.toml
  base_sequence_option/readme/CONTRIBUTORS.md
  base_sequence_option/readme/DESCRIPTION.md
  base_sequence_option/readme/USAGE.md
  base_sequence_option/security/ir.model.access.csv
  base_sequence_option/security/sequence_option_security.xml
  base_sequence_option/static/description/icon.png
  base_sequence_option/static/description/index.html
  base_sequence_option/tests/__init__.py
  base_sequence_option/tests/base_sequence_tester.py
  base_sequence_option/tests/common.py
  base_sequence_option/tests/test_ir_sequence_option.py
  base_sequence_option/views/sequence_option_view.xml
  requirements.txt
Labels: approved, bot is merging ⏳

#3378 Remove pygount hardcoded version and improve compatibility
  module_analysis/__manifest__.py
  module_analysis/models/ir_module_module.py
  requirements.txt
Labels: bot is merging ⏳

#3319 [18.0][MIG] base_model_restrict_update: Migration to 18.0
  base_model_restrict_update/README.rst
  base_model_restrict_update/__init__.py
  base_model_restrict_update/__manifest__.py
  base_model_restrict_update/data/config_parameter_data.xml
  base_model_restrict_update/i18n/es.po
  base_model_restrict_update/i18n/es_AR.po
  base_model_restrict_update/i18n/ja_JP.po
  base_model_restrict_update/models/__init__.py
  base_model_restrict_update/models/ir_model.py
  base_model_restrict_update/models/ir_model_access.py
  base_model_restrict_update/models/res_config_settings.py
  base_model_restrict_update/models/res_users.py
  base_model_restrict_update/pyproject.toml
  base_model_restrict_update/readme/CONFIGURE.md
  base_model_restrict_update/readme/CONTRIBUTORS.md
  base_model_restrict_update/readme/CREDITS.md
  base_model_restrict_update/readme/DESCRIPTION.md
  base_model_restrict_update/static/description/icon.png
  base_model_restrict_update/static/description/index.html
  base_model_restrict_update/tests/__init__.py
  base_model_restrict_update/tests/test_base_model_restrict_update.py
  base_model_restrict_update/views/ir_model_views.xml
  base_model_restrict_update/views/res_config_settings.xml
  base_model_restrict_update/views/res_users_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2831 [17.0][MIG] base_name_search_improved: Migration to 17.0
  base_name_search_improved/README.rst
  base_name_search_improved/__init__.py
  base_name_search_improved/__manifest__.py
  base_name_search_improved/hooks.py
  base_name_search_improved/i18n/base_name_search_improved.pot
  base_name_search_improved/i18n/ca.po
  base_name_search_improved/i18n/de.po
  base_name_search_improved/i18n/es.po
  base_name_search_improved/i18n/es_ES.po
  base_name_search_improved/i18n/eu.po
  base_name_search_improved/i18n/fi.po
  base_name_search_improved/i18n/fr.po
  base_name_search_improved/i18n/hr.po
  base_name_search_improved/i18n/hr_HR.po
  base_name_search_improved/i18n/it.po
  base_name_search_improved/i18n/nb_NO.po
  base_name_search_improved/i18n/nl.po
  base_name_search_improved/i18n/pt_BR.po
  base_name_search_improved/i18n/sl.po
  base_name_search_improved/i18n/tr.po
  base_name_search_improved/i18n/tr_TR.po
  base_name_search_improved/i18n/zh_CN.po
  base_name_search_improved/images/image0.png
  base_name_search_improved/images/image1.png
  base_name_search_improved/images/image2.png
  base_name_search_improved/images/image3.png
  base_name_search_improved/models/__init__.py
  base_name_search_improved/models/ir_model.py
  base_name_search_improved/pyproject.toml
  base_name_search_improved/readme/CONFIGURE.md
  base_name_search_improved/readme/CONTRIBUTORS.md
  base_name_search_improved/readme/CREDITS.md
  base_name_search_improved/readme/DESCRIPTION.md
  base_name_search_improved/readme/ROADMAP.md
  base_name_search_improved/readme/USAGE.md
  base_name_search_improved/static/description/icon.png
  base_name_search_improved/static/description/index.html
  base_name_search_improved/tests/__init__.py
  base_name_search_improved/tests/test_name_search.py
  base_name_search_improved/views/ir_model_views.xml
Labels: approved, ready to merge, bot is merging ⏳
